bloom-housing/bloom

apps/public/lib/unit_summaries.tsx
apps/public/pages/listing.tsx
shared/ui-components/src/helpers/address.tsx
shared/ui-components/src/page_components/listing_sidebar/leasing_agent.tsx
shared/ui-components/src/page_components/listing_sidebar/what_to_expect.tsx
shared/ui-components/src/page_components/listings_list.tsx
shared/ui-components/src/types.ts

Various issues in these components were both blocking Storybook from launching and also blocking commit by failing the husky eslint precommit hook. Open to adjustments on how we resolve these errors.

Fix ts compliance issues in some components

---

apps/public/lib/unit_summaries.tsx
apps/public/pages/listing.tsx
shared/ui-components/.storybook/config.ts
shared/ui-components/.storybook/webpack.config.js
shared/ui-components/package.json
shared/ui-components/src/helpers/address.tsx
shared/ui-components/src/page_components/listing_sidebar/leasing_agent.tsx
shared/ui-components/src/page_components/listing_sidebar/what_to_expect.tsx
shared/ui-components/src/page_components/listings_list.tsx
shared/ui-components/src/types.ts
yarn.lock

Correcting the incorrect merge order from from PR #21

Add css to storybook correctly

---

apps/public/package.json
package.json
services/listings/package.json
shared/ui-components/package.json
yarn.lock

Did quick local tests, and it seems like an uneventful upgrade.

upgrade to typescript 3.6 and other minor dep changes

---

apps/public/pages/listing.tsx
apps/public/static/images/listing-process.svg
shared/ui-components/src/page_components/listing/listing_sidebar/Apply.tsx

Fixes mobile side bar from issue #42

Mobile sidebar

---

apps/public/pages/index.tsx
shared/ui-components/src/headers/hero.tsx

Add subheader when all listings are closed

---

apps/public/pages/listing.tsx
shared/styles/src/accordion.scss
shared/styles/src/cards.scss
shared/styles/src/custom_counter.scss
shared/styles/src/hero.scss
shared/styles/src/image_card.scss
shared/styles/src/index.scss
shared/styles/src/lists.scss
shared/styles/src/mixins.scss
shared/styles/src/tables.scss
shared/styles/src/text.scss
shared/styles/tailwind.config.js
shared/ui-components/src/atoms/LocalizedLink.tsx
shared/ui-components/src/cards/InfoCard.tsx
shared/ui-components/src/cards/image_card.tsx
shared/ui-components/src/headers/hero.tsx
shared/ui-components/src/headers/image_header/image_header.tsx
shared/ui-components/src/lists/ResponsiveContentList/ResponsiveContentList.tsx
shared/ui-components/src/page_components/listing/ListingDetailHeader.tsx
shared/ui-components/src/page_components/listing/ListingDetails.tsx
shared/ui-components/src/page_components/listing/ListingsList.tsx
shared/ui-components/src/page_components/listing/listing_sidebar/ApplicationDeadline.tsx
shared/ui-components/src/page_components/listing/listing_sidebar/Apply.tsx
shared/ui-components/src/page_components/listing/listing_sidebar/LeasingAgent.tsx
shared/ui-components/src/page_components/listing/listing_sidebar/SidebarAddress.tsx
shared/ui-components/src/page_components/listing/listing_sidebar/Waitlist.tsx
shared/ui-components/src/page_components/listing/listing_sidebar/WhatToExpect.tsx
shared/ui-components/src/page_components/unit_tables.tsx
shared/ui-components/src/sections/ListSection.tsx

Lots of new work to tighten up components on single listing

Css updates

---

shared/ui-components/src/page_components/unit_tables.tsx
shared/ui-components/styles/text.scss

Fix unit features table spacing

---

services/listings/src/lib/unit_transformations.ts
shared/core/src/general.ts
shared/core/src/units.ts
shared/ui-components/src/atoms/LinkButton.tsx
shared/ui-components/src/page_components/unit_tables.tsx
shared/ui-components/src/tables/basic_table.tsx

Fix untyped

---

apps/public/pages/_app.jsx
apps/public/static/locale_overrides/general.json

Provide custom locale overrides

---

README.md
apps/public/pages/listing.tsx
shared/ui-components/src/lists/ResponsiveContentList/ResponsiveContentList.tsx
shared/ui-components/src/page_components/listing/ListingDetailHeader.tsx
shared/ui-components/src/page_components/listing/ListingDetails.tsx
shared/ui-components/styles/lists.scss

Hide process section on desktop

---

apps/public/pages/listing.tsx
shared/core/src/listings.ts
shared/ui-components/styles/lists.scss

Add more feature descriptions

---

apps/public/pages/listing.tsx
shared/core/src/listings.ts

Additional Information section

---

apps/public/pages/listing.tsx
services/listings/listings/triton.json
shared/core/src/listings.ts
shared/ui-components/static/locales/general.json

Add criminal background & more translated strings

---

services/listings/__tests__/index.test.ts
services/listings/package.json
services/listings/src/index.ts
services/listings/src/lib/listings_loader.ts
yarn.lock

I looked into JSONQuery and JSONPath and the latter seemed pretty solid to me, so I've implemented that here. All listings come back from the endpoint by default, but if you supply a `jsonpath` query param, it'll filter down the array accordingly (an example URL is in a comment). Let me know what you think.

Listings loader and filtering via jsonpath

---

shared/core/src/listings.ts
shared/ui-components/src/atoms/Button.scss
shared/ui-components/src/atoms/LinkButton.tsx
shared/ui-components/src/locales/general.json
shared/ui-components/src/page_components/listing/listing_sidebar/Apply.stories.tsx
shared/ui-components/src/page_components/listing/listing_sidebar/Apply.tsx

Support external online application urls

---

shared/ui-components/src/headers/SiteHeader/SiteHeader.tsx
shared/ui-components/styles/navbar.scss

Upstreams improvements from the Alameda site

Improve utility of the navbar notice

---

apps/public-reference/layouts/application.tsx
shared/ui-components/src/footers/ExygyFooter.tsx
shared/ui-components/src/footers/FooterNav/FooterNav.scss
shared/ui-components/src/footers/FooterNav/FooterNav.tsx
shared/ui-components/src/footers/FooterSection/FooterSection.scss
shared/ui-components/src/footers/FooterSection/FooterSection.tsx
shared/ui-components/src/footers/SiteFooter/SiteFooter.scss
shared/ui-components/src/footers/SiteFooter/SiteFooter.stories.tsx
shared/ui-components/src/footers/SiteFooter/SiteFooter.tsx
shared/ui-components/src/footers/SiteFooter/__snapshots__/SiteFooter.stories.storyshot

Customizable footer component

---

shared/ui-components/src/helpers/tableSummaries.tsx
shared/ui-components/src/page_components/__snapshots__/UnitTables.stories.storyshot

Add min income and rent ranges to summaries

---

shared/ui-components/package.json
shared/ui-components/src/page_components/listing/ListingMap.tsx
shared/ui-components/src/page_components/listing/__snapshots__/ListingMap.stories.storyshot
yarn.lock

Fixes #184
(P.S. It seems to me like a bug in react-map-gl that the width/height have to be set in the viewport callback for this to work, but it was the only solution I could come up with.)

Fix map on mobile layout

---

apps/public-reference/pages/_error.jsx
shared/ui-components/src/headers/Hero/Hero.scss
shared/ui-components/src/headers/Hero/Hero.tsx
shared/ui-components/src/locales/general.json

Error page and Hero style updates

---

shared/ui-components/src/cards/InfoCard.tsx

Small downstream enhancement added to InfoCard

Add external href to InfoCard

---

apps/public-reference/pages/listing.tsx
services/listings/listings/gish.json
shared/core/src/listings.ts
shared/ui-components/src/page_components/UnitTables.stories.tsx
shared/ui-components/src/page_components/UnitTables.tsx
shared/ui-components/src/page_components/__snapshots__/UnitTables.stories.storyshot

Disable the units list accordion

---

apps/public-reference/package.json
shared/core/package.json
shared/ui-components/package.json

and add homepage fields to shared package.json files

Use newest ui-components and core in reference app

---

shared/ui-components/src/locales/general.json
shared/ui-components/src/page_components/listing/listing_sidebar/Waitlist.tsx

Needed for downstream content improvements.

Fix Waitlist sidebar bugs

---

apps/public-reference/next.config.js
shared/ui-components/src/page_components/listing/ListingMap.tsx

Import mapbox css and add css loader

---

apps/public-reference/package.json
services/listings/package.json
shared/core/package.json
shared/ui-components/package.json
shared/ui-components/src/page_components/UnitTables.tsx
shared/ui-components/src/page_components/listing/listing_sidebar/__snapshots__/ApplicationSection.stories.storyshot
shared/ui-components/src/tables/BasicTable.tsx
shared/ui-components/src/tables/GroupedTable.tsx
yarn.lock

Upgrade nanoid

---

package.json
shared/ui-components/src/cards/ImageCard.scss
yarn.lock

Fixes image width then image is too small.

Fix image width

---

shared/core/src/listings.ts

Adds missing buildingSelectionCriteria field to Listing

Add buildingSelectionCriteria field to Listing

---

apps/public-reference/next.config.js
apps/public-reference/pages/_app.jsx
apps/public-reference/src/customScripts.ts
shared/ui-components/src/page_components/listing/listing_sidebar/__snapshots__/ApplicationSection.stories.storyshot

Closes #174 
Out of the box nothing will happen on any new builds currently, but if the GTM_KEY env var is set, then it inserts the head script and body noscript tag. It's also flexible enough to accommodate any other sort of scripts which might be needed in future app variants.

Insert GTM tags into page

---

apps/public-reference/package.json
apps/public-reference/pages/listing.tsx
package.json
services/listings/package.json
shared/core/package.json
shared/ui-components/index.ts
shared/ui-components/package.json
shared/ui-components/src/atoms/ExpandableText.scss
shared/ui-components/src/atoms/ExpandableText.stories.tsx
shared/ui-components/src/atoms/ExpandableText.tsx
shared/ui-components/src/atoms/__snapshots__/ExpandableText.stories.storyshot
shared/ui-components/src/locales/general.json

Add ExpandableText component

---

.gitignore

As the title says - we don't need individual IDE configs in the repo.

Added .idea (WebStorm config) to gitignore

---

apps/public-reference/netlify.toml

Fix production env key in netlify.toml

---

shared/ui-components/src/page_components/listing/ListingMap.tsx
shared/ui-components/src/page_components/listing/__snapshots__/ListingMap.stories.storyshot

A necessary upstream change to fix Alameda listing

Zoom in Mapbox component so streets are visible

---

apps/public-reference/next.config.js
apps/public-reference/package.json
yarn.lock

I don't think we'll use this all that often, but I did the work so I figure we might as well have the tool there. Note that it's behind an environment variable to run this, so it shouldn't affect the normal build process.

Add the nextjs bundle analyzer

---

shared/ui-components/styles/custom_counter.scss

@jaredcwhite Fixing this again after I think it got overwritten in a previous rebase.

Fixing Custom Counter Spacing

---

backend/core/package.json
backend/core/src/listings/listings.controller.spec.ts
backend/core/src/listings/listings.service.spec.ts
backend/core/test/factories/index.ts
backend/core/test/factories/listing.ts
backend/core/test/factories/unit.ts
yarn.lock

A test PR to see if typescript factories are for us. Factories are make with Fishery: https://thoughtbot.com/blog/announcing-fishery-a-javascript-and-typescript-factory-library
Library is based on most popular factory solution for Rails. 
As I was working on that I took a look at out field types and made comments in places we should address them, eg. string fields that should be numeric or fields that could be nullable (@pbn4 a kickstart for our Monday task)

Add js factories with fishery

---

apps/public-reference/pages/listing.tsx
backend/core/src/entity/Listing.ts
shared/core/src/listings.ts
shared/ui-components/src/atoms/ApplicationStatus.scss
shared/ui-components/src/atoms/ApplicationStatus.tsx
shared/ui-components/src/atoms/__snapshots__/ApplicationStatus.stories.storyshot
shared/ui-components/src/page_components/listing/listing_sidebar/WhatToExpect.tsx

More changes required for upcoming listings. 
Note: would be good to run sth like `yarn typeorm migration:generate -n AddWhatToExpectToListing` but typeorm doesnt recognise snake case for me.

Add required changes for latest listings

---

apps/public-reference/layouts/forms.tsx
apps/public-reference/lib/AppSubmissionContext.ts
apps/public-reference/pages/applications/contact/address.tsx
apps/public-reference/pages/applications/contact/name.tsx
apps/public-reference/pages/applications/start/choose-language.tsx
shared/ui-components/src/cards/FormCard.scss
shared/ui-components/src/cards/FormCard.tsx
shared/ui-components/src/forms/Field.tsx
shared/ui-components/src/locales/general.json
shared/ui-components/src/prototypes/AppHeader.scss
shared/ui-components/styles/forms.scss

Closes #255 
Review: https://5ef139faa1603f01999581ae--clever-edison-cd22c1.netlify.app/applications/start/choose-language
(skip to next page)

1.2 Name form

---

shared/core/src/listings.ts
shared/ui-components/src/authentication/api_requests.ts
shared/ui-components/src/page_components/listing/AdditionalFees.tsx
shared/ui-components/src/page_components/listing/listing_sidebar/Apply.tsx
tsconfig.json

...in order to get Paper pickup information to render properly.

Fix upstream pieces missing from HBA PR#76

---

apps/public-reference/cypress/integration/pages/ApplicationForms.ts
apps/public-reference/layouts/forms.tsx
apps/public-reference/pages/applications/contact/address.tsx
apps/public-reference/pages/applications/contact/name.tsx
apps/public-reference/pages/applications/start/choose-language.tsx
apps/public-reference/pages/create-account.tsx
apps/public-reference/pages/sign-in.tsx
shared/ui-components/src/atoms/LinkButton.tsx
shared/ui-components/src/cards/FormCard.scss
shared/ui-components/src/locales/general.json

Closes #277 
Preview: https://5efcf708158fb2f82badb20f--clever-edison-cd22c1.netlify.app/applications/start/choose-language

Finish layout of the starting Choose Language step

---

apps/public-reference/lib/AppSubmissionContext.ts
apps/public-reference/pages/applications/household/ada.tsx
shared/ui-components/src/locales/general.json

Closes #266 
RA:
~~https://5f03b51cc7522c06e150a38a--clever-edison-cd22c1.netlify.app/applications/start/choose-language~~ (sorry you have to go through a bunch of steps first…)
https://5f051d2b7d92cb02e26de02a--clever-edison-cd22c1.netlify.app/applications/start/choose-language

Add the ADA features form step

---

apps/public-reference/pages/applications/start/choose-language.tsx

Change Choose Your Language header to display block

---

apps/public-reference/pages/applications/contact/alternate-contact-contact.tsx
apps/public-reference/pages/applications/contact/alternate-contact-name.tsx
apps/public-reference/pages/applications/contact/alternate-contact-type.tsx

Closes https://github.com/bloom-housing/bloom/issues/420

Fix empty arrow functions ESLint complaint

---

shared/ui-components/src/helpers/tableSummaries.tsx
shared/ui-components/src/locales/general.json

Pull housingbay changes

---

apps/partners-reference/package.json
apps/public-reference/package.json
apps/public-reference/pages/applications/contact/address.tsx
apps/public-reference/pages/applications/household/ada.tsx
yarn.lock

Upgrade to React Hook Form 6.0+

---

shared/ui-components/package.json
shared/ui-components/src/cards/InfoCard.tsx
shared/ui-components/src/cards/InfoCardGrid.stories.tsx
shared/ui-components/src/cards/__snapshots__/InfoCardGrid.stories.storyshot
shared/ui-components/styles/markdown.scss
yarn.lock

Fixes #401 
There's a second InfoCardGrid story variant showing the Markdown formatting.

Add Markdown option to InfoCard

---

apps/public-reference/lib/AppSubmissionContext.ts
apps/public-reference/pages/applications/contact/address.tsx
shared/ui-components/src/helpers/formOptions.tsx
shared/ui-components/src/locales/general.json

Add prefered contact

---

apps/public-reference/pages/applications/start/choose-language.tsx
apps/public-reference/pages/applications/start/what-to-expect.tsx
shared/ui-components/src/locales/general.json

Add what to expect page to application process

---

backend/core/tsconfig.build.json

Closes https://github.com/bloom-housing/bloom/issues/447

Ignore generate-axios-client.ts during builds

---

README.md

SFDS ticket: [#174026532](https://www.pivotaltracker.com/n/projects/1405352/stories/174026532)
While setting up the [bloom-sf repo](https://github.com/SFDigitalServices/bloom) during our hackathon we found a few extra steps were necessary to get an app up and running. This change just documents those steps.

Update readme with steps for creating an app

---

shared/ui-components/src/locales/general.json

Just adding the word "other". 
See https://github.com/housingbayarea/bloom/pull/104 for context.

Tweak preference remaining units text

---

apps/public-reference/pages/applications/household/preferred-units.tsx
shared/ui-components/src/forms/CheckboxGroup.tsx
shared/ui-components/src/forms/HouseholdMemberForm.tsx

Just a couple of minor build issues that snuck through in the last couple PRs.
@dominikx96 - Let me know if you think groupNote should be mandatory, but it looks like you already do a null check when you're rendering it, so I'm assuming this is what you intended.

Make groupNote optional for CheckboxGroup + lint fixes

---

apps/public-reference/pages/applications/financial/vouchers.tsx
apps/public-reference/pages/applications/household/ada.tsx
apps/public-reference/pages/applications/household/preferred-units.tsx
apps/public-reference/pages/applications/review/summary.tsx
shared/ui-components/src/locales/general.json

Add Preferences to the Review summary

---

apps/public-reference/layouts/application.tsx
apps/public-reference/pages/applications/household/preferred-units.tsx
apps/public-reference/pages/applications/review/confirmation.tsx
apps/public-reference/pages/applications/review/demographics.tsx
apps/public-reference/pages/applications/review/summary.tsx
apps/public-reference/pages/applications/review/terms.tsx
apps/public-reference/pages/create-account.tsx
apps/public-reference/pages/sign-in.tsx
shared/ui-components/src/atoms/Button.scss
shared/ui-components/src/cards/FormCard.scss
shared/ui-components/src/forms/Field.tsx
shared/ui-components/styles/forms.scss
shared/ui-components/styles/index.scss

- Sticky footer
- Form card lead spacing
- Removing un-needed back buttons
- Date year field
- Error states for radios and checkboxes
- Adding label class to field component (I know this goes against best practice and open to suggestions)

Various style updates including sticky footer

---

apps/public-reference/pages/applications/household/add-members.tsx

Fix adding a new household member

---

apps/public-reference/pages/applications/financial/income.tsx

Enable the conditional income validation

---

apps/public-reference/page_content/homepage.mdx
apps/public-reference/pages/index.tsx
shared/ui-components/src/locales/general.json

Relocate the copy on the homepage

---

shared/ui-components/src/cards/ImageCard.scss
shared/ui-components/src/cards/ImageCard.stories.tsx
shared/ui-components/src/cards/ImageCard.tsx
shared/ui-components/src/cards/__snapshots__/ImageCard.stories.storyshot
shared/ui-components/src/page_components/listing/ListingsList.tsx

Issue: #568 
I also added state (it's visible on sample screenshot, but not in the description - let me know if the state should not be in the address line).

Added missing address to listing element & updated story

---

apps/public-reference/layouts/application.tsx
shared/ui-components/src/locales/general.json

Moved copyright to the translation string

---

apps/public-reference/pages/applications/contact/name.tsx

Added validation for email

---

backend/core/ormconfig.ts
backend/core/src/main.ts

Closes https://github.com/bloom-housing/bloom/issues/340

Add warning when pending migrations are detected

---

apps/public-reference/pages/listing.tsx
shared/ui-components/src/headers/SiteHeader/SiteHeader.tsx
shared/ui-components/src/locales/general.json

Moved hardcoded strings to translations

---

apps/public-reference/pages/applications/review/confirmation.tsx
apps/public-reference/pages/applications/view.tsx

Fixes #563 
There were actually a couple of places needing updated links.

Add listing link to the application confirmation page

---

apps/public-reference/pages/applications/household/preferred-units.tsx
apps/public-reference/pages/applications/review/demographics.tsx

Hidden "save & finish later" button

---

apps/public-reference/page_content/applications/complete.mdx
apps/public-reference/page_content/applications/new.mdx
apps/public-reference/page_content/applications/step2.mdx

Just removes some old code that doesn't seem to be used anywhere.
Fixes #610.

remove old placeholders from page_content/applications

---

shared/ui-components/__tests__/authentication/RequireLogin.test.tsx
shared/ui-components/src/page_components/__snapshots__/DashBlocks.stories.storyshot
shared/ui-components/src/page_components/listing/__snapshots__/ListingMap.stories.storyshot
shared/ui-components/src/page_components/listing/listing_sidebar/__snapshots__/ApplicationSection.stories.storyshot

- fix RequireLogin test to send a now-required signInMessage
- update storyshots for ApplicationMethods schema changes

Resolve test failures in ui-components

---

apps/public-reference/pages/applications/review/confirmation.tsx
apps/public-reference/pages/applications/start/choose-language.tsx
apps/public-reference/pages/listing.tsx
shared/ui-components/src/page_components/listing/ListingsList.tsx

Use assets for obtaining the listing image URL

---

apps/public-reference/pages/listing.tsx

Render program rules and required documents with Markdown

---

backend/core/src/listings/listings.service.ts

Order unit types in tables

---

apps/public-reference/lib/AppSubmissionContext.ts
apps/public-reference/pages/applications/review/confirmation.tsx
apps/public-reference/pages/applications/review/terms.tsx
apps/public-reference/pages/applications/view.tsx

Added real confirmation ID from BE

---

backend/core/src/entity/user.entity.ts
backend/core/src/migration/1600106585058-add-unique-email-constraint.ts

Fix email uniqueness for User entity

---

apps/public-reference/src/forms/applications/FormSummaryDetails.tsx

Don’t display blank alternate contact address

---

backend/core/client.ts
backend/core/seeds.json
backend/core/src/entity/preference.entity.ts
backend/core/src/listings/listings.service.ts
backend/core/src/migration/1600891752631-change-ordinal-type.ts
services/listings/listings/gish.json
shared/core/src/backend-swagger.ts
shared/core/src/preferences.ts
shared/ui-components/src/helpers/translator.tsx
shared/ui-components/src/lists/PreferencesList.tsx
shared/ui-components/src/lists/__snapshots__/PreferencesList.stories.storyshot

Order preferences by ordinal

---

apps/public-reference/pages/listing.tsx

Hide section when requiredDocuments or programRules were not passed

---

backend/core/src/lib/unit_transformations.ts

Fix for https://github.com/housingbayarea/bloom/issues/160

Fix min max function

---

apps/public-reference/pages/listings.tsx
shared/ui-components/src/cards/ImageCard.scss
shared/ui-components/styles/mixins.scss

- Adding container to fix collapsing listing rows with no image present
- Adding background color and aspect ratio to fill image container to prevent collapsing image container

Fix listing rows

---

apps/public-reference/layouts/application.tsx
apps/public-reference/pages/applications/review/confirmation.tsx
apps/public-reference/pages/applications/start/choose-language.tsx

Partially reverts #606 so that we can start testing and expanding the login flow.

Begin to re-enable login flow for public-reference

---

shared/ui-components/styles/text.scss

@jaredcwhite Removing remaining block style

Removing block style from info item

---

shared/ui-components/src/locales/general_cleanup.json

We'll have to do a diff with the current file and update the entire app/components which is a Big Deal, so this can live in the repo separately at first.

Add separate cleanup locale JSON for future integration

---

shared/core/package.json
shared/ui-components/src/prototypes/Drawer.tsx
shared/ui-components/src/prototypes/GridItem.tsx
shared/ui-components/src/prototypes/Tag.tsx
shared/ui-components/src/prototypes/__snapshots__/Drawer.stories.storyshot
shared/ui-components/src/prototypes/__snapshots__/FieldSection.stories.storyshot
shared/ui-components/src/prototypes/__snapshots__/GridItem.stories.storyshot
shared/ui-components/src/prototypes/__snapshots__/StatusBar.stories.storyshot
shared/ui-components/src/prototypes/__snapshots__/SummaryCard.stories.storyshot
shared/ui-components/src/prototypes/__snapshots__/TabNav.stories.storyshot
shared/ui-components/src/prototypes/__snapshots__/Tag.stories.storyshot
shared/ui-components/src/prototypes/__snapshots__/ViewItem.stories.storyshot
shared/ui-components/src/prototypes/__snapshots__/ViewSection.stories.storyshot

- Add an explicit `axios` dependency to shared/core for the monorepo build pack to be able to resolve
- fix some linter issues
- update storyshots from a previous PR to ui-components/prototypes

Minor fixes for the legacy listings service and test failures

---

backend/core/src/services/application-formatting-metadata.ts
backend/core/src/services/csv-builder.service.ts

Fixes a 500 on CSV applications endpoint when application is a malformed JSON

Fix undefined join on string[] in csv builder

---

shared/ui-components/src/page_components/listing/AdditionalFees.tsx

Resolves spacing issue for Logan listing.

Add spacing for deposit range

---

apps/public-reference/lib/AppSubmissionContext.ts
apps/public-reference/pages/applications/review/demographics.tsx
backend/core/src/entity/application.entity.ts

Issue: #767 
Added missing field & updated backend type for this for the future.

Added race field to context

---

shared/ui-components/src/sections/__snapshots__/GridSection.stories.storyshot

add missing storyshot for GridSection

---

apps/public-reference/pages/listing.tsx

Resolves #765 
NOTE:
As this change sits on to of public-reference it will need to be updated on every regional sub project.

Hide preference section for no preferences

---

apps/public-reference/layouts/application.tsx
apps/public-reference/pages/account/dashboard.tsx
apps/public-reference/pages/sign-in.tsx
shared/ui-components/src/locales/general.json

Issue: #725 
@slowbot do we still want a green full-width alert "Welcome back, %{name}!" (currently on the homepage after sign in) in the dashboard? If yes - probably we have to increase the dashboard top margin.

Added logout alert & redirected user to dashboard after login

---

shared/ui-components/src/page_components/listing/listing_sidebar/SidebarAddress.tsx
shared/ui-components/src/page_components/listing/listing_sidebar/__snapshots__/ApplicationSection.stories.storyshot
shared/ui-components/src/page_components/listing/listing_sidebar/__snapshots__/Apply.stories.storyshot

Use Markdown for the Office Hours sidebar

---

apps/public-reference/pages/account/applications.tsx
shared/ui-components/index.ts
shared/ui-components/package.json
shared/ui-components/src/authentication/timeout.tsx
shared/ui-components/src/global/mixins.scss
shared/ui-components/src/overlays/Drawer.scss
shared/ui-components/src/overlays/Drawer.stories.tsx
shared/ui-components/src/overlays/Drawer.tsx
shared/ui-components/src/overlays/Modal.scss
shared/ui-components/src/overlays/Modal.stories.tsx
shared/ui-components/src/overlays/Modal.tsx
shared/ui-components/src/overlays/Overlay.scss
shared/ui-components/src/overlays/Overlay.tsx
shared/ui-components/src/overlays/__snapshots__/Modal.stories.storyshot
yarn.lock

New overlay and drawer components

---

backend/core/src/entity/application.entity.ts
backend/core/test/applications/applications.e2e-spec.ts
shared/core/src/backend-swagger.ts

Closes https://github.com/bloom-housing/bloom/issues/845

Improve incomePeriod typing

---

shared/ui-components/src/overlays/Drawer.stories.tsx
shared/ui-components/src/overlays/Overlay.tsx

Fixes #859 (check out the first Model or Drawer story and scroll up/down to verify)

Fix scrolling issue with Overlay

---

package.json

Wrong configuration got into master by mistake (mine). Whoops!

Fix incorrect lint-staged config

---

shared/ui-components/.storybook/main.js
shared/ui-components/package.json
shared/ui-components/src/actions/Button.stories.tsx
shared/ui-components/src/actions/__snapshots__/Button.stories.storyshot
yarn.lock

Add Storybook Knobs

---

shared/ui-components/src/notifications/StatusMessage.tsx
shared/ui-components/src/notifications/StatusMessages.scss
shared/ui-components/src/notifications/StatusMessages.stories.tsx
shared/ui-components/src/notifications/__snapshots__/StatusMessages.stories.storyshot

Closes #692 
@slowbot I wasn't quite sure how to express the difference between a container with one or more message children, and an "empty" container that shows just the the Last Updated date instead. I tried to come up with something that seems reasonable. Let me know what you think :)

Status Messages component

---

.circleci/config.yml
apps/partners-reference/next.config.js
apps/partners-reference/package.json
apps/public-reference/cypress/integration/navigation.ts
apps/public-reference/cypress/integration/pages/application/financial/income.spec.ts
apps/public-reference/cypress/support/helpers.ts
apps/public-reference/package.json
package.json

Enable cypress for circle ci

---

apps/partners-reference/next.config.js
apps/partners-reference/pages/listings.tsx

Fixed listing data path after backend changes. Currently unable to fetch listings data and partners app doesn't work.

Fixed path for listings data

---

apps/partners-reference/netlify.toml
apps/public-reference/netlify.toml

Changed backend URLs to use the new backend instance in the Netlify config - to fix deploy.

Updated netlify env to use the new backend

---

apps/public-reference/next.config.js
apps/public-reference/pages/_app.jsx
shared/ui-components/src/helpers/useLanguageChange.ts
shared/ui-components/src/locales/general.json
shared/ui-components/src/locales/vi.json
shared/ui-components/src/locales/zh.json

Finish adding in all the translation options to the top nav.

Additional translation options

---

apps/partners-reference/src/applications/ApplicationForm.tsx
shared/ui-components/index.ts
shared/ui-components/src/locales/general.json
shared/ui-components/src/notifications/StatusAside.scss
shared/ui-components/src/notifications/StatusAside.stories.tsx
shared/ui-components/src/notifications/StatusAside.tsx
shared/ui-components/src/notifications/StatusMessage.tsx
shared/ui-components/src/notifications/__snapshots__/StatusAside.stories.storyshot
shared/ui-components/src/notifications/__snapshots__/StatusMessages.stories.storyshot

Close #696
@dominikx96 I added the new component to the sidebar, let me know what you think. We'll probably need to adjust for adding vs. editing.
@slowbot Right now this is a single column, but it supports two-column button placements as well for more advanced layouts.

Add StatusAside component and place on the New/Edit Application form

---

backend/core/client.ts
backend/core/src/applications/applications.service.ts
backend/core/src/applications/dto/application.dto.ts
backend/core/src/applications/entities/application.entity.ts
backend/core/src/migration/1610361232572-add-deleted-at-to-application.ts
shared/core/src/backend-swagger.ts

Closes https://github.com/bloom-housing/bloom/issues/936

Add soft delete to application entity

---

backend/core/src/listings/listings.service.ts

It's not caputed by any issue, removes a bug causing PUT /listings to throw 500 internal server error when trying to modify a listing through the API.

Fix PUT /listings

---

backend/core/package.json
backend/core/src/applications/applications.service.ts
backend/core/src/applications/dto/application.dto.ts
backend/core/types/src/backend-swagger.ts
sites/public/pages/account/applications.tsx
ui-components/src/blocks/AppStatusItem.tsx
yarn.lock

It's not captured by any issue, but this is somewhat a bug that some of the frontend code was retrieving listing properties through application object. Doing that introduces repeating listing in data for each retrieved application.  I decided to remove that problem early.

Applications service refactor (remove listing join) 

---

sites/partners/layouts/application.tsx

Sign Out Button

---

sites/partners/src/applications/applicationsColDefs.ts
sites/public/pages/applications/household/member.tsx
ui-components/index.ts
ui-components/src/helpers/formatYesNoLabel.ts

Closes: #860
@slowbot I'm not sure about Residence and Work Address (primary applicant, not HH member) - Is this information should be visible?
Also added n/a inside HH columns if the information is not set. Do we want to apply this for primary applicant columns as well?

Household Columns Update

---

ui-components/src/blocks/FormCard.tsx
ui-components/src/blocks/InfoCard.tsx
ui-components/src/footers/SiteFooter.tsx
ui-components/src/headers/Hero.tsx
ui-components/src/notifications/ErrorMessage.tsx
ui-components/src/page_components/listing/UnitTables.tsx
ui-components/src/sections/ContentSection.tsx
ui-components/src/sections/InfoCardGrid.tsx
ui-components/src/sections/ListSection.tsx
ui-components/src/sections/MarkdownSection.tsx

Change JSX.Element to React.ReactNode

---

sites/public/lib/AppSubmissionContext.ts
sites/public/lib/ApplicationConductor.ts
sites/public/pages/applications/household/add-members.tsx
sites/public/pages/applications/household/member.tsx
sites/public/pages/applications/household/members-info.tsx
sites/public/pages/applications/review/terms.tsx
sites/public/pages/applications/start/choose-language.tsx
sites/public/pages/listing.tsx
sites/public/src/forms/applications/ApplicationTimeout.ts
sites/public/src/forms/applications/FormSummaryDetails.tsx
ui-components/src/helpers/localeRoute.tsx
ui-components/src/locales/general.json
ui-components/src/page_components/listing/listing_sidebar/Apply.tsx

Fixes #932, #933
@kathyccheng We apparently didn't have a word meaning "Begin" for Vietnamese. I chose "Bắt đầu" from the online translator but we'll want that QA'd.

Translations working now for Application forms

---

backend/core/src/applications/entities/alternate-contact.entity.ts
backend/core/src/applications/entities/applicant.entity.ts

Disabled backend email validation.
I think we should use null for empty, not required fields, what do you think @pbn4 ?

Temporary disable email validators

---

ui-components/src/locales/es.json
ui-components/src/locales/vi.json
ui-components/src/locales/zh.json
ui-components/src/page_components/listing/listing_sidebar/Apply.tsx

Additional round of translation fixes

---

backend/core/listings-importer.ts
ui-components/src/blocks/InfoCard.scss
ui-components/src/global/navbar.scss
ui-components/src/headers/Hero.scss
ui-components/src/headers/Hero.tsx
ui-components/src/headers/SiteHeader.tsx
ui-components/src/headers/__snapshots__/Hero.stories.storyshot
ui-components/src/headers/__snapshots__/SiteHeader.stories.storyshot

Resolves style issues and fixes #998

Fix importer and styles for release

---

backend/core/src/migration/1612777228056-make-ami-chart-items-a-jsonb-column.ts
backend/core/src/migration/1612778538403-make-listing-assets-a-jsonb-column.ts
backend/core/src/migration/1612778951266-make-listing-application-methods-a-jsonb-column.ts
backend/core/src/migration/1612779568745-make-listing-events-a-jsonb-column.ts
sites/public/lib/ApplicationConductor.ts
sites/public/lib/LiveAloneStep.ts

Resolves #999 
**Note:** this also updates recent migrations so the jsonb columns default value is an array: `[]`

Skip Live Alone page when there are already multiple household members

---

sites/public/pages/listing.tsx

Fixes date formatting issue for public lottery and adds option to add multiple open house events.

Fix public lottery and add multiple open houses

---

sites/public/layouts/forms.tsx
ui-components/src/blocks/FormCard.scss
ui-components/src/navigation/ProgressNav.scss

Fixes #1015
Updating mobile font size and container margins
Also added overflow auto to the container in case of longer nav items

Updating mobile app bav styles

---

sites/public/pages/applications/preferences/displaced.tsx
sites/public/pages/applications/preferences/general.tsx

Fixes #1009 
Also fixes I bug I saw where depending on how you selected various preferences, it wouldn't advance the progress nav.

Improve preferences UI functionality

---

ui-components/src/blocks/InfoCard.scss
ui-components/src/global/blocks.scss
ui-components/src/sections/InfoCardGrid.scss
ui-components/src/sections/InfoCardGrid.stories.tsx
ui-components/src/sections/InfoCardGrid.tsx
ui-components/src/sections/__snapshots__/InfoCardGrid.stories.storyshot

Some style updates to fix Markdown presentation for downstream uses.

Improve InfoGard/Grid for use downstream

---

backend/core/src/shared/units-transformations.ts

Addresses https://github.com/bloom-housing/bloom/issues/931

Use translations keys for hmiHeaders

---

backend/core/src/csv/formatting/basic-formatting-metadata.ts
backend/core/src/csv/formatting/format-blocks.ts
backend/core/src/csv/formatting/hayward-formatting-metadata.ts

Closes https://github.com/bloom-housing/bloom/issues/1055

Remove redundant residence zip in CSV exporter

---

sites/partners/lib/hooks.ts
sites/partners/pages/listings/applications/index.tsx
sites/partners/public/images/icons.svg
sites/public/public/images/icons.svg
ui-components/public/images/icons.svg
ui-components/src/actions/Button.scss
ui-components/src/actions/Button.tsx

Added loading state for csv export

---

ui-components/src/locales/general.json

Closes #228 from housingbayarea fork.

Changed translation to Displacee Tenant

---

ui-components/src/blocks/__snapshots__/AppStatusItem.stories.storyshot
ui-components/src/helpers/address.tsx
ui-components/src/notifications/ApplicationStatus.tsx
ui-components/src/notifications/__snapshots__/ApplicationStatus.stories.storyshot
ui-components/src/page_components/listing/__snapshots__/ListingMap.stories.storyshot
ui-components/src/page_components/listing/listing_sidebar/Apply.tsx
ui-components/src/page_components/listing/listing_sidebar/__snapshots__/ApplicationSection.stories.storyshot
ui-components/src/page_components/listing/listing_sidebar/events/PublicLotteryEvent.tsx

Changes for https://github.com/housingbayarea/bloom/issues/243

Fixes to date format, allow markup for street, add lottery time

---

sites/partners/src/applications/ApplicationsColDefs.ts

Fixed annual and monthly income values in the applications table

---

sites/partners/pages/listings/applications/index.tsx
sites/partners/pages/listings/flags/index.tsx
sites/partners/src/listings/ListingSecondaryNav.tsx
ui-components/src/headers/PageHeader.scss
ui-components/src/headers/PageHeader.tsx
ui-components/src/locales/general.json
ui-components/src/navigation/TabNav.tsx
ui-components/src/text/__snapshots__/Tag.stories.storyshot

Closes: #951
It's highly connected with #777 (this branch includes necessary routes).
@netrabadami few things that I noticed during development:
- Your branch is not up to date with the master and you need to resolve conflicts.
- I had to use --no-verify flag to push changes because there are a lot of linter/type issues. You need to focus on this element and maybe check your IDE settings? Happy to support you with this element, just let me know on Slack :)
In the PR scope is tab navigation only. We need to connect flags number with Tag in the "Flags" tab when we'll have the final version of data in the frontend. Currently, it's just hardcoded 0. I added _TODO_ notes in these places.

Added flags navigation

---

sites/partners/lib/hooks.ts
sites/partners/pages/listings/applications/index.tsx

Closes: #1095
- Moved export POST logic directly to the component
- Added site alert with generic error

Added csv export error message

---

backend/core/src/applications/applications.service.ts

Add missing address and workAddress as joins to application householdMembers
resolves: #1105

Add missing address and workAddress

---

backend/core/src/csv/csv-encoder.service.ts

Closes https://github.com/bloom-housing/bloom/issues/1094

Add exception handling in _encodeDoubleQuotes

---

backend/core/src/shared/units-transformations.ts
sites/public/pages/listing.tsx
ui-components/src/tables/StandardTable.tsx

Use translated strings on responsive table headers

---

backend/core/src/application-flagged-sets/application-flagged-sets.controller.ts
backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
backend/core/src/application-flagged-sets/dto/application-flagged-set.dto.ts
backend/core/src/applications/applications.controller.ts
backend/core/src/applications/applications.service.ts
backend/core/src/applications/dto/application.dto.ts
backend/core/test/afs/afs.e2e-spec.ts
backend/core/types/src/backend-swagger.ts

Closes https://github.com/bloom-housing/bloom/issues/918 and addressed https://github.com/bloom-housing/bloom/issues/903 (get by id endpoint)

Add get AFS by id and pagination meta for totalFlagged

---

backend/core/src/listings/entities/listing.entity.ts
backend/core/src/migration/1619558199145-add-missing-listing-fields.ts
backend/core/src/property/entities/property.entity.ts
backend/core/src/seeds/listings.ts
backend/core/types/src/backend-swagger.ts
sites/public/pages/listing.tsx
ui-components/src/locales/general.json

Add missing listing fields

---

ui-components/src/locales/es.json
ui-components/src/locales/vi.json
ui-components/src/locales/zh.json

chore: new autofill translations

---

sites/public/pages/listing.tsx

Adds the same referral application logic to the mobile view (if no application methods, show the referral component)

fix: referral application section on mobile

---

docs/pull_request_template.md

Here's a pull request template for us to iterate on. We may want more or less items depending on the team's preferences and we may want separate templates for front and backend changes, if they're typically separate, but it's easy enough for a dev to remove the list items that aren't relevant on PR creation.

pull_request_template proposal

---

sites/public/pages/account/edit.tsx

Fixes the issue in #1200 
Here is a screenshot from the account settings page after creating an account with a birthdate of 01/01/1999

fix: birthdate localizing issues

---

backend/core/Procfile
backend/core/package.json

Addresses # (https://github.com/bloom-housing/bloom/issues/1232)
I decided to move migrations into postbuild hook to decrease startup time of a container. 
Deploy new changes to backend and see container correctly start up.

Moves running migration from a start script to build pipeline

---

ui-components/__tests__/text/Tag.test.tsx
ui-components/src/global/AppearanceTypes.ts
ui-components/src/text/Tag.scss
ui-components/src/text/Tag.stories.tsx
ui-components/src/text/Tag.tsx

Addresses #1159 
New styles need to be supported in the Tag for listings management, view the [Figma](https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2789%3A0) for more details
I copied existing patterns, but the way the styling is done feels kinda weird (add an appearance type, to add a class, to then toggle another class on that class). 
Look at the Tag story in Storybook. Here is a screenshot of one of the new stories:

feature: new styles for tag component

---

docs/pull_request_template.md

updates pull request template

---

CHANGELOG.md

@seanmalbert Let me know if you think this provides enough context. cc @pbn4

Add information about Next 10 upgrade to Changelog

---

CHANGELOG.md
sites/public/pages/applications/start/choose-language.tsx

It's a quick fix for https://github.com/bloom-housing/bloom/pull/1234
On the first render, router params are not available. The solution is to wait for the router by using `router.isReady`.
More info: https://stackoverflow.com/questions/61040790/userouter-withrouter-receive-undefined-on-query-in-first-render

Wait for checking listingId until router is ready

---

sites/partners/netlify.toml
sites/public/netlify.toml

This updates `netlify.toml` with a command that ensures Netlify will always rebuild the site even if there are no repo changes.
See if a push or rebuild trigger (without emptying build cache) will still do a Next rebuild.

Ensure Netlify builds always do a full rebuild and deploy

---

ui-components/src/notifications/AlertBox.scss
ui-components/src/notifications/AlertBox.stories.tsx
ui-components/src/notifications/AlertBox.tsx

Addresses #1252
Add ability to AlertBox to correctly display on full width of the screen.
I've added a StoryBook case for the full width option for AlertBox

Alert improvements

---

CHANGELOG.md
backend/core/src/csv/formatting/formatters.ts
backend/core/src/csv/formatting/metadata/oha-formatting-metadata.ts

Addresses # (https://github.com/bloom-housing/bloom/issues/1275)
This change adds HOPWA preference to `ohaFormat` in CSV exporter.
Go to partners portal partners.housingbayarea.bloom.exygy.dev and export CSV for coliseum.

Add hopwa preference

---

CHANGELOG.md
sites/partners/lib/hooks.ts

It's not covered by any issue.
As @kathyccheng noticed - searching by id or name doesn't affect the results. It was because the `search` param wasn't assigned correctly. I fixed it, so users can search by name, but not by application id - I think it still needs backend improvements.
Open partners listing applications and use search to find applications by first or last name.

Fixed search param

---

ui-components/__tests__/forms/Textarea.test.tsx
ui-components/src/forms/Textarea.scss
ui-components/src/forms/Textarea.stories.tsx
ui-components/src/forms/Textarea.tsx
ui-components/src/locales/general.json

Addresses #1156
New textarea component for listings management. Here is a link to the [Figma](https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2717%3A158654).
Check out the new stories in Storybook.

feature: text area component

---

CHANGELOG.md
backend/core/src/user/dto/user.dto.ts
backend/core/src/user/user.controller.ts
backend/core/test/user/user.e2e-spec.ts
backend/core/types/src/backend-swagger.ts

Addresses # (#1300 )
This change is modifying a response from POST /users. Now the response includes UserBasicDto (identifier and some basic information) which makes is useful for e.g. programatically creating leasing agent accounts. 

Return UserBasicDto from POST /users

---

yarn.lock

Fix yarn.lock being out of sync with package.json

---

ui-components/src/headers/Hero.scss
ui-components/src/headers/Hero.stories.tsx
ui-components/src/headers/Hero.tsx

Addresses #1314 
Fixes an issue where having a secondary button wasn't symmetric in the Hero component, and another issue where mobile responsiveness wasn't quite right. Open to any and all feedback since this is my first contribution, also open to any sort of design feedback. 
- [?] My code follows the style guidelines of this project

Update hero button styles #1314

---

CHANGELOG.md
backend/core/src/migration/1623279600284-listing-status-enum-closed.ts
sites/partners/pages/listings/[id]/index.tsx
sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalDetails.tsx
sites/partners/src/listings/PaperListingForm/index.tsx
sites/partners/src/listings/PaperListingForm/sections/AdditionalDetails.tsx
ui-components/index.ts
ui-components/src/forms/Textarea.tsx
ui-components/src/global/forms.scss
ui-components/src/locales/general.json

Addresses #1321
Adds the additional details section to listing management prototype
Visit listings/add in partners and check out the new section

1321/listings management, additional details section

---

CHANGELOG.md

Add change log for `toPrecision` fix.

Add changelog for toPrecision fix

---

CHANGELOG.md

Just checkout the diff, looks like we missed a merge conflict at some point

fix merge conflicts in master

---

backend/core/README.md
backend/core/package.json

No Issue
Adds a package.json command for starting the backend server in debug mode

Adds debug instructions to backend/core readme (#15)

---

CHANGELOG.md
backend/proxy/Dockerfile
backend/proxy/README.md
backend/proxy/default.conf

Addresses # (1368)
This PR adds files necessary for proxy Docker image build and deployment  [heroku app](https://dashboard.heroku.com/apps/bloom-reference-backend-proxy). 
NOTE: Heroku handles ingress with AWS Elastic Loadbalancer and performs SSL termination, so this proxy is listening on HTTP protocol and encrypts payload second time when forwarding traffic to target AWS ELB in particular v1 or v2 app.
TODO: Once this is deployed in for e.g. core staging it should be the default DNS target for listings-next.bloom.exygy.dev (instead of actual v1 backend) and BACKEND_V1_HOSTNAME env variable should point herokudns.com DNS target assigned to v1 app out of the box (so in other words domain configured for v1 should be changed to point to the proxy app now). A minimal downtime is required to …

Add backend/proxy Dockerfile, README.md and nginx config file

---

CHANGELOG.md
backend/core/src/app.module.ts
backend/core/src/auth/authz_policy.csv
backend/core/src/jurisdictions/dto/jurisdiction.dto.ts
backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
backend/core/src/jurisdictions/jurisdictions.controller.ts
backend/core/src/jurisdictions/jurisdictions.module.ts
backend/core/src/jurisdictions/jurisdictions.service.ts
backend/core/src/listings/dto/listing.dto.ts
backend/core/src/listings/entities/listing.entity.ts
backend/core/src/listings/listings.service.ts
backend/core/src/migration/1624272587523-add-jurisdictions-table.ts
backend/core/test/jurisdictions/jurisdictions.e2e-spec.ts

Addresses # (https://github.com/bloom-housing/bloom/issues/1168)
This change adds `jurisdictions` table to the DB, exposes it over a separate endpoint `/jurisidctions` (admin only) and integrates it into Listing CRUD.

Add /jurisdictions endpoint

---

CHANGELOG.md
backend/core/archer.ts
backend/core/package.json
backend/core/src/app.module.ts
backend/core/src/auth/authz_policy.csv
backend/core/src/jurisdictions/dto/jurisdiction.dto.ts
backend/core/src/listings/dto/listing.dto.ts
backend/core/src/listings/entities/listing.entity.ts
backend/core/src/listings/listings.service.ts
backend/core/src/migration/1624359766509-add-reserved-community-types-table.ts
backend/core/src/reserved-community-type/dto/reserved-community-type.dto.ts
backend/core/src/reserved-community-type/entities/reserved-community-type.entity.ts
backend/core/src/reserved-community-type/reserved-community-types.controller.ts
backend/core/src/reserved-community-type/reserved-community-types.module.ts
backend/core/src/reserved-community-type/reserved-community-types.service.ts
backend/core/test/reserved-community-types/reserved-community-types.e2e-spec.ts
backend/core/types/src/archer-listing.ts
backend/core/types/src/backend-swagger.ts
sites/public/pages/_app.tsx
yarn.lock

Addresses # (https://github.com/bloom-housing/bloom/issues/1171)
This change adds reserved_community_type table and reserved_community_min_age column to listing model.
NOTE: It targets `fix_merge_master` branch which is housingbayarea merge revert fix. 

Add reservedCommunityType endpoint

---

CHANGELOG.md
sites/partners/pages/listings/[id]/index.tsx
sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
sites/partners/src/listings/PaperListingForm/index.tsx
sites/partners/src/listings/PaperListingForm/sections/AdditionalFees.tsx
ui-components/src/locales/es.json
ui-components/src/locales/general.json
ui-components/src/locales/vi.json
ui-components/src/locales/zh.json
ui-components/src/page_components/listing/AdditionalFees.tsx

Addresses #1318 
Adds the additional fees section for listings management. Application fee should auto-populate due to the preset defaults in the prototype. Added changes to the fee section so all the fields can show optionally.
Create a new listing in partners at listings/add
Add the new fees section section, save as draft
Restart the app
Look at the listing you created in public and check the new fields
In partners visit listings/[id-of-listing-you-just-made] and see the detail version of the form as well

1318/additional fees, listings management

---

backend/core/.env.template
backend/core/README.md
backend/core/package.json

No attached issue
Adds two things to help with setting up the test db for end-to-end tests
- Adds uuid extension step to test db initialization
- Adds `TEST_DATABASE_URL` to `env.template` so it's clear how to set the test database url

Adds uuid extension step to e2e tests, and update to .env.template

---

CHANGELOG.md
backend/core/src/migration/1624542123483-seed-reserved-community-type.ts

Addresses # (1171)
This change adds a reserved_communit_type seeds for values already existing in prod DB: `senior` and `specialNeeds`. 

Add reserved_community_type seed migration

---

CHANGELOG.md
sites/partners/pages/listings/[id]/index.tsx
sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx
sites/partners/src/listings/PaperListingForm/index.tsx
sites/partners/src/listings/PaperListingForm/sections/BuildingFeatures.tsx
sites/public/src/ListingView.tsx
ui-components/src/locales/general.json

Addresses #1319
Adds the building features section to listings management MVP.
Add a new listing at listings/add in partners and check it out in that form view and the detail view (will need to restart the stack). The public view is not currently working w the schema changes for testing.

1319/listings management, building features

---

sites/public/pages/listing/[id]/[slug].tsx

set fallback to true for getStaticPaths so new paths can be added

---

CHANGELOG.md
backend/core/src/listings/listings.controller.ts
sites/public/.env.template
sites/public/next.config.js
sites/public/pages/index.tsx
sites/public/pages/listing/[id]/[slug].tsx
sites/public/pages/listings.tsx
sites/public/src/ListingView.tsx

Dev - adds cache revalidation to frontend app

---

backend/core/src/listings/listings.controller.ts

removes listing controller update

---

backend/core/client.ts
backend/core/src/listings/listings.controller.ts
backend/core/src/listings/types/application-method-type-enum.ts
backend/core/types/src/backend-swagger.ts

Application method/paperpickup

---

sites/public/src/ListingView.tsx

removes preview logic from ListingView

---

CHANGELOG.md
backend/core/src/ami-charts/dto/ami-chart.dto.ts
backend/core/src/ami-charts/entities/ami-chart.entity.ts
backend/core/src/application-flagged-sets/entities/application-flagged-set.entity.ts
backend/core/src/applications/entities/application.entity.ts
backend/core/src/auth/dto/user.dto.ts
backend/core/src/auth/entities/user.entity.ts
backend/core/src/listings/dto/listing.dto.ts
backend/core/src/listings/entities/listing.entity.ts
backend/core/src/property/dto/property.dto.ts
backend/core/src/property/entities/property.entity.ts
backend/core/src/reserved-community-type/dto/reserved-community-type.dto.ts
backend/core/src/reserved-community-type/entities/reserved-community-type.entity.ts
backend/core/src/seeds/listings.ts
backend/core/src/units/entities/unit.entity.ts

Addresses # (https://github.com/bloom-housing/bloom/issues/1475)
This change removes unsued OneToMany relations from entities.

Remove unused inverse relations from entities

---

backend/core/archer.ts
backend/core/src/listings/dto/listing.dto.ts
backend/core/types/src/backend-swagger.ts
sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
ui-components/src/notifications/ApplicationStatus.stories.tsx
ui-components/src/notifications/ApplicationStatus.tsx

Make Listing reviewOrderType a getter

---

CHANGELOG.md
backend/core/src/shared/units-transformations.ts

Addresses # (https://github.com/bloom-housing/bloom/issues/1559)
This change fixes unit summaries transformations after a regression coming from separating unitTypes from jsonb column into a table.

Fix unitSummary transformations

---

CHANGELOG.md
ui-components/src/actions/Button.scss
ui-components/src/global/mixins.scss
ui-components/src/global/navbar.scss

Addresses # (#1465 )
Minor visual fixes for button border and navbar border.

Minor visual fixes 1465

---

sites/public/next.config.js

The ENV var was missing in Next's config, so there were broken images for anything saved via Cloudinary.
Go to the public site and then click through to listings that have Cloudinary images attached.

Add Cloudinary cloud ENV var for the public site

---

backend/core/package.json
backend/core/src/shared/types/county-code.ts
backend/core/types/src/backend-swagger.ts

Addresses https://github.com/CityOfDetroit/bloom/issues/49
Add a Detroit county code to the backend. Regenerate the backend-swagger.ts to match and add a convenience Prettier write when generating the client such that you're only comparing the actual diff instead of formatting diffs as well.
There were no UI changes involved here. I built/tested the backend and am checking in the same change to our fork: https://github.com/CityOfDetroit/bloom/pull/351.

Add a Detroit CountyCode.

---

backend/core/src/listings/listings.module.ts
backend/core/src/main.ts
backend/core/src/seed.ts

Force quits redis connection on app close

---

ui-components/src/navigation/ProgressNav.tsx

Ensures screen readers see "dimmed link" for inactive/greyed out progress bar pages.
Turn on screen reader and listen to links for progress bars. Any current step or future steps are read outloud as "dimmed link"

Contribute Feature/Ensure Progress Bar is screen reader friendly

---

CHANGELOG.md
backend/core/src/libs/miscLib/index.ts
backend/core/src/translations/translations.service.ts
ui-components/src/helpers/occupancyFormatting.tsx

testing build issues

---

CHANGELOG.md
sites/public/pages/account/application/[id].tsx

None / ad-hoc
Fixes routing to individual application page.
Submit an application --> my applications --> view application.

fix application routing

---

backend/core/src/csv/formatting/formatters.ts
backend/core/src/csv/formatting/metadata/bha-formatting-metadata.ts

No issue, ad-hoc
A backend change that went directly into `0.3_alameda` that we also need to make here. Formats the bha column to say `claimed` and adds the duplicate columns.
Create an application to the Jordan Court listing and in parters export applications to CSV.

update bha csv columns

---

CHANGELOG.md
ui-components/src/global/lists.scss
ui-components/src/headers/Heading.stories.tsx
ui-components/src/headers/Heading.tsx
ui-components/src/lists/NumberedList.stories.tsx

Addresses #1405 
Adds Heading component and numbered-list styles

Add header and utility classes for DAHLIA

---

.github/workflows/lint.yml
CHANGELOG.md
sites/public/email_templates/email.html

Details in a comment below, but we introduced an issue that was causing the prettier action to fail to run

Fix prettier action

---

ui-components/src/page_components/listing/ListingCard.tsx

Create a prop for styling the LinkButton. This is to match our UX requirements while keeping our ui-components package the same as upstream.
See Detroit's deployment. Or pass in a className to this prop and view the results.

Create a prop for styling the LinkButton in the ListingCard.

---

sites/partners/tailwind.config.js
sites/public/tailwind.config.js

Addresses #1046 & #78
See comment below for the file size savings.
A/B test of dev vs. this PR on various public/partners pages

Purge the CSS output from Tailwind, etc. so only used styles are published

---

yarn.lock

Just remade https://github.com/bloom-housing/bloom/pull/1856 because I think dependabot is branching off of master, will see if I can fix that

chore: bump tmpl package

---

ui-components/src/overlays/Drawer.stories.tsx
ui-components/src/page_components/listing/ListingCard.tsx
ui-components/src/prototypes/FieldSection.stories.tsx
ui-components/src/prototypes/GridItem.stories.tsx
ui-components/src/sections/GridSection.stories.tsx

No issue, I accidentally merged a broken a11y test into dev. The actual a11y fix is in ListingCard (the issue was headers increasing by more than one numeric value). The other changes are stories that were / have been broken by the register prop becoming typed.

test: fix broken a11y test, stories

---

backend/core/src/seeds/listings/listing-coliseum-seed.ts
backend/core/src/seeds/listings/listing-default-seed.ts
backend/core/src/seeds/listings/shared.ts
backend/core/test/unit-accessibility-priority-types/unit-accessibility-priority-types.e2e-spec.ts

No issues, names of priority types changed so updated the seeds so we can re-seed again!

fix: fix dev seeds with new priority types

---

CHANGELOG.md
sites/public/lib/SelectedPreferencesStep.ts
sites/public/lib/hooks.ts
sites/public/pages/applications/preferences/all.tsx
sites/public/pages/applications/review/terms.tsx
sites/public/pages/applications/start/choose-language.tsx
sites/public/pages/listings.tsx
sites/public/pages/preview/listings/[id].tsx

fix: updates from alameda

---

ui-components/package.json

chore: pre-release ui-components

---

CHANGELOG.md
backend/core/src/application-flagged-sets/dto/application-flagged-set-pagination-meta.ts

fix(backend): totalFlagged from AFS missing in swagger documentation

---

.github/workflows/pre-release_components.yml

The GitHub action for auto versioning and pre-releasing ui-components on every push to dev.
Once this is merged it'll start running!

chore: Pre-release GitHub Action

---

.github/workflows/pre-release_components.yml
backend/core/package.json
package.json
shared-helpers/package.json
sites/partners/package.json
sites/public/package.json
ui-components/package.json

Iterating on GitHub action auth

chore: add node auth token

---

ui-components/__tests__/helpers/unitTypes.test.ts
ui-components/src/helpers/unitTypes.ts

https://github.com/bloom-housing/bloom/issues/2021
Adds unit tests around preferred units

fix: adds tests around the unit type work

---

backend/core/src/csv/application-csv-exporter.ts

fix: updates household member count

---

backend/core/src/applications/entities/application.entity.ts
backend/core/src/csv/application-csv-exporter.ts
backend/core/src/migration/1635216780193-new-household-common-app-questions.ts
backend/core/src/seeds/applications.ts
backend/core/test/lib/get-test-app-body.ts
backend/core/types/src/backend-swagger.ts
sites/partners/lib/formatApplicationData.ts
sites/partners/src/applications/PaperApplicationDetails/sections/DetailsHouseholdDetails.tsx
sites/partners/src/applications/PaperApplicationForm/FormTypes.ts
sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
sites/public/cypress/fixtures/applicationConfigBlank.json
sites/public/cypress/fixtures/applicationConfigFilled.json
sites/public/cypress/fixtures/listing.json
sites/public/cypress/fixtures/listingConfig.json
sites/public/cypress/fixtures/routes.json
sites/public/cypress/integration/pages/application/household/expecting-changes.ts
sites/public/cypress/integration/pages/application/household/student.ts
sites/public/lib/AppSubmissionContext.ts
sites/public/lib/ApplicationConductor.ts
sites/public/pages/applications/household/ada.tsx
sites/public/pages/applications/household/changes.tsx
sites/public/pages/applications/household/student.tsx
sites/public/src/forms/applications/FormSummaryDetails.tsx
ui-components/src/helpers/blankApplication.ts
ui-components/src/locales/general.json

This PR addresses #1735 
Two new common app questions, detailed in the issue. There are two new screens after ADA in the Household section - household changes and household student.
Overall adding a question took a lot of setup and we are storing the step order in a lot of places - we should refactor this in the future.
Submit an application. In the household section ensure the new sections are in the changes-->student order and that you can navigate forward and backward. Ensure they are on the summary screen before submission. Then in partners open the application and ensure it looks good on the detail and edit pages. Then export as CSV and ensure the column appears.
- Pull the …

feat: two new common app questions - Household Changes and Household Student

---

sites/public/cypress/integration/pages/application/household/member.spec.ts

fix: household member cypress test

---

sites/partners/layouts/index.tsx
sites/public/layouts/application.tsx
sites/public/layouts/forms.tsx
sites/public/pages/account/applications.tsx
sites/public/pages/account/dashboard.tsx
sites/public/pages/index.tsx
ui-components/src/headers/PageHeader.scss
ui-components/src/headers/SiteHeader.scss
ui-components/src/headers/SiteHeader.stories.tsx
ui-components/src/headers/SiteHeader.tsx
ui-components/src/navigation/LanguageNav.scss

This PR addresses #2067 
Check out the ticket for a screenshot of the existing bugs with the SiteHeader on DAHLIA (they have longer menus, we were not seeing this in Bloom).
Look at the DAHLIA toggle set story under SiteHeader as you move from desktop to mobile
If you have one commit and message, squash. If you need …

fix: SiteHeader visual issues with long menu bars

---

backend/core/src/applications/applications.service.ts
sites/partners/pages/_app.tsx

This PR addresses #2101
Previously if you tried to submit a fresh paper application you'd get an error (but your data was actually saving, visually it did not look like it was). The issue was that we were still trying to send a confirmation email after a paper application submission to the applicant's email and jurisdictional configuration is required for sending the email. But we should never have been sending a confirmation email on paper submission so I removed that and all is good now.
Create a paper application, ensure no error. Submit an application from public w local email key configured to confirm you still get a confirmation email in this case.
- Pull the changes down …

fix: error on creating paper applications

---

backend/core/src/auth/dto/user-filter-params.ts
backend/core/src/auth/dto/user-filter-type-to-field-map.ts
backend/core/src/auth/filters/user-query-filter.ts
backend/core/src/auth/services/user.service.ts
backend/core/src/auth/types/user-filter-keys.ts
backend/core/src/shared/filter/base-query-filter.ts
backend/core/src/shared/filter/index.ts
backend/core/test/user/user.e2e-spec.ts
backend/core/types/src/backend-swagger.ts

fix(backend): make it possible to filter portal users in /users endpoint

---

backend/core/src/app.module.ts
backend/core/src/program/dto/jurisdictionFilterTypeToFieldMap.ts
backend/core/src/program/dto/program-filter-keys.ts
backend/core/src/program/dto/programs-filter-params.ts
backend/core/src/program/dto/programs-list-query-params.ts
backend/core/src/program/programs.controller.ts
backend/core/src/program/programs.service.ts
backend/core/src/seeds/listings/shared.ts
backend/core/types/src/backend-swagger.ts
sites/partners/lib/hooks.ts
sites/partners/pages/listings/[id]/index.tsx
sites/partners/src/listings/PaperListingDetails/sections/DetailPrograms.tsx
sites/partners/src/listings/PaperListingForm/index.tsx
sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
ui-components/src/authentication/AuthContext.ts

This PR addresses #1868
Adds the Programs section to listings management. It's identical to the Preferences section. Also fixes an existing bug with Preferences where if you opened the drawer, deleted an already select preference from the draggable list, then opened the checkboxes, the deleted checkbox would still be checked.
Still waiting to hear from Kathy what the titles of the Programs should be in LM since we are currently showing just the questions, and have no titles. Will update seeds when I get those.
Add, remove, and reorder both preferences and programs. Ensure they appear on the detail page as well.
- Pull the changes down locally and test that the acceptance criteria is …

feat: add Programs section to listings management

---

sites/partners/src/listings/PaperListingForm/UnitForm.tsx

This PR addresses #1974
Updates field type from number to string.
1. Open listings management form and units drawer
2. Put string e.g `2R` into the `unit number` field
3. Save listing
4. Verify if unit number has been saved correctly
If you have one commit and message, squash. If you need each message to be applied, …

feat: Change unit number field type to text

---

backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
backend/core/src/applications/applications.module.ts
backend/core/src/applications/applications.service.ts
backend/core/test/applications/applications.e2e-spec.ts

This PR addresses #2083 
This change optimizes ORM queries and thus overall app performance in application submission flow. 
Before:
```
Percentage of the requests served within a certain time (ms)
50%    494
66%    512
75%    524
80%    529
90%    565
95%    619
98%    986
99%    986
100%    986 (longest request)
```
After: 
```
Percentage of the requests served within a certain time (ms)
50%    360
66%    375
75%    382
80%    388
90%    609
95%    781
98%    859
99%    859
100%    859 (longest request)
```
- Pull the …

feat(backend): improve application flagged set saving efficiency

---

backend/core/src/csv/application-csv-exporter.ts

This PR addresses #2092 
- [ x] This change addresses the issue in full
This updates the label for confirmation code and order the address fields to all be the same (street, street 2, city, state, zip code)
Go to the partners portal and export applications for a listing. You should see all the address fields are ordered the same.
- [x ] My code follows the style guidelines of this project
- Either explicitly ask a clarifying question, request changes, or approve the PR …

fix: updates address order

---

backend/core/src/listings/listings.controller.ts
backend/proxy/default.conf

feat(backend): add nginx proxy-cache configuration

---

sites/partners/lib/hooks.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/1868)
Preference, and programs were not querying by jurisdiction correctly, so if there was data not tied to the jurisdiction they were also being pulled in
This was due to swr caching, so the fix here is to cache the results on a per-jurisdiction basis
The only way I could test this locally was, add a program and/or a preference to the db. Don't tie that entry to a jurisdiction
(I did that by adding in the `createPrograms` function in seed.ts repeats, and did that after the jurisdiction save. if that makes sense?)
create a new partner's listing form and select a jurisdiction
you should not see that program/preference inserted earlier as options on those sections of the form
- Read and …

1868/fixes program, preference, ami-chart de-dupe

---

backend/core/src/listings/views/view.spec.ts

fix(backend): fix view.spec.ts test

---

backend/core/package.json
backend/core/src/listings/dto/listings-query-params.ts
backend/core/src/listings/listings.service.ts
backend/core/test/listings/listings.e2e-spec.ts
backend/core/types/src/backend-swagger.ts
sites/partners/cypress/fixtures/listingImage.json
sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
yarn.lock

This removes the use of jsonpath, which we don't use anymore.
Listing service querying should work as before.

refactor: removes jsonpath

---

ui-components/__tests__/icons/Icon.test.tsx
ui-components/src/icons/Icon.tsx

Add "ariaHidden" as an optional prop on the Icon component to support having decorative icons that are hidden from the accessibility tree.
-See https://github.com/CityOfDetroit/bloom/pull/753 for an example usage
- Added test to make sure aria-hidden was set on the resulting span
- Either explicitly ask a …

Add ariaHidden to Icon component

---

sites/public/pages/applications/financial/vouchers.tsx
sites/public/pages/applications/household/changes.tsx
sites/public/pages/applications/household/student.tsx
ui-components/src/locales/general.json

This PR addresses #2164
Changes copy on yes/no radio questions in the application.
The voucher/student/household steps will have a different helper text above the radio buttons.

fix: change the yes/no radio text to be more descriptive

---

shared-helpers/src/formKeys.ts
sites/public/cypress/mockData/applicationData.ts
ui-components/src/locales/es.json
ui-components/src/locales/general.json
ui-components/src/locales/general_OLD.json
ui-components/src/locales/vi.json
ui-components/src/locales/zh.json

This PR addresses #2166
De-jurisdicitonalize the key for county website in the "How did you hear?" question in demographics. Next step in San Jose / San Mateo would be adding a string override on their branches.
Does the demographics question still work as expected.
If you have one commit and message, squash. If you …

fix: remove alameda reference in demographics

---

backend/proxy/default.conf

fix(backend): make nginx proxy use Language HTTP header in cache key

---

sites/partners/src/applications/PaperApplicationForm/sections/FormPrograms.tsx

Closes #1901
This PR addresses #1901
Removes descriptions and "read more" button from the partners programs form.
Open partners on a dev and check the "I'm homeless" option - it should not include description and "read more" button.
If you have one commit and message, squash. If you need each message to be applied, …

fix: Remove description for the partners programs

---

ui-components/src/overlays/Modal.scss
ui-components/src/overlays/Modal.tsx

Closes #2253
This PR addresses #2253
Updates modal styles on mobile to fill 100% width.
Also, updated modal footer structure to improve layout, see:
before:
after:
s Be Tested/Reviewed?
1. Try to create an account
2. You should see a confirmation modal
3. Check if the modal fit the screen width on mobile and if look good on desktop …

fix: Fix modal styles on mobile

---

sites/public/pages/applications/household/programs.tsx

This PR addresses #2222 
Very minor visual change as described in the issue.
Verify the visual change is present for the Programs questions in a public application submission. Note: @slowbot has confirmed we can keep the vertical orientation of the radio buttons, so the only change here is the left margin of the options.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to …

fix: visual improvement to programs form display

---

sites/public/cypress/integration/pages/submit-application.spec.ts
sites/public/cypress/support/commands.js
sites/public/cypress/support/index.d.ts

[This change](https://github.com/bloom-housing/bloom/commit/81ca55a9f2bca5482985de62ec94e81b34a5ee55) caused application submission tests to not run, just to immediately pass (I'm assuming hitting the done first somehow, maybe an async issue).
Run the test locally and ensure it logs in / begins.
If you have one commit …

fix: submission tests not running

---

ui-components/src/locales/es.json
ui-components/src/locales/vi.json
ui-components/src/locales/zh.json

This PR addresses #1237 
Adds translations
All strings are on the account page

fix: account translations

---

sites/public/page_content/locale_overrides/general.json
sites/public/pages/index.tsx
sites/public/pages/sign-in.tsx
ui-components/src/locales/es.json
ui-components/src/locales/general.json
ui-components/src/locales/vi.json
ui-components/src/locales/zh.json

chore: new alameda translations

---

ui-components/src/locales/es.json
ui-components/src/locales/vi.json
ui-components/src/locales/zh.json

chore: alameda translations - household questions

---

ui-components/src/locales/es.json
ui-components/src/locales/vi.json
ui-components/src/locales/zh.json

chore: missing translations

---

backend/core/src/translations/services/translations.service.ts

This PR addresses #2300 
This adds what to expect to google translate for listings.
Boot it up and go to a listing detail page. You should see What To Expect translated on the public site when you switch languages.

feat: adds whatToExpect to Google Translate

---

sites/public/pages/applications/review/demographics.tsx

This PR addresses #2285 
The repro steps for the bug: visit http://localhost:3000/applications/review/demographics
Select a non-English language, refresh the page
Change the language
The strings would always stay in the page-loaded language - now they should always update
If you have one commit and message, squash. If …

fix: demographics howDidYouHear options were not changing on language

---

ui-components/src/headers/SiteHeader.scss

In SF, they show the feedback bar on mobile, and the text was being cut off. You can see this in an [existing story](https://storybook.bloom.exygy.dev/?path=/story/headers-site-header--with-language-and-mobile-notice) we have.
In Storybook --> SiteHeader --> With Language And Mobile Notice --> in mobile view, the text should wrap to a second line and not cut off …

fix: mobile notice text wrap issue

---

shared-helpers/package.json
sites/partners/package.json
sites/public/package.json
ui-components/package.json

fix: versioning issues

---

backend/core/src/applications/services/application-csv-exporter.service.ts
backend/core/src/shared/units-transformations.ts

This PR addresses #2237
This change adds programs to CSV export.
If you have one commit and message, squash. If you need each message to be applied, rebase …

feat(backend): all programs to csv export

---

backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
backend/core/src/migration/1639135587230-add-partner-terms-to-jurisdiction.ts
backend/core/types/src/backend-swagger.ts

This PR addresses #2233 
This change adds partnerTerms column to jurisdiction entity.
If you have one commit and message, squash. If you need each message to …

feat(backend): add partnerTerms to jurisdiction entity

---

sites/public/pages/listing/[id]/[slug].tsx
ui-components/src/forms/HouseholdSizeField.stories.tsx

refactor: listing detail props

---

shared-helpers/package.json
sites/partners/package.json
sites/public/package.json
ui-components/package.json

Version mismatch issues, bumping manually

chore: bump versions

---

ui-components/src/headers/PageHeader.tsx

This PR addresses DAHLIA ticket [DAH-840](https://sfgovdt.jira.com/jira/software/c/projects/DAH/boards/122?selectedIssue=DAH-840)
DAHLIA's sale directory header has a two-column setup with the page header title in one of the columns. 
To be able to implement this (in progress pr [here](https://github.com/SFDigitalServices/sf-dahlia-web/pull/1552)) we need to add our own title within the grid rather than using the default header. 
Check for adverse effects on bloom code, verify that title is no longer a required prop on the PageHeader component.  
- Also review the acceptance criteria on the Netlify deploy …

feat: make page header title optional

---

ui-components/src/global/lists.scss

This PR addresses DAHLIA Jira ticket [DAH-840](https://sfgovdt.jira.com/jira/software/c/projects/DAH/boards/122?modal=detail&selectedIssue=DAH-840)
When Marçin initially implemented this design, he matched the breakpoint with the old DAHLIA breakpoint of 960px. This PR updates the css for the numbered-list to have the size change at the configured medium breakpoint instead. 
TBD whether I should also update the text styles on this PR, or just set them in my [DAHLIA PR](https://github.com/SFDigitalServices/sf-dahlia-web/pull/1552). 
Look at the styles for numbered list (`/?path=/story/lists-numbered-list--list`) in the review app. to see that the change in font size now happens at the medium breakpoint of 768px.
Describe the tests that you ran to verify your changes. Please also list any …

fix: make numbered list breakpoint match config

---

ui-components/__tests__/notifications/ApplicationStatus.test.tsx
ui-components/src/global/ApplicationStatusType.ts
ui-components/src/notifications/ApplicationStatus.stories.tsx
ui-components/src/notifications/ApplicationStatus.tsx

This PR addresses https://github.com/bloom-housing/bloom/issues/2339
I added:
- an option of "Matched" to `ApplicationStatusTypes` and set it to a green background color
- an optional prop to `Application Status` that allows you to specify what type of icon. 
Look at `/?path=/story/notifications-application-status--matched` and verify that it looks ok and doesn't have any a11y issues. 
- Either explicitly ask a clarifying question, request changes, or approve the PR if …

feat: add matched style to ApplicationStatus

---

ui-components/src/global/mixins.scss

This PR addresses #2341
Makes primary button have primary color, and primary-dark on hover
Look at `?path=/story/actions-button--small-and-primary` and `http://localhost:57886/?path=/story/actions-button--standard` on the ui-components preview and verify that the buttons are primary (#0077DA) by default, and primary-dark (#0067BE) on hover …

fix: make primary buttons primary background

---

ui-components/__tests__/blocks/ImageCard.test.tsx
ui-components/src/blocks/ImageCard.stories.tsx
ui-components/src/blocks/ImageCard.tsx

This PR addresses an issue with PR #2340
I added the application status type, but didn't propagate the change through to the StatusBarType and ImageCard object in #2340. 
Look at `?path=/story/blocks-image-card--with-custom-icon-type` on the storybook review app
- Either explicitly ask a clarifying question, request changes, or approve the PR if …

fix: propagate custom icon type to ImageCard prop

---

backend/core/package.json
shared-helpers/package.json
sites/partners/package.json
sites/public/package.json
ui-components/package.json

Manually bump package versions

fix: bump version

---

ui-components/src/blocks/ActionBlock.scss
ui-components/src/blocks/ActionBlock.stories.tsx

This PR addresses #2171
We were seeing this issue with ActionBlocks on DAHLIA where the buttons didn't have any margin, but the storybook stories looked OK. It was because the css that added the margin was looking for `button` rather than `.button` and we were passing links as actions
look at `?path=/story/blocks-action-block--inline-block-with-2-actions-as-links` on the review app, and compare to `?path=/story/blocks-action-block--inline-block-with-2-actions`. See that they both have the expected margin between buttons.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do …

fix: apply action block style to button class not component

---

ui-components/src/global/forms.scss

Fixes the rtl styles for checkboxes by changing margin-left/margin-right to margin-inline-start/margin-inline-end. We support Arabic for the Detroit Home Connect so this makes the checkboxes look better.
Our example:

Fix checkbox rtl style

---

ui-components/package.json
ui-components/src/page_components/sign-in/FormSignIn.tsx

Remove dependency on shared-helpers in ui-components

fix: move type declarations out of shared-helpers

---

sites/public/cypress.json
sites/public/cypress/integration/pages/submit-application.spec.ts
sites/public/cypress/support/commands.js
sites/public/cypress/support/index.d.ts
sites/public/pages/applications/contact/name.tsx
sites/public/pages/applications/start/autofill.tsx

Currently if you run the public Cypress test `submit-application` locally, it will fail the second time without re-seeding the database.
This is an alternative that would prevent a reseed, although you would still need to close and re-open the Cypress window to reset being signed in.
Cypress *really* does not want you to conditionally test, so I feel like the solution here is a little wonky.
Locally re-seed and run the submit-application test twice ensuring it passes both times (with closing and stopping the test in between).
- Also review the acceptance criteria on the Netlify deploy preview (noting that …

refactor: prevent local reseed with cypress tests

---

sites/partners/lib/formatApplicationData.ts
sites/partners/src/applications/ApplicationsColDefs.ts
sites/public/pages/account/edit.tsx
sites/public/pages/create-account.tsx
ui-components/src/forms/DOBField.tsx

In cases where Day.js needs to parse strings with specific formatting, a custom plugin needs to be imported to extend the days object. This PR adds that in.

fix: ensure dayjs parsing strings will work as expected

---

backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
sites/partners/src/listings/PaperListingForm/index.tsx

Solves an issue on https://dev-partners-bloom.netlify.app/ where the add listing page was not rendering
Open the add listing page, ensure it renders

fix: partners render issue

---

ui-components/__tests__/page_components/ListingCard.test.tsx
ui-components/src/page_components/listing/ListingCard.stories.tsx
ui-components/src/page_components/listing/ListingCard.tsx

This PR addresses #2406
ListingCard now takes optional children to support custom content where the tables currently live - before, it had to display a table. The code changes are minimal, the story is to just POC the ticket with our built in styles. That section would only live with a consumer.
Ideally in the future I think both of these pieces should not be tied together and we can simplify the ListingCard interface but this is more time-sensitive.
Look at the [new stories](https://deploy-preview-2407--dev-storybook-bloom.netlify.app/?path=/story/listing-listingcard--custom-content) in ListingCard
- Also …

feat: listing card takes optional children

---

sites/public/lib/ApplicationConductor.ts
sites/public/pages/_app.tsx
sites/public/pages/applications/start/autofill.tsx
sites/public/pages/applications/start/choose-language.tsx

This sets the listing properly on choose-language, which fixes an issue with refreshing the application before you get to the address section, removes the use of useSwr in fetching a user's profile, since we don't ever want that returning a cached version while revalidating, and re-adds auto save.
Test filling out the application while refreshing at different parts of it. You should be able to continue on with the application. …

fix: issues with public app and re adds auto save

---

backend/core/src/seeder/seeds/ami-charts/default-ami-chart.ts
sites/partners/src/listings/PaperListingForm/UnitForm.tsx
sites/public/lib/ApplicationConductor.ts
sites/public/pages/_app.tsx
sites/public/pages/applications/start/autofill.tsx
sites/public/pages/applications/start/choose-language.tsx

2022 01 24 patch

---

sites/public/src/ListingView.tsx
ui-components/src/global/lists.scss

Closes #2374
Fixes infinite page width.
1. Open a listing page in public
2. Notice that the page has a proper width and horizontal scrollbar is not visible

fix: Fix infinite page width

---

sites/partners/src/listings/PaperListingForm/sections/AdditionalDetails.tsx
sites/partners/src/listings/PaperListingForm/sections/AdditionalEligibility.tsx

Closes #2420
Increases textarea limits for the following fields:
- Credit History
- Rental History
- Required Documents
- Criminal Background
1. Seek for the fields listed above
2. Try to fill with content > 2000
3. A field should be limited to 2000
I used https://wordcounter.net/character-count and https://www.lipsum.com/feed/html for testing purposes.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there …

refactor: Increase textarea limits

---

ui-components/src/locales/es.json
ui-components/src/locales/general.json
ui-components/src/locales/vi.json
ui-components/src/locales/zh.json

This PR addresses #2424
This updates the copy and adds translations for the "Do you anticipate any changes in your household…" question in the public application forms. (FYI, the other copy/translation change will be made only for SJ in the housingbayarea repo.)
Apply for a listing and check all four languages on that form step.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise …

chore: add translation for household changes question

---

backend/core/package.json

build: sets node max-old-space-size

---

backend/core/src/email/email.service.spec.ts
backend/core/src/email/email.service.ts

This PR addresses #2331 
This is a very simple change to remove "to Bloom" after "Welcome" in the email subject.
Create a new user account. I tried seeing if I could get a review app created on Heroku but it didn't work, so I guess you'd have to test this locally or merge into dev first.
If you have one commit and …

chore: switch email subject to just "Welcome"

---

sites/partners/cypress/integration/listing.spec.ts
sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx
sites/partners/src/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx
sites/partners/src/listings/PaperListingDetails/sections/helpers.tsx
sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx
ui-components/src/forms/FieldGroup.tsx

This PR addresses #2393
Moves the leasing agent address to the leasing agent section, and for mailing, pickup, and dropoff addresses shows the leasing agent radio selection as disabled if no valid leasing agent address has been entered.
I also changed the address fields to take up the full width of the form section as there were display issues on smaller screens. This is for leasing agent, mailing, pickup, and dropoff addresses.
I also removed duplication around rendering an address on the listing detail page.
Review the visual changes on the listing form and detail page with the leasing agent address.
- Also …

refactor: move leasing agent address on listing form

---

backend/core/Aptfile

build: adds Aptfile for heroku

---

backend/core/src/listings/listings.service.ts

Currently cannot save a draft listing, this fixes the date input for the new publishedAt and closedAt fields
Add a draft listing with minimal fields and ensure it saves

fix: date validation issue

---

backend/core/package.json
backend/core/src/applications/applications.controller.ts
backend/core/src/applications/dto/applications-csv-list-query-params.ts
backend/core/src/applications/services/applications.service.ts
backend/core/types/src/backend-swagger.ts

refactor: param and auth updates for export

---

backend/core/src/translations/entities/translation.entity.ts

fix(backend): translations input validator

---

backend/core/src/auth/services/authz.service.ts

fix: updates partner check for listing perm

---

ui-components/src/locales/es.json
ui-components/src/locales/general.json
ui-components/src/locales/vi.json
ui-components/src/locales/zh.json

This adds the SMC preferences in: https://github.com/bloom-housing/bloom/issues/2419
```
SELECT
id
FROM jurisdictions
WHERE name = 'San Mateo'
;
INSERT INTO preferences (Title, subtitle, description, links, form_metadata)
SELECT 
'Persons subject to termination of affordability restrictions' as Title,
'' as subtitle,
'Persons who are living in a Below Market Rate deed restricted unit in Foster City for a minimum of twelve (12) months that is subject to termination of affordability restrictions within three (3) years.' as description,
'[]' as links,
'{"key":"terminationOfAffordability","options":[{"key":"atLeastOne","extraData":[],"description":false}]}' as form_metadata
;
INSERT INTO preferences (Title, subtitle, description, links, form_metadata)
SELECT 
'Live and work in Foster City' as …
```

2419/adding SMC preferences

---

backend/core/src/applications/services/applications.service.ts
backend/core/test/applications/applications.e2e-spec.ts

This PR addresses #2403 
This change removes assigning user relation to application partner submission. 
1. Go to the partners portal and submit a new application for any listing. 
2. Go to public portal and log in with the same credentials. You should not see any applications in my applications tab. 
If you have one …

feat(backend): remove assigning partner user as an application owner

---

backend/core/src/applications/services/applications.service.ts

fix: csv export auth check

---

README.md
ui-components/README.md

Updates our README
Nothing new, just corrects outdated information

docs: update readme

---

backend/core/src/migration/1639051722043-add-mfa-related-columns-to-user-entity.ts

This PR addresses #2224 
This change fixes a failing migration where mfa_enabled did not specify a default value for a non null field.
If you have one commit …

fix(backend): mfa_enabled migration fix

---

backend/core/src/migration/1639051722043-add-mfa-related-columns-to-user-entity.ts
backend/core/src/migration/1644581761889-convert-listing-image-to-array.ts

fix: checks for existance of image_id

---

ui-components/__tests__/page_components/UnitTables.test.tsx
ui-components/src/global/headers.scss
ui-components/src/helpers/tableSummaries.tsx
ui-components/src/icons/Icon.tsx
ui-components/src/page_components/listing/UnitTables.stories.tsx
ui-components/src/page_components/listing/UnitTables.tsx

This PR addresses #2362 QA notes
If a unit accordion is enabled, show an icon indicating that it is expandable
Check out the "Unit Summary Tables" stories

fix: add icons to unit accordions if enabled (#2372)

---

backend/core/src/listings/listings.service.ts
backend/core/src/listings/types/listing-orderby-enum.ts
backend/core/src/migration/1644325106310-add-listings-closed-at-fill.ts
backend/core/src/migration/1645110873807-setProdPublishDates.ts
backend/core/types/src/backend-swagger.ts
sites/public/lib/hooks.ts
sites/public/pages/listings.tsx

This PR addresses #2388
This change adds a new orderBy query param to /listings endpoint, making it possible to sort by mostRecentlyClosed. The missing part of the CR is frontend actually using it when displaying closed listings.
- Either explicitly ask a clarifying question, request changes, or approve the PR …

feat(backend): add listing order by mostRecentlyClosed param

---

backend/core/src/migration/1639051722043-add-mfa-related-columns-to-user-entity.ts
ui-components/src/notifications/ApplicationStatus.scss
ui-components/src/notifications/ApplicationStatus.stories.tsx
ui-components/src/notifications/ApplicationStatus.tsx

fix: support text wrapping in ApplicationStatus

---

backend/proxy/default.conf
sites/partners/pages/listings/[id]/edit.tsx
sites/partners/src/listings/PaperListingForm/index.tsx

This PR addresses #2547
This updates partners to purge listings by the ID on save and to only clear the lists if the listing is not pending. This also updates listings/[id]/edit to use server side rendering to match how the detail is fetched. …

feat: updates cache clear to separate individual and lists

---

sites/partners/page_content/locale_overrides/general.json
sites/partners/pages/_app.tsx

feat: overrides partner app website trans

---

sites/public/pages/listings.tsx

fix: serverSideProps on listings bc of netlify limitations

---

ui-components/src/locales/general.json

feat: adds veteran to reserved community types translations

---

sites/public/pages/preview/listings/[id].tsx
ui-components/src/notifications/AlertBox.scss

This PR addresses #2157 (again)
Remove the `max-height` property and ensure proper line alignment.
You can view the AlertBox in Storybook, or if you try to log in on public/partners and use the wrong credentials. You can verify the correct visuals of the preview bar when [previewing a listing](https://deploy-preview-2526--dev-bloom.netlify.app/preview/listings/b832fd76-b212-46ec-9a07-18ac795a5c54). …

fix: more style tweaks for AlertBox

---

backend/core/src/auth/passport-strategies/local-mfa.strategy.ts
shared-helpers/src/catchNetworkError.ts
sites/partners/lib/signInHelpers.ts
sites/partners/pages/sign-in.tsx
ui-components/src/blocks/FormCard.scss
ui-components/src/forms/Field.tsx
ui-components/src/global/forms.scss
ui-components/src/locales/general.json
ui-components/src/page_components/forgot-password/FormForgotPassword.tsx
ui-components/src/page_components/sign-in/FormSignIn.tsx
ui-components/src/page_components/sign-in/FormSignInAddPhone.tsx
ui-components/src/page_components/sign-in/FormSignInErrorBox.tsx
ui-components/src/page_components/sign-in/FormSignInMFACode.tsx
ui-components/src/page_components/sign-in/FormSignInMFAType.tsx

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/1928#issuecomment-1042525792)
This should address the styling issues with the mfa pathways 
Go to the partner's site and log in as user with mfa enabled
as you go through the mfa process, verify that the styling matches what is in the mock, and in the comments of the ticket linked above
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining …

feat: updates to mfa styling

---

sites/public/lib/helpers.tsx
sites/public/lib/hooks.ts
ui-components/src/notifications/ApplicationStatus.stories.tsx

This PR addresses #2333
Addresses a small bit of QA feedback by @slowbot.
Look at listing pages for listings with a due date.

fix: remove space between minutes and AM/PM for ApplicationStatus

---

ui-components/src/notifications/ApplicationStatus.stories.tsx
ui-components/src/notifications/ApplicationStatus.tsx

A request to have the application status bar to allow for a custom icon color to support the below screenshotted scenario present in DAHLIA.
Add an optional prop to Application Status component for `iconColor.` Leaving existing `vivid` prop as is to avoid making a breaking change
New story added to storybook for Application Status > Past Due With Icon Color. 
Verify that 
-color passed in as `iconColor` prop is applied to the icon
-if no `iconColor` is passed, icon should keep its existing styles …

feat: allow application status bar to have custom icon color

---

backend/core/src/auth/services/sms-mfa.service.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/2559)
Updates the text in the sms an mfa user receives 
Create a user that has mfa enabled, or use a user that has mfa enabled
if you have not yet, you will need to reach out to sean to have the user's phone number added to the test twilio account 
attempt to sign in as that user
opt for mfa code via sms 
notice the text matches the request
- Either explicitly ask a clarifying question, request …

2559/update to mfa text's text

---

backend/core/src/auth/controllers/user.controller.ts
backend/core/src/auth/entities/user.entity.ts
backend/core/src/auth/services/user.service.ts
backend/core/src/migration/1647917319793-adding-hit-confirmation-url.ts
backend/core/types/src/backend-swagger.ts

This adds tracking for when a user hits the confirmation page, so we can know if a user successful hit the page or not 
Two flows should be followed:
**Flow 1**
1. create a user
2. follow the confirmation link in the email
3. verify the new timestamp tracking field has been hit
**Flow 2**
1: create a user
2: either wait 1 day, or if the token was set to automatically be expired ignore this step
3: follow the confirmation link in the email for that user
4: verify the new timestamp tracking field has been hit
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet …

feat: adds tracking for confirmation page hit

---

.gitignore
backend/core/src/auth/controllers/user.controller.ts
backend/core/src/auth/entities/user.entity.ts
backend/core/src/auth/services/user.service.ts
backend/core/src/migration/1647917319793-adding-hit-confirmation-url.ts
backend/core/src/shared/filters/catch-all-filter.ts
backend/core/types/src/backend-swagger.ts
sites/partners/src/users/FormUserConfirm.tsx
sites/partners/src/users/FormUserManage.tsx
sites/partners/src/users/ReRequestConfirmation.tsx
ui-components/src/locales/general.json

This PR is taken from Detroit https://github.com/CityOfDetroit/bloom/pull/1047, which adds the ability for a partner user to resend the confirmation.
for engineering: 
mark the expiry date of the token in the `createConfirmationToken` function as in the past (instead of +24, use -24)
1: create a user
2: either wait 1 day, or if the token was set to automatically be expired ignore this step
3: follow the confirmation link in the email for that user
4: enter a valid password
5: a modal should pop up when you attempt to confirm account that the token is invalid
6: fill out and submit the email in that modal
7:  a new email should be received with a new confirmation token that works
- …

feat: adds partners re-request confirmation

---

sites/partners/src/users/FormUserManage.tsx

This PR addresses #2366 
This fixes an issue where the listings all checkbox was not respecting the status of the listing checkboxes. This addresses it by unchecking the all checkbox when not all of the listings are checked and checks it when all of them are checked.
Boot up locally and go to partners portal users. Add a new user or edit an existing one. Check the all listings checkbox and unselect an individual listing, you should see the all checkbox unselect. Reselect that listing and you should see the all checkbox reselect.
- Also review the acceptance criteria on the Netlify deploy preview (noting that …

fix: partners user lisitngs all checkbox

---

backend/core/src/auth/services/user.service.ts
backend/core/src/migration/1639051722043-add-mfa-related-columns-to-user-entity.ts
sites/partners/src/users/FormUserConfirm.tsx

feat: temp disable terms and set mfa enabled to false

---

CHANGELOG.md
backend/core/CHANGELOG.md
backend/core/package.json
backend/core/src/auth/controllers/auth.controller.ts
shared-helpers/CHANGELOG.md
shared-helpers/package.json
sites/partners/CHANGELOG.md
sites/partners/package.json
sites/public/CHANGELOG.md
sites/public/package.json
ui-components/CHANGELOG.md
ui-components/package.json

chore: sync versions and changelog from master release

---

sites/partners/src/listings/PaperListingForm/UnitForm.tsx

This PR addresses #2445 
Added a margin bottom to the button in unit modal to address button spacing issue in mobile view.
On Partners portal, open up Listing Form, click Add Unit and on small screen, you should see that spacing issues are fixed.
If you have one commit and message, squash. If you need each message to …

fix: added margin bottom to button on mobile in unit modal

---

sites/public/cypress/support/commands.js
sites/public/lib/helpers.tsx
sites/public/pages/applications/start/choose-language.tsx
sites/public/src/ListingView.tsx
ui-components/__tests__/blocks/ImageCard.test.tsx
ui-components/__tests__/page_components/ListingCard.test.tsx
ui-components/src/blocks/ImageCard.scss
ui-components/src/blocks/ImageCard.stories.tsx
ui-components/src/blocks/ImageCard.tsx
ui-components/src/global/text.scss
ui-components/src/headers/Heading.stories.tsx
ui-components/src/headers/Heading.tsx
ui-components/src/page_components/listing/ListingCard.scss
ui-components/src/page_components/listing/ListingCard.stories.tsx
ui-components/src/page_components/listing/ListingCard.tsx

This PR addresses [Detroit 975](https://github.com/CityOfDetroit/bloom/issues/975) and #2268 
Updates the listing card and image to follow the new designs and account for the needs in Detroit and SF
1) Updates the ImageCard component props to remove the title/subtitle and add an optional array of tags
2) Updates the Heading component props to allow for the new heading variations
3) Updates the ListingCard component props to allow for multiple footer buttons / a custom footer (Detroit), custom header styling (SF), and adds the new headers and formatting while cleaning up the component
Check out the new stories for ImageCard, Heading, and ListingCard
Check out the directory and details pages for listings on desktop and mobile
[Public Site …

feat: listing card title redesign, multiple tags possible

---

ui-components/src/lists/PreferencesList.tsx

Small change so that users don't leave the listing page when clicking on a preference link. I assumed we'd want this in all cases, but if we want this configurable let me know and I can add a prop to `ListPreferenceLink`
View the Preferences List component in storybook and click on the link. Link should now open in a new tab/window.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are …

feat: open preference links in new tab/window

---

backend/core/CHANGELOG.md
backend/core/package.json
shared-helpers/CHANGELOG.md
shared-helpers/package.json
sites/partners/CHANGELOG.md
sites/partners/package.json
sites/public/CHANGELOG.md
sites/public/package.json
sites/public/pages/listings.tsx
ui-components/CHANGELOG.md
ui-components/package.json
yarn.lock

2022-04-06 sync master

---

sites/partners/src/users/FormUserConfirm.tsx
sites/partners/src/users/FormUserManage.tsx

This fixes an issue introduced with the last terms PR where a new user couldn't be created.

fix: sets agreedToTermsOfService properly

---

ui-components/src/blocks/ActionBlock.tsx
ui-components/src/headers/SiteHeader.tsx
ui-components/src/locales/general.json
ui-components/src/navigation/LanguageNav.stories.tsx
ui-components/src/navigation/LanguageNav.tsx

Fixes the following a11y issues from components used on the dahlia homepage
For the language switcher, view the `LanguageNav` component in storybook. If the knob value is empty, the `aria-label` attribute should not be on the `nav` element.  After adding a value for the knob e.g. 'Choose a language', `aria-label` attribute should now be added to the `Nav` element. …

fix: a11y issues on homepage components

---

backend/core/src/auth/entities/user.entity.ts

This PR addresses #2651 
This updates the IsPhoneNumber validator for users to specify the region and fixes an issue discovered when attempting to save the terms for a user with a phone number.
1. create a new user and assign them to a San José listing
2. confirm the user and when you get to the terms acceptance page, sign out before accepting
3. go to login with the user and specify phone number for MFA, this should set the phone number for the user
4. when you get to the terms page, you should be able to accept and save without issue …

fix: adds region to user phone # validation

---

shared-helpers/src/formKeys.ts
sites/partners/lib/formatApplicationData.ts
sites/partners/page_content/locale_overrides/general.json
sites/partners/src/applications/PaperApplicationForm/FormTypes.ts
sites/partners/src/applications/PaperApplicationForm/PaperApplicationForm.tsx
sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
sites/public/pages/applications/household/ada.tsx
ui-components/src/forms/FieldGroup.tsx
ui-components/src/locales/general.json

This PR addresses #2127
The initial AC in the ticket was to update the ada step in the public site application to remove our use of plain input tags and make use of our Field components instead.
We updated the public site ada step to use our FieldGroup component, and noticed that the ada fields on the partners side manual application input form were just repeating Field components instead of using a FieldGroup, so we updated that as well, and added the shared keys to the shared-helpers package.
Ensure that the ADA step in the public application works exactly as before: (1) The values should save appropriately (2) Checking the none value should uncheck all the other values, and checking any other value should uncheck the none value (3) The checkboxes should autofill to their previous input …

feat: refactor ada form fields

---

ui-components/src/page_components/forgot-password/FormForgotPassword.tsx
ui-components/src/page_components/sign-in/FormSignIn.tsx

This PR addresses #2548 and #2573
This PR addresses the missing bottom border of the Sign In form card, as well as an unnecessary grey background behind the submit button on the Forgot Password form. While in the Forgot Password form, I also found an empty warning message and this PR addresses that as well.
Entry point: http://localhost:3000/sign-in
1. Notice a bottom border line between the Sign In form and the 'Don't Have an Account?' section
2. Click Forgot Password? and notice that the Send Email button is not enclosed by a light grey box
3. Also on this page, notice that there is no empty warning
- …

fix: forgot password empty warning and two minor style changes

---

backend/core/src/migration/1650934163344-alameda-programs-and-preferences.ts

This deploys the program and preference changes 
for: https://github.com/bloom-housing/bloom/issues/2623 
related to: https://github.com/housingbayarea/bloom/pull/398

feat: adding alameda prog and prefs

---

sites/public/pages/applications/start/choose-language.tsx

This PR addresses #2639 
This PR adds a margin bottom on screen sizes smaller than 640px equal to the left/right margin between buttons.
Entry Point: First page of the public application.
In console, or on mobile screen, you will see that if language buttons are pushed to a second line, there is an adequate margin between the bottom of the first row and the top of the second row.
- Either explicitly ask a clarifying question, …

style: language button margin bottom

---

shared-helpers/__tests__/stringFormatting.test.ts
shared-helpers/src/stringFormatting.ts
sites/public/src/ListingView.tsx
ui-components/__tests__/page_components/AdditionalFees.test.tsx
ui-components/src/page_components/listing/AdditionalFees.stories.tsx
ui-components/src/page_components/listing/AdditionalFees.tsx

This PR addresses #2690
Removes business logic and strings from the application fee component, and fixes a margin issue on small screens between the blocks. Also makes it more flexible to accept any number of below-fee strings.
[Storybook deploy preview](https://deploy-preview-2691--dev-storybook-bloom.netlify.app/?path=/story/listing-additional-fees--all-fields)
Check out the `AdditionalFee` stories and the section on an existing listing to ensure there are no changes apart from the padding fix.
- Also review the acceptance criteria on the Netlify deploy preview …

refactor: remove business logic, strings from application fee component

---

sites/public/src/ListingView.tsx
ui-components/src/global/text.scss
ui-components/src/page_components/listing/ListingCard.scss
ui-components/src/page_components/listing/ListingCard.tsx

This PR addresses #2268 QA
Addresses the QA updates in this comment: https://github.com/bloom-housing/bloom/issues/2268#issuecomment-1094429120
Ensure the ListingCard titles have centered mobile views, that the padding is adjusted as requested, and that the listing title is black on the detail pages.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR …

fix: ux updates for new listing card design

---

backend/core/src/translations/services/translations.service.ts

Pulling this Detroit fix back into core: https://github.com/CityOfDetroit/bloom/pull/1191

fix: check for empty translations before sending to google translate

---

ui-components/src/footers/SiteFooter.stories.tsx
ui-components/src/navigation/FooterNav.scss

This PR addresses #2712
Fixes alignment issues in the `SiteFooter` component when you have enough links to overflow (screenshot in the issue).
Look at the new [stories](https://deploy-preview-2713--dev-storybook-bloom.netlify.app/?path=/story/footers-site-footer--overflowing-links) added to the `SiteFooter` component.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining …

fix: footer alignment issue with overflowing links

---

ui-components/src/navigation/FooterNav.scss

fix: site footer overflowing

---

backend/core/src/auth/dto/user-list-query-params.ts
backend/core/src/auth/repositories/user-repository.ts
backend/core/src/auth/services/user.service.ts
backend/core/test/user/user.e2e-spec.ts
backend/core/types/src/backend-swagger.ts

This PR addresses #2656
This changes add `search` query param to `GET /user/list` endpoint allowing search by:
- user.firstName
- user.lastName
- user.email
- leasingAgentInListings.name
This can be review using POSTMAN or cURL:
```
Authenticate:
AUTH_TOKEN=$(curl -H "Content-Type: application/json" -X POST http://localhost:3100/auth/login --data '{"email": "admin@example.com", "password": "abcdef"}' | jq .accessToken | tr -d '"')
Send GET request: 
curl  -H "Content-Type: application/json" -H "Authorization: Bearer $AUTH_TOKEN" -H "jurisdictionName: Alameda"  http://localhost:3100/user/list\?limit\=4\&search\=Second
```
- Pull the changes …

feat(backend): add search param to GET /user/list endpoint

---

sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx

No related ticket - just found during PR review. Without this optional, some listings locally were unable to load the listing details page in partners.
Ensure the `lottery results - pending` listing can render the listing details page in partners.
If you have one commit and …

fix: check for empty url before rendering

---

backend/core/CHANGELOG.md
backend/core/package.json
package.json
shared-helpers/CHANGELOG.md
shared-helpers/package.json
sites/partners/CHANGELOG.md
sites/partners/package.json
sites/public/CHANGELOG.md
sites/public/package.json
ui-components/CHANGELOG.md
ui-components/package.json

2022 05 24 sync master

---

backend/core/src/auth/repositories/user-repository.ts
backend/core/src/auth/services/password.service.ts
sites/partners/lib/hooks.ts

Fixes performance issues with user queries.

perf: user list and user getQb

---

backend/core/src/auth/filters/user-query-filter.ts
backend/core/src/auth/services/user.service.ts
backend/core/src/listings/tests/listings.service.spec.ts
backend/core/src/shared/query-filter/index.ts

This PR addresses #2725 
This PR is a refactor of some of how we are handling the filtering of users, pulling in improvements that we made in Detroit. Apart from some Detroit-specific filters, these files are now mostly identical.
Ensure that the partners users table is functioning appropriately in terms of fetching all partners users.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are …

refactor: refactor user filters to pull in improvements from detroit

---

sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx

Fixes an issue with the selectAndOrder component drag and drop where StandardTable now returns a different structure.

fix: selectAndOrder drag and drop

---

backend/core/jest-e2e.json
backend/core/test/applications/applications.e2e-spec.ts
backend/core/test/listings/listings.e2e-spec.ts
backend/core/test/listings/utils/make-test-listing.ts

Fixes some of the backend e2e tests.

test: fixes backend e2e tests

---

ui-components/src/overlays/Modal.scss
ui-components/src/overlays/Modal.stories.tsx
ui-components/src/overlays/Modal.tsx

This PR addresses [DAH-1157](https://sfgovdt.jira.com/jira/software/c/projects/DAH/boards/122?modal=detail&selectedIssue=DAH-1157)
We need to approximate the appearance of the lottery results modal on the angular version of DAHLIA. This PR adds an optional prop `scrollable` that makes the modal a fixed height and scrollable for long body content.
Run storybook and open the scrollable modal story
- Either explicitly ask a …

feat(modal): add option for fixed-height scrollable modal

---

shared-helpers/src/formKeys.ts
sites/partners/src/applications/PaperApplicationForm/sections/FormApplicationData.tsx
sites/partners/src/users/FormUserManage.tsx
ui-components/src/helpers/formOptions.tsx

This PR addresses #2772
Removes backend dependencies from `formOptions` in ui-components, and moves the offenders to shared-helpers.

refactor: remove backend deps from form options

---

backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
backend/core/src/migration/1654560903063-add-settings-jurisdiction-toggle.ts
backend/core/src/seeder/seeds/jurisdictions.ts
backend/core/types/src/backend-swagger.ts
sites/partners/layouts/index.tsx
sites/partners/page_content/locale_overrides/general.json
sites/partners/pages/settings/index.tsx

This PR addresses #2745
Adds settings page in partners, and renders it conditionally based off of a field on the jurisdiction, so that we can easily toggle this on and off in Detroit.
Ensure the page is available for admins in partners
If you have one commit and message, …

feat: add settings page to partners

---

sites/partners/pages/sign-in.tsx
ui-components/src/page_components/sign-in/FormSignInMFACode.tsx
ui-components/src/page_components/sign-in/FormSignInMFAType.tsx

This PR addresses #2778 #2779
These components generally need a refactor here to remove some existing Bloom-specific constraints - but this is a workaround for now to remove backend dependencies, since this is not a pressing component for consumers to uptake.
Ensure the MFA flow works without regression.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the …

refactor: remove backend deps from mfa components

---

ui-components/package.json

Add a missing dependency in ui-components that is preventing consumer build.

fix: add missing dependency preventing build

---

ui-components/src/actions/ExpandableContent.tsx

add classname prop for customization needed for dahlia
#2798
Added a className prop into Expandable Component.
Go into ExpandableContent.stories.tsx, add a className prop and verify that the styles are applied.
If you have one commit and message, …

feat(expandablecontent.tsx): add classname prop

---

sites/partners/src/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
sites/partners/src/listings/PaperListingDetails/sections/DetailUnits.tsx
sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
sites/partners/src/listings/PaperListingForm/sections/LotteryResults.tsx
sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
sites/partners/src/listings/PaperListingForm/sections/Units.tsx
ui-components/src/blocks/StandardCard.stories.tsx
ui-components/src/global/tables.scss
ui-components/src/icons/Icon.tsx
ui-components/src/locales/general.json
ui-components/src/tables/MinimalTable.stories.tsx
ui-components/src/tables/StandardTable.tsx

This PR addresses #2747
This PR would get rather large with the UI updates and the functionality, so I'm splitting out the first piece here.
Adds a new stories under MinimalTable and StandardCard that demonstrate a usage of the existing MinimalTable component to get the requested table. 
The new additions and UX bug fixes are:
The vertical padding of all minimal tables that use buttons has been fixed to match the default minimal table height, there is a new order column in draggable tables, new sort styling, there is now a border under the headers and not under the last row, and when dragging rows now have a border on both the top and the bottom.
I opted to not use styles v2 because there weren't many styles to add into our existing `tables.scss` file, and so teasing out what to update …

feat: actionable row component

---

backend/core/CHANGELOG.md
backend/core/package.json
backend/core/src/listings/dto/listings-query-params.ts
shared-helpers/CHANGELOG.md
shared-helpers/package.json
sites/partners/CHANGELOG.md
sites/partners/package.json
sites/public/CHANGELOG.md
sites/public/package.json
ui-components/CHANGELOG.md
ui-components/package.json

Syncs master down to dev, for versioning.

2022-06 -16 sync master

---

sites/public/lib/helpers.tsx
ui-components/__tests__/page_components/ListingCard.test.tsx
ui-components/src/page_components/listing/ListingCard.stories.tsx
ui-components/src/page_components/listing/ListingCard.tsx

Related to some DAHLIA changes necessary for adding accessibility features to abbreviations that appear in listing verbiage. We are using the `<abbr>` tag which necessitates a move from subheader content as a string to a JSX element.
The additional prop is optional so pages currently using the `ListingCard` should not be affected.  …

feat(listingcard): add compatability for jsx elements in subheader

---

ui-components/src/page_components/sign-in/FormSignInMFAType.tsx

fixes issue with mfa verification email/phone swap.

fix: mfa verificication fields

---

ui-components/__tests__/page_components/GetApplication.test.tsx
ui-components/src/page_components/listing/listing_sidebar/GetApplication.stories.tsx
ui-components/src/page_components/listing/listing_sidebar/GetApplication.tsx

This PR addresses #2845
Hides the `how to apply` section when there are no paper application files or digital application URL.
1. Open partners and create a new listing
2. Check the `Is there a digital application?` to `no`
3. Check the `Is there a paper application?` to `yes`
4. Do not upload any paper application files
5. Open preview and make sure that the section is not visible
- Either explicitly ask a clarifying question, …

fix: hide apply section if there is no data

---

ui-components/src/blocks/ImageCard.scss

This PR addresses #2850
With previous styling updates, some padding turned into margin instead which messed up the image card spacing on the listing page. This switches back to padding.
View a listing page here: https://deploy-preview-2851--dev-bloom.netlify.app/listing/e47f050a-3a0a-479d-a91b-8bae499c5eee/application_deduplication_demo_548_market_street_san_francisco_ca
- Either explicitly ask a clarifying question, request …

fix: switch back to padding for image card leader

---

backend/core/src/preferences/dto/preference.dto.ts
backend/core/src/preferences/preferences.service.ts
backend/core/types/src/backend-swagger.ts
sites/partners/lib/hooks.ts
sites/partners/page_content/locale_overrides/general.json
sites/partners/pages/settings/index.tsx
ui-components/src/blocks/StandardCard.scss
ui-components/src/locales/general.json

This PR addresses #2751
Fetches jurisdictional preferences from all the jurisdictions the user has on the settings page. I fought with this for a while trying to call the single hook multiple times and ended up just changing the comparison on the hook to `IN` so I could pass in multiple jurisdictions in one call. Open to feedback!
Log in as admin, ensure you can see all jurisdictions preferences. Create a parter and assign them one jurisdiction, ensure you can see only that jurisdictions preferences.
Ensure the loading state and empty states trigger appropriately.
- …

feat: populate jurisdictional preferences on settings page

---

ui-components/src/page_components/listing/listing_sidebar/Contact.tsx

Add react key to additional info items in the Contact component to reduce unit test error logging, but also help React identify which items have changed in the list.
Run the unit test `Contact.test.tsx` and/or load the component (Contact > Additional Information) in storybook. Should no longer see the error in the console "Warning: Each child in a list should have a unique "key" prop." …

Add react key

---

ui-components/src/notifications/ApplicationStatus.stories.tsx
ui-components/src/notifications/ApplicationStatus.tsx

Add optional styling to the Application Status component. This is needed for DAHLIA which centers the text.
View the Application Status component in storybook. There is a new story for 'Past Due with Styles' which has a text knob for specifying component level styles.
If you …

Add classname prop for custom styling

---

ui-components/src/overlays/Modal.tsx
ui-components/src/overlays/Overlay.tsx

Modal scrolling was already implemented and working for desktop and most mobile devices, but we discovered it was not working on actual iphones (iphone emulator was ok). Honor the `scrollable` prop all the way through to the `Overlay,tsx` component
View the Scrollable Modal story in storybook using an actual iphone. Verify the content is now scrollable.
- Either explicitly ask a clarifying question, request changes, or approve …

fix(component): allow modals to scroll for iphone

---

ui-components/src/page_components/listing/listing_sidebar/events/EventSection.stories.tsx
ui-components/src/page_components/listing/listing_sidebar/events/EventSection.tsx

add classname to date span for customization
#2907
There was a design request to allow title-cased dates (January 19 vs upper-cased JANUARY 19) within the EventSection component. To support this, I added a className prop that gets applied to the date span. This would allow a user to pass in a class to override the uppercase css styling and I figure it wouldn't hurt to add some customization.
Check out storybook - there should be a new instance showcasing the title-cased date. Check out the code changes to ensure there was no breaking changes. 
- [] My changes generate no new warnings …

feat(eventsection): allow EventSection to lowercase date

---

backend/core/src/auth/guards/authz.guard.ts
backend/core/src/auth/services/authz.service.ts
backend/core/src/listings/tests/listings.service.spec.ts
backend/core/src/units/units.module.ts
ui-components/package.json
ui-components/src/helpers/MultiLineAddress.tsx
yarn.lock

This fixes two issues:
1. the preview was throwing an error. The fix was to use a different package for DOMPurify
2. jurisdiction admins could not delete users. The fix was to alter how we're checking for user access with jurisdictional admins.

fix: preview and juri admin perms for user access

---

backend/core/CHANGELOG.md
backend/core/package.json
shared-helpers/CHANGELOG.md
shared-helpers/package.json
sites/partners/CHANGELOG.md
sites/partners/package.json
sites/public/CHANGELOG.md
sites/public/package.json
ui-components/CHANGELOG.md
ui-components/package.json

2022-07-26 sync master

---

backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
sites/partners/src/flags/flagSetCols.tsx

This addresses the issue where hitting the application flagged set endpoint on the backend causes crashes
Aim your local at dev
head to a listing's applications specifically the flagged applications
the grid should load much snappier now, and should actually load
If you have …

fix: fix for big timeout on flagged set

---

ui-components/src/page_components/listing/ListingCard.scss

This PR addresses #2611
Fixes an issue found in QA where the clickable link region for a listing card didn't cover the tag on the image itself. (see https://github.com/bloom-housing/bloom/issues/2611#issuecomment-1201922727)
Check out this story: https://deploy-preview-2943--dev-storybook-bloom.netlify.app/?path=/story/page-components-listing-card--with-headers …

fix: ensure listing card link region covers image tags

---

backend/core/src/applications/dto/applications-csv-list-query-params.ts
sites/partners/pages/listings/[id]/applications/index.tsx

This PR addresses #2937 
This updates the application export button to include demographics if the user is an admin. This way we don't have to get a developer involved.
Login as an admin and export applications. You should see demographic info. Login as a leasing agent or jurisdictional admin, and you should not see that info in the export.
- Either explicitly ask a clarifying question, request changes, or approve the PR if …

feat: adds includeDemographics if admin

---

backend/core/src/migration/1655821661726-remove-property-relation.ts

This updates the property migration, so that when this gets moved over to detroit we don't cause problems for the existing listings

fix: update to resolve issue with migration

---

ui-components/src/blocks/ImageCard.scss

This PR addresses #2969 
We currently have a bug on production where at a tablet screen size, the image on a single listing view is not extending the full width of the screen
Check out a single listing view and check all screen widths. At a desktop width it should fit within the left/right panel view. Once the right panel collapses, the image should expand to full screen width.
- Either explicitly ask a clarifying question, …

fix: image width fix for tablet screen sizes

---

ui-components/src/actions/ExpandableText.stories.tsx
ui-components/src/actions/ExpandableText.tsx

There's been a design request from SF that can be addressed by adding a className prop on the ExpandableText component. 
- Check that all storybook instances of ExpandableText that don't use the new prop haven't changed
- Ensure that the code updates don't introduce breaking changes
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but …

feat(expandabletext): add classname to expandable text button

---

backend/core/src/migration/1658871879940-multiselect-question.ts

This is a migration update for the pref/program to multiselect question 
in theory this should build the translations we need without affecting the build in ci

fix: update for migration

---

backend/core/src/migration/1658871879940-multiselect-question.ts
backend/core/src/seeder/seeds/listings/shared.ts

Updates to migration:
this should make running `yarn db:migration:run` work

fix: migration updates

---

backend/core/src/migration/1658871879940-multiselect-question.ts

hotfix for the migration on dev

fix: update to get migration to run on dev

---

backend/core/src/migration/1658871879940-multiselect-question.ts

This makes some updates to the migration around programs being radios by defaults and also resolves the double `'` one

fix: Migration hotfix 2

---

backend/core/src/multiselect-question/multiselect-question.controller.ts
shared-helpers/src/multiselectQuestions.tsx
sites/partners/layouts/index.tsx
sites/partners/tailwind.config.js
sites/public/tailwind.config.js

Two bash fixes for preferences:
(1) Styling discrepancies between local and build
(2) The tab should be hidden for partners users who only have a partners role
For (1), see the below issue
For (1) Using the Netlify preview, walk through an application (`APPLICATION DEDUPLICATION DEMO` will work) and ensure the padding is consistent between checkbox options. All the right styles were there, but they were being applied in a different order than they were locally.
For (2) Login as a user who is just a partner (you can create a new one) and ensure the `Settings` tab is not present. …

fix: styling precedence issues in preferences

---

backend/core/src/migration/1655122535654-update-invite-email-text.ts
backend/core/src/migration/1655299904609-add-default-email-translations.ts

This fixes a couple of migration files that already ran in prod (were fixed there first)

fix: updates translation migration files

---

backend/core/src/migration/1655122535654-update-invite-email-text.ts
backend/core/src/migration/1655299904609-add-default-email-translations.ts
backend/core/src/multiselect-question/multiselect-question.controller.ts
sites/partners/layouts/index.tsx
sites/partners/tailwind.config.js
sites/public/tailwind.config.js

2022 08 25

---

ui-components/src/page_components/listing/listing_sidebar/Contact.stories.tsx
ui-components/src/page_components/listing/listing_sidebar/Contact.tsx

This PR addresses #2998
If the Contact section has office hours but no website or address, the phone number section wasn't displaying with enough padding.
Check out the new story (the screenshot is the new story on dev) and ensure there is space between the phone number and office hours sections. …

fix: add margin in contact section

---

backend/core/src/auth/passport-strategies/jwt.strategy.ts
backend/core/src/shared/views/change-email.hbs
sites/partners/src/listings/Aside.tsx
sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts
sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
sites/partners/src/users/FormUserManage.tsx
sites/public/pages/create-account.tsx
sites/public/src/ListingView.tsx
ui-components/src/forms/FieldGroup.stories.tsx

This PR syncs over some small code improvements from Detroit that are causing merge conflicts when we pull from core.

refactor: detroit improvements

---

sites/public/pages/applications/financial/vouchers.tsx
sites/public/pages/applications/household/ada.tsx
sites/public/pages/applications/household/changes.tsx
sites/public/pages/applications/household/student.tsx
sites/public/src/ApplicationMultiselectQuestionStep.tsx

This PR addresses #3009
Remove redundant select language from above application multiselect questions.
View multiselect questions (household, programs, preferences) in an application and ensure the text is no longer present.
If you have one commit and message, squash. If you …

fix: remove select text from multiselect application questions

---

sites/partners/pages/index.tsx
sites/partners/pages/users/index.tsx
ui-components/src/tables/AgTable.tsx

This PR addresses #3004 (sort of)
At the moment, the ag grid react table we are using is not configured to have the columns take up the full width of the table container - this is the fix for that. It was initially noticed in the duplicates branch - I have a PR to fix it over there, so I'm just putting the fix in core for our existing tables.
Compare the listings table and users table in partners on this branch to dev, and ensure the columns take up the full width of the table and do not super squish themselves on mobile as they do on dev. …

fix: table columns should take up full width

---

sites/public/src/ListingView.tsx
ui-components/__tests__/page_components/ReferralApplication.test.tsx
ui-components/src/blocks/HousingCounselor.tsx
ui-components/src/blocks/ImageCard.tsx
ui-components/src/blocks/StatusItem.tsx
ui-components/src/forms/DOBField.tsx
ui-components/src/forms/DateField.tsx
ui-components/src/forms/Dropzone.tsx
ui-components/src/forms/FieldGroup.tsx
ui-components/src/forms/HouseholdMemberForm.tsx
ui-components/src/forms/HouseholdSizeField.tsx
ui-components/src/forms/TimeField.tsx
ui-components/src/headers/Hero.tsx
ui-components/src/headers/SiteHeader.tsx
ui-components/src/helpers/formOptions.tsx
ui-components/src/helpers/formatYesNoLabel.ts
ui-components/src/navigation/ProgressNav.tsx
ui-components/src/notifications/StatusMessage.tsx
ui-components/src/page_components/ApplicationTimeline.tsx
ui-components/src/page_components/listing/listing_sidebar/GetApplication.tsx
ui-components/src/page_components/listing/listing_sidebar/ListingUpdated.tsx
ui-components/src/page_components/listing/listing_sidebar/OrDivider.tsx
ui-components/src/page_components/listing/listing_sidebar/ReferralApplication.stories.tsx
ui-components/src/page_components/listing/listing_sidebar/ReferralApplication.tsx
ui-components/src/page_components/listing/listing_sidebar/events/DownloadLotteryResults.tsx
ui-components/src/tables/AgTable.tsx
ui-components/src/tables/StandardTable.tsx

This PR addresses #3013
For each component, we need to allow consumers to be able to pass in their own strings, as they may have a different translation tool or keys. This PR updates all components with current `t()` calls in ui-components to support optionally passing in custom strings for those values.
Ensure we are always falling back to the existing value. …

refactor: allow custom strings

---

ui-components/src/notifications/AlertBox.docs.mdx
ui-components/src/notifications/AlertBox.scss
ui-components/src/notifications/AlertBox.stories.tsx
ui-components/src/notifications/AlertBox.tsx
ui-components/src/notifications/alertTypes.ts

This PR addresses #3015 #1396
Completes the styling V2 refactor of the AlertBox component and fixes one existing bug around links being the wrong color, as well as fixing one very small vertical misalignment with the icon and the text.
Here is an example alert on SF that we will need to support with custom styling (the custom styling story is an example of this):
Check out the [stories](https://deploy-preview-3014--dev-storybook-bloom.netlify.app/?path=/story/notifications-alert-box--alert-box-alert) and ensure there are no regressions compared to [dev](https://storybook.bloom.exygy.dev/?path=/story/notifications-alert-box--alert-box-alert).
- …

refactor: alert box v2 styling refactor

---

sites/public/lib/appAutofill.ts

This PR addresses #3011
This addresses the issue where a user applies to listings that have programs and then applies to a listing that doesn't have programs the programs were getting autofilled to the application. So this PR resets all of the programs when starting an application (same way preferences were done)
This does **NOT** address the existing applications that ran into this issue. We will need to follow up with a migration script to clean those ones up
When signed in to the public site apply to a listing that has preferences and programs. Make sure to select some of the programs when doing the application.
Switch to a listing that doesn't have any programs. Apply to that listing.
Go to the partners site and export the applications for the second listing that was applied to. There …

fix(application): remove programs from autofill

---

ui-components/src/page_components/ApplicationTimeline.scss
ui-components/src/page_components/ApplicationTimeline.tsx

Porting over the css fix for ApplicationTimeline from HBA

fix: updated css class naming

---

sites/public/pages/applications/financial/income.tsx
sites/public/pages/applications/household/student.tsx

This PR addresses #3071 
conductor.completeStep() were missing or got wrong value 
Go through application process

3071/Core - Fix Progress Bar

---

sites/partners/pages/settings/index.tsx

This PR addresses #3029
Instead of prepending the `Copy` test, append it, so that copied don't change their location in the list since we are sorting alphabetically.
Copy a preference, ensure the `Copy` text appears after the name.
If you have one commit and message, squash. If …

fix: append copy text to copied preferences

---

backend/core/src/application-flagged-sets/application-flagged-sets.controller.ts
backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
backend/core/types/src/backend-swagger.ts
sites/partners/pages/application/[id]/review.tsx

This PR addresses #2860 
When you update an application flagged set to resolved, an alert should pop up indicating how many applications you have verified. It should persist between all users until it is explicitly dismissed, even after logging out.
Resolve an application flagged set and ensure the alert appears. Ensure it persists on the resolved set page until it is dismissed.
- Either explicitly ask a clarifying question, …

feat: show dismissable alert when updating afs

---

sites/public/lib/helpers.tsx
ui-components/src/page_components/listing/ListingCard.stories.tsx
ui-components/src/page_components/listing/ListingCard.tsx

This PR addresses #3089 
We had a visual change in ui-components that will break the ListingCard for consumers. The newly added pill styling on the unit availability on the ListingCard needs to be an optional style update so that it doesn't automatically roll out to consumers.
Check out the new [story](https://deploy-preview-3088--dev-storybook-bloom.netlify.app/?path=/story/page-components-listing-card--with-pill-header) and ensure we do see the pill type on the deploy [preview](https://deploy-preview-3088--dev-bloom.netlify.app/listings) / that we are uptaking the new optional prop.
- Pull the changes down locally and test that the …

fix: make pill style on listing card optional

---

backend/core/package.json
backend/core/src/email/email.service.spec.ts
package.json
sites/partners/package.json
sites/public/package.json
ui-components/package.json
yarn.lock

chore: standardize the typescript version

---

sites/partners/lib/hooks.ts
sites/partners/pages/listings/[id]/applications/resolved/index.tsx

This PR addresses #3099
This issue fixes pagination for both pending and resolved pages.
Locally, you can boot it up and review the duplicates pages and make sure changing the limit and page work as expected.
If you have one commit and message, squash. If you need each message …

3099/AFS Pagination

---

backend/core/src/email/email.service.spec.ts
backend/core/src/migration/1664235051977-email-typo.ts
ui-components/src/locales/general.json

Ad-hoc, fixes the email backend test + a typo in the original copy

fix: email tests

---

backend/core/package.json
shared-helpers/package.json
sites/partners/package.json
sites/public/package.json
ui-components/package.json

chore: sync release version from main to dev

---

sites/partners/pages/listings/[id]/applications/index.tsx

Ad-hoc, [context](https://exygy.slack.com/archives/C02G1S19QA2/p1664892288933419)

fix: individual application link in applications table

---

sites/partners/page_content/locale_overrides/general.json
sites/partners/pages/listings/[id]/applications/pending/index.tsx
sites/partners/pages/listings/[id]/applications/resolved/index.tsx

This PR addresses #3100
This PR updates the label at the bottom of the tables on the application set pages to read `set`/ 'sets` vs applications to differentiate these tables from the first tab which does show `applications`.
Open the `pending` and `resolved` tabs in the applications view and ensure the label on the total number of items is `set`/ `sets`.
- Either explicitly ask a clarifying question, request changes, or approve …

fix: update copy on total number of duplicate sets

---

shared-helpers/src/multiselectQuestions.tsx
sites/partners/src/applications/PaperApplicationForm/sections/FormApplicationData.tsx
sites/partners/src/users/FormUserConfirm.tsx
sites/public/pages/account/edit.tsx
sites/public/pages/applications/contact/address.tsx
sites/public/pages/applications/contact/alternate-contact-contact.tsx
sites/public/pages/applications/contact/alternate-contact-name.tsx
sites/public/pages/applications/contact/alternate-contact-type.tsx
sites/public/pages/applications/contact/name.tsx
sites/public/pages/applications/household/member.tsx
sites/public/pages/applications/review/demographics.tsx
sites/public/pages/create-account.tsx
sites/public/src/ApplicationMultiselectQuestionStep.tsx
ui-components/src/documentation/Utilities.tsx
ui-components/src/forms/DOBField.tsx
ui-components/src/forms/Field.tsx
ui-components/src/forms/FieldGroup.tsx
ui-components/src/forms/PhoneField.tsx
ui-components/src/global/forms.scss
ui-components/src/global/text.scss

This PR addresses #3123 
Renames the `text_caps-spaced` class to have two underscores to match the style of all the other text classes.
Ensure no instances were missed and that the class still comes through. The `Your Name` label on the public create account page is an example usage of the class. …

fix: rename text style class for consistency

---

backend/core/CHANGELOG.md
backend/core/package.json
shared-helpers/CHANGELOG.md
shared-helpers/package.json
sites/partners/CHANGELOG.md
sites/partners/package.json
sites/public/CHANGELOG.md
sites/public/package.json
ui-components/CHANGELOG.md
ui-components/package.json

- @bloom-housing/backend-core@7.0.0
- @bloom-housing/shared-helpers@7.0.0
- @bloom-housing/partners@7.0.0
- @bloom-housing/public@7.0.0
- @bloom-housing/ui-components@7.0.0 …

chore(release): version

---

sites/public/src/ListingView.tsx
ui-components/src/actions/ExpandableText.stories.tsx
ui-components/src/actions/ExpandableText.tsx
ui-components/src/sections/InfoCardGrid.stories.tsx

move styling of more/less button to parent component
#3140
- …

feat(expandablecontent): remove classname from ExpandableContent

---

sites/public/pages/listings.tsx

This PR addresses #3142
The listings page is not getting updated when a listing is added or one is closed. It appears that it is an issue with either netlify or next. Even though the listings page is setup to be a ISR ([Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration)), on build of the public site it does not get recognized. Because of this the listings page is generated once on build and never regenerated. 
This solution is to revert it back to a server side rendered page. Meaning that it will be generated on runtime. This fixes the problem as when a user hits the listings page it will generate it on the server using the latest backend data. 
There are potential downsides to this. The number of calls to the backend …

fix: convert listings to a server rendered page

---

backend/core/src/activity-log/entities/activity-log.entity.ts
backend/core/src/migration/1665762602664-remove-activity-log-user-relationship-on-delete.ts

This PR addresses #3137 
Users are unable to delete users that have done any "activity" such as editing a listing. this is because there is a many to one relationship with the activity_log table. This is fixed by updating the activity_log table `user` column to null on user deletion
In order to test this you'll need to have two accounts. One account you'll need to do an action with (e.g. close a listing) and the other account will be the one to delete the first account.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet …

fix: update activity-log relationship to users for deletion

---

ui-components/__tests__/text/Description.test.tsx
ui-components/src/text/Description.tsx

Add options to allow markup for descriptions and classes
Unit tests added which verify markup comes through and classname is present

Allow markup for descriptions and optional classname

---

backend/core/src/migration/1664882024743-add-thank-you-to-email.ts

This PR addresses #3069 
For some reason there was no `footer.thankYou` translation for core, Ala, and SMC (it was present for SJ). After that PR it should work for all of them. Don't really know if i can test that for Ala and SMC (so i checked if that field is present in database). In Core it works fine.
Create account, check if in confirmation mail footer there is `Thank you` instead of  `footer.thankYou`
- Either explicitly …

feat: add thank you translations to email footer

---

backend/core/package.json
yarn.lock

This resolves an issue on the heroku deployment of the backend. There is a new version of node 14 that was recently released (version `14.21.0`) and for whatever reason it is causing issues with the version of ioredis we use. 
```
error TS2688: Cannot find type definition file for 'ioredis'.
The file is in the program because:
Entry point for implicit type library 'ioredis'
Found 1 error(s).
````
Updating ioredis to the newest version resolves this issue. 
*Note*: this doesn't appear to be reproducible locally, only in the heroku deployment
- …

fix: upgrade ioredis version

---

ui-components/src/overlays/Modal.scss
ui-components/src/overlays/Modal.stories.tsx

This PR addresses #3062
This PR addresses a bug in the [previous PR](https://github.com/bloom-housing/bloom/pull/3153) that targeted this issue, we were not expanding a mobile modal to full screen if it didn't have a footer at all. We don't have this pattern in Bloom but it exists in DAHLIA, I added a new story to track it.
Check out the [new story for a modal with no footer](https://deploy-preview-3163--dev-storybook-bloom.netlify.app/?path=/story/overlays-modal--scrollable-modal-no-footer). Ensure on mobile it takes up the full height of the screen and scrolls.
- …

fix: allow for scrollable modal to have flexible height

---

sites/partners/pages/listings/[id]/applications/pending/index.tsx

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3097)
Exposes the last run date & time of the application flagged set processor to the partner's front end 
Head to partner's site
go to a listing's details page then navigate to the application tab
head to the application tab for pending review
notice at the bottom below the table is a time stamp for the afslastrun  …

feat: adding last run to pending page

---

ui-components/src/blocks/ActionBlock.scss

This PR addresses #3176 
The text wasn't aligned center in the ActionBlock component causing a funky UI on mobile (see screenshot in the issue).
This PR center aligns the text and fixes one inconsistent padding style.
Check out the ActionBlock stories on mobile and ensure the text alignment is centered.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the …

fix: fix text alignment on action block component

---

ui-components/src/blocks/InfoCard.docs.mdx
ui-components/src/blocks/InfoCard.scss
ui-components/src/blocks/InfoCard.stories.tsx
ui-components/src/lists/PreferencesList.docs.mdx
ui-components/src/lists/PreferencesList.scss
ui-components/src/lists/PreferencesList.stories.tsx

Bringing the PreferenceList and InfoCard components into the world of [v2 styling](https://github.com/bloom-housing/bloom/blob/main/docs/Styling2ndGen.md).
Refactored both PreferenceList and InfoCard components using the v2 style guidelines.
Compare storybooks, app instances, and code for any visual or functional regressions. Ensure that the code changes follow the [v2 styling](https://github.com/bloom-housing/bloom/blob/main/docs/Styling2ndGen.md). Check that the new docs are correct.
- Also review the acceptance criteria on the Netlify …

refactor(preferenceslist infocard): v2 style

---

shared-helpers/src/AuthContext.ts

This is a cherry pick for https://github.com/housingbayarea/bloom/pull/561
**testing:**
head over to the public site ( https://hba-public-main.netlify.app/)
attempt to create a new account
get the email
click the confirmation link
you should now be signed in

fix: public site user confirmation issue (#561)

---

backend/core/src/auth/constants.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/2250)
Update to (I think) fix an issue with hosted envs. The issue is that because the hosted envs have different urls for the backend and the front ends (whereas locally we just aim at localhost)
https://stackoverflow.com/questions/59990864/what-is-the-difference-between-samesite-lax-and-samesite-strict?rq=1
is where I got a lot of this info from if anyone else wants to peep
you should be able to log in locally, and when this goes to hosted envs this should work …

fix: update to fix hosted envs

---

shared-helpers/package.json
sites/partners/package.json
sites/public/package.json
sites/public/src/components/listing/ListingView.tsx
yarn.lock

This PR addresses #3225
Modified description in aside for FCFS listings
Go into listing with FCFS it should have different description. For waitlist, and lottery it should stay as it was.
If you have one commit and message, squash. If you need each message to be applied, rebase …

feat: add description for FCFS in listing aside

---

.github/workflows/release_packages.yml
.github/workflows/version_packages.yml
lerna.json
package.json

This PR addresses #3275 
After the failure of release_components.yml on the merge of #3229, a misuse of lerna was exposed in bloom. We only ran yarn version:ui-components and yarn publish:ui-components, but benefited from all packages ["sites/public", "sites/partners", "backend/core", "shared-helpers"] releasing. The commands lerna version and lerna publish apply to all packages within a repository no matter the directory that they are called. This is based on my understanding of this [discussion](https://github.com/lerna/lerna/issues/1055). This PR is meant to clean up the duplicate functionality in our package.json and re-configure the lerna release process to more clearly achieve the same outcome as before.
**Correction**
Based on discussions, this PR removes the publish functionality …

fix: reduce lerna repetition

---

backend/core/test/authz/authz.e2e-spec.ts

This PR addresses #3304
See #3304 for much more context, tl;dr is that this adds a Throttler config that exists in many other e2e tests to avoid the tests getting rate limited.
There are probably a few ways to configure Throttler to not rate limit for tests but I chose to remain consistent with the rest of the e2e tests.
note: I found the tests to super noisy, so I did this change locally to avoid all of the console spam
```git
--- a/backend/core/package.json
+++ b/backend/core/package.json
@@ -28,7 +28,7 @@
"test:watch": "jest --watch",
"test:cov": "jest --coverage",
"test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
-    "test:e2e": "jest --config ./jest-e2e.json --runInBand --forceExit",
+    "test:e2e": "jest --config …
```

fix: fix flaky e2e test (authz.e2e-spec.ts) when run locally via rate limiting

---

shared-helpers/package.json
sites/partners/package.json
sites/public/package.json
sites/public/src/layouts/application.tsx
yarn.lock

This PR addresses #3270 
This is PR takes in the newer version of UI-Components and implements the SiteHeader.tsx's skip link.
1. Navigate to any page on the Bloom public site
2. Press tab
3. The first focusable item should be a skip to main content link
4. Press enter
5. The page should jump past the headers to the central content
6. Pressing enter again will highlight the first focusable item in the main content, skipping over all of the language and header buttons.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet …

fix: add main content id

---

docs/Authentication.md
shared-helpers/src/RequireLogin.tsx

Updates to allowlist/blocklist terminology

docs: update terminology

---

backend/core/src/applications/entities/household-member.entity.ts
backend/core/src/migration/1675104670318-remove-household-member-phone-and-email.ts
backend/core/src/seeder/seeds/applications.ts
backend/core/types/src/backend-swagger.ts

This PR fixes #2130
This is a mergeable version of #3306 (I somehow messed up commit state there... git is hard, esp with forks)
To test this I:
* Ran the migration to make sure there were no errors
* reseeded the DB to make sure that the changes I made to the seed script didn't throw any exceptions (and also made sure that the migration applied cleanly)
* tested making and submitting an application and did some extra CRUD operations around the household members step to make sure that I didn't break anything there.
* clicked around in http://localhost:3100/docs/ to check api doc changes and make sure that I didn't break anything
- Pull the …

Remove unused phone number and email fields from HouseholdMembers

---

shared-helpers/__tests__/testHelpers.ts
sites/partners/__tests__/components/listings/PaperListingForm/sections/DetailUnits.test.tsx
sites/partners/__tests__/pages/settings/index.test.tsx
sites/partners/__tests__/pages/users/index.test.tsx
sites/public/.jest/setup-tests.js
sites/public/__tests__/components/listing/ListingView.test.tsx
sites/public/src/lib/helpers.tsx

This PR closes #3217 by adding a unti test on the ListingView component with the recommended tests.
Mocking all of the appropriate data (e.g. `Jurisidction`, `Listing`) was the primary challenge here. I decided to reuse and extend the existing `testHelpers.ts` data mocks used on the partners side in the public as well by moving that file to the `shared-helpers` folder and importing it from there for both sites.
I also added some stuff that was needed for the tests to work.
Run the new tests, both the new ones and the existing partners tests that I updated (or just check the CI test run which does run the new ListingView test)
- Pull the …

test: add unit tests on the ListingView component

---

backend/core/src/applications/applications.controller.ts
backend/core/src/auth/auth.module.ts
backend/core/src/auth/controllers/user.controller.spec.ts
backend/core/src/auth/controllers/user.controller.ts
backend/core/src/auth/services/user-csv-exporter.service.ts
backend/core/src/shared/query-filter/index.ts
backend/core/types/src/backend-swagger.ts
shared-helpers/src/auth/AuthContext.ts
sites/partners/__tests__/pages/users/index.test.tsx
sites/partners/cypress.json
sites/partners/cypress/integration/06-admin-user-mangement.spec.ts
sites/partners/page_content/locale_overrides/general.json
sites/partners/src/lib/hooks.ts
sites/partners/src/pages/listings/[id]/applications/index.tsx
sites/partners/src/pages/users/index.tsx

This PR addresses #3282 
This adds a new endpoint to the backend that exports all partner users to a csv file. It also adds an "export" button to the users page on the partner site (made the export and add users button the smaller size as well). 
The export includes all of the columns referenced here: https://docs.google.com/spreadsheets/d/1RrYNnkAdG4QPyVBC8yG1svqPaLt0V4qVQMzQgHUEIjY/edit#gid=670984196.
When running this locally and clicking on "export" you should get a csv download with all of the users shown on the users page.
An additional unit and cypress test was also added. …

feat: add user csv export

---

backend/core/src/seeder/seeds/listings/shared.ts
shared-helpers/src/locales/es.json
shared-helpers/src/locales/general.json
shared-helpers/src/locales/tl.json
shared-helpers/src/locales/vi.json
shared-helpers/src/locales/zh.json
shared-helpers/src/views/summaryTables.tsx
sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
sites/partners/src/lib/helpers.ts

This PR addresses [#599](https://github.com/housingbayarea/bloom/issues/599)
This adds an additional bathroom option to the units of "Shared" (0 bathrooms). The additional option is added to the partner unit creation form along with the displaying of "shared" whenever there are 0 bathrooms on the listing details page
Update a listing in partners to have "shared" bathrooms. The change should reflect in the unit features section of the listing details page. …

feat: add shared bathroom option

---

sites/partners/src/lib/helpers.ts
sites/partners/src/lib/listings/CloudinaryUpload.ts

This PR addresses [#98](https://github.com/bloom-housing/ui-components/issues/98)
This PR blocks https://github.com/bloom-housing/ui-components/pull/97
Ensure you can upload a photo on a listing.
If you have one commit and message, squash. If you need each message to be …

refactor: add cloudinary fxn to partners

---

sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx

#3130 -> [this comment](https://github.com/bloom-housing/bloom/issues/3130#issuecomment-1458905105)
Previously addressed was only lottery date / time. This PR adds missing field to submit open house event.
Go to listing in partners -> application process , and create open house event. It should properly display in public site
- Either explicitly ask a clarifying question, request changes, or approve the …

fix: add startDate to open house submit event

---

shared-helpers/package.json
sites/partners/package.json
sites/public/package.json
yarn.lock

This PR addresses [#93](https://github.com/bloom-housing/ui-components/issues/93)
This pulls in the latest changes from ui-components. Including the footer fix and some of the detroit back-pull
All pages can be tested, but the footer should not have stacked links anymore.
If …

fix: update ui-c to latest version

---

backend/core/src/application-flagged-sets/application-flagged-sets-cronjob.service.ts

Removes the dependency on the listing service by pulling the createQueryBuilder code into the afs conjob service. 🤞 that this solves all of the cron job issues and removes the REQUEST scope issues

fix: remove listing service from afs cron job

---

backend/core/src/applications/applications-submission.controller.ts
backend/core/types/src/backend-swagger.ts
shared-helpers/src/locales/es.json
shared-helpers/src/locales/general.json
shared-helpers/src/locales/tl.json
shared-helpers/src/locales/vi.json
shared-helpers/src/locales/zh.json
sites/public/src/components/shared/FormSummaryDetails.tsx
sites/public/src/pages/applications/review/summary.tsx

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3439)
This creates and now uses an application verification endpoint to prevent partially filled out applications from the public site from being submitted
go to public site and begin filling out an application for a listing 
after filling out 1-2 sections skip ahead by changing the url from something like: `/contact/name` to something like `/review/demographics` (the tail end of the url)
fill out the rest of the form till you get to the review application step. Once you have looked it over and verified you are missing data hit the confirm button. An error should be thrown, only the edit button for the beginning of the form and the confirm button at the bottom should be disabled
on the flip side if the application is …

feat: adding app sub verification endpoint

---

backend/core/src/listings/views/config.ts

This PR addresses #3472 
The following two fields are needed by the Doorway team to do front-end filtering:
- units.numBedrooms
- units.numBathrooms
This can be tested by hitting the backend directly with this link. Note you will need to change the jurisdiction id to the one setup in your local db
```
http://localhost:3100/listings?view=base&limit=all&filter[0][$comparison]==&filter[0][jurisdiction]=3faa4429-7754-425b-8f6e-d77ee6d9b178&filter[1][$comparison]==&filter[1][status]=active&orderBy[0]=mostRecentlyPublished&orderDir[0]=DESC
``` …

fix: add additional unit fields to base view

---

sites/partners/cypress/e2e/03-listing.spec.ts

This PR addresses #3448
Since it seems that this issue is more related to our broader state management and approach and useSWR, this PR just serves to add the testing that should've flagged this issue
Seeing that the test passes below or locally.
If you have one commit and …

fix: cypress coverage

---

backend_new/.env.template
backend_new/package.json
backend_new/prisma/seed-helpers/listing-factory.ts
backend_new/src/modules/listing.module.ts
backend_new/src/services/google-translate.service.ts
backend_new/src/services/listing.service.ts
backend_new/src/services/translation.service.ts
backend_new/test/integration/listing.e2e-spec.ts
backend_new/test/unit/services/listing.service.spec.ts
backend_new/test/unit/services/translation.service.spec.ts
backend_new/yarn.lock
package.json

This PR addresses #3496 
Add the translation service to the new Prisma backend. This does not require a controller so it is just the service that translates listings and gets the translations from the DB
This can only be partially tested as the one service endpoint is currently not being used.
Testing the `translateListing` endpoint:
- When running the backend locally, you can hit the get listing endpoint from swagger: http://localhost:3101/api#/listings/retrieve.
- Get a listing id from the db and hit the above endpoint with that listing id and a non-english language (e.g `es`)
- All of the translatable fields on the listing should be translated to the selected language in the output.
- Also these new translations should show up in the `generated_listing_translations` table. If you hit …

Prisma Translation service

---

backend/core/src/applications/applications.controller.ts
backend/core/src/applications/dto/applications-csv-list-query-params.ts
backend/core/src/applications/helpers.ts
backend/core/src/applications/services/application-csv-exporter.service.ts
backend/core/test/lib/format-local-date.spec.ts
backend/core/types/src/backend-swagger.ts
sites/partners/src/components/applications/ApplicationsColDefs.ts
sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx
sites/partners/src/components/flags/applicationsCols.tsx
sites/partners/src/lib/helpers.ts
sites/partners/src/lib/hooks.ts
sites/partners/src/pages/application/[id]/applicationsCols.tsx

This PR addresses #3518 
For this fix, I followed the pattern established by this [Detroit PR](https://github.com/CityOfDetroit/bloom/pull/1612) so that the UTC time would be converted to the exporters local timezone. Only additional changes, made in relation to manual-entry paper applications where the timing is manually entered and isn't affected by timezone adjustments of the db so the previous logic is maintained for those pieces. 
The most challenging component to the PR proved to be the replicating the DB's responses and time storage locally. Despite changing my databases timezone to UTC, I could not repeat this issue locally. However, the two screenshots below outline the DB responses seen on dev and I **added testing that directly mirrors these responses** to demonstrate this …

fix: timezone adjustment

---

backend/core/src/application-flagged-sets/application-flagged-sets-cronjob.service.ts

Pulls over the bug fix for #3517 from HBA. 
How to test:
Testing options are listed in the how to test section of [#625](https://github.com/housingbayarea/bloom/pull/625)

fix: add check in afs for null email (#625)

---

backend/core/src/auth/services/user.service.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3537)
There is a higher than expected volume of errors coming from the confirm user endpoint. This is to add a bit more logging to get more context as to why this is happening
We don't really know how this error is popping up, but hopefully this logging helps us track it down 
- Either explicitly ask a clarifying question, request changes, or approve the PR …

fix: adding more logging to user confirm()

---

shared-helpers/src/locales/es.json
shared-helpers/src/locales/general.json
shared-helpers/src/locales/tl.json
shared-helpers/src/locales/vi.json
shared-helpers/src/locales/zh.json

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3544)
We were missing the password too weak error message on the change password page of the public site. This adds this error message that was missing
create a public user (or use an existing user)
go through the reset password work flow
enter a password that would be too weak `abcdef` for example, you should now get a translated error message
- Either …

fix: adds missing translation

---

sites/public/src/pages/applications/household/member.tsx

This PR addresses #3525
There were 2 issues. 
- First was that delete button also triggered form submission (so it re-created just deleted member).
- other was with `orderID` that could be the same for few items. For example when having 3 items with `orderID` [1,2,3] and remove middle one, and then add another one, will result with ids [1,2,2]. So now i rearrange `orderID` on item remove
Start application -> in `household` section select `other people will live with me` -> after adding household member it should be possible to remove it. 
Check for few members and if `add member` works correctly after delete was performed.
Check if whole workflow still works.
- Review the code itself from a …

fix: delete household member in application

---

sites/partners/page_content/locale_overrides/general.json
sites/partners/src/components/listings/ListingFormActions.tsx
sites/partners/src/components/listings/PaperListingForm/index.tsx

This PR addresses [#307](https://github.com/metrotranscom/doorway/issues/307)
* Note this branch is branched off of [another PR currently up for review](https://github.com/bloom-housing/bloom/pull/3597) that updates the latest Tag component from seeds.
When listings approval is on:
* When a partner submits a listing for approval, they get a modal asking them to confirm. When submitted, the status of the listing changes to pending approval.
Ensure if you have the environment variable on that as a partner/jurisdictional admin when you create a draft listing and submit it for approval that a modal pops that matches the designs. On submit the status should change to pending approval.
- Review the …

feat: submit for approval flow

---

backend/core/.env.template
backend/core/src/app.module.ts

This PR addresses #3468
We currently have an issue where applications aren't working on deploy previews as a result of a change to how we are allow-listing URLs. The issue is that our deploy preview URLs change every time, so our static allowlist doesn't work. This is a simple change to just remove that check in non-prod environments.
Tricky to test locally, but there's a new environment variable in the backend that takes in an array of regex expressions that will also be checked against the origin. In netlify environments we can set expressions like `https://deploy-preview-[A-Za-z0-9]+--bloom-exygy-dev\.netlify\.app/` to allow for the deploy previews to fully work.
- Review the code itself …

fix: cors origin deploy preview issues

---

backend/core/src/listings/db/listing-query-builder.ts

This PR addresses https://github.com/metrotranscom/doorway/issues/322
Updates the sort order of the table in partners to have pending review + changes requested precede the existing order.
You'll need to start the app locally and have the flag on to ensure the statuses are now sorted as described in the issue.
(The closed ones are on the last page)
- Either explicitly ask a clarifying question, request changes, or approve the PR …

fix: sort table with listings approval statuses

---

shared-helpers/package.json
sites/partners/package.json
sites/public/package.json
yarn.lock

This PR addresses #3630
Gets change from ui-c that will hide empty due date section
it was tested in this [PR](https://github.com/bloom-housing/ui-components/pull/122)

chore: upgrade ui-c to 12.0.21

---

sites/partners/__tests__/pages/listings/index.test.tsx
sites/partners/__tests__/pages/users/index.test.tsx
sites/partners/page_content/locale_overrides/general.json
sites/partners/src/pages/index.tsx
sites/partners/src/pages/listings/[id]/applications/index.tsx
sites/partners/src/pages/users/index.tsx

This PR addresses #3649
Changes the error message when an export fails to remove the email.
Turn off network connection when attempting to export to confirm the new error message text.
I'm not sure what environment the screenshot is from because in core it's the darker alert, so it's the darker alert here as well / no changes made there.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there …

fix: remove email from export error

---

backend/core/src/applications/applications.controller.ts
backend/core/src/applications/services/applications.service.ts
backend/core/src/email/email.service.ts
backend/core/src/migration/1696353656895-csv-export-translations.ts
backend/core/src/shared/views/csv-export.hbs
backend/core/test/applications/applications.e2e-spec.ts
backend/core/types/src/backend-swagger.ts
sites/partners/page_content/locale_overrides/general.json
sites/partners/src/lib/hooks.ts
sites/partners/src/pages/listings/[id]/applications/index.tsx

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3610)
This changes the application export to be emailed instead of sent directly to the front end to be downloaded
there is a new migration so you'll have to reseed or run the new migration
log in to the partner site
navigate to a listing with applications
head to the applications tab
click the export button
the toast at the top right should inform you that an email was sent to the logged in user's email
the email should match the screenshot in the ticket and come with an attached csv of the application data …

feat: application export now emailed

---

sites/partners/src/components/users/FormUserManage.tsx

This PR addresses #3667 
Sorts listings in user creation page.
This can be tested by going  to create a partner user and changing jurisdictions to see that all listing assignment options display in alphabetical order.
If you have one commit and message, squash. If you need each …

fix: alphabetical listing order

---

backend/core/src/applications/applications.controller.ts
backend/core/src/applications/services/applications.service.ts
backend/core/test/applications/applications.e2e-spec.ts
backend/core/test/authz/authz.e2e-spec.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3683)
This changes it so that the application csv export returns immediately, and the work of building the csv is done in a non-blocking way
Log in and head to a listing
head to that listing's applications
export
you should get a toast pretty much instantly saying there was a success, and the email should be sent to the email of the user that logged in
- …

fix: email is sent async and response is immediate

---

backend_new/README.md
backend_new/package.json
backend_new/src/decorators/permission-action.decorator.ts
backend_new/src/decorators/permission-type.decorator.ts
backend_new/src/enums/permissions/http-method-to-actions-enum.ts
backend_new/src/enums/permissions/permission-actions-enum.ts
backend_new/src/enums/permissions/user-role-enum.ts
backend_new/src/guards/permission.guard.ts
backend_new/src/guards/user-profile-permission-guard.ts
backend_new/src/interceptors/activity-log.interceptor.ts
backend_new/src/modules/auth.module.ts
backend_new/src/permission-configs/permission_model.conf
backend_new/src/permission-configs/permission_policy.csv
backend_new/src/services/permission.service.ts
backend_new/src/utilities/deep-find.ts
backend_new/test/unit/services/permission.service.spec.ts
backend_new/test/unit/utilities/deep-find.spec.ts
backend_new/yarn.lock
sites/partners/package.json
sites/public/package.json

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3445)
This adds the permissioning service and guards that we'll be applying throughout the application in a follow up pr
Tests were added for the service, but for now there isn't a way to directly test these, that will be added in a follow on pr 
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining …

feat: prisma permission guards and service

---

backend_new/prisma/migrations/20230626231609_init/migration.sql
backend_new/prisma/schema.prisma
backend_new/prisma/seed-helpers/jurisdiction-factory.ts
backend_new/prisma/seed-helpers/translation-factory.ts
backend_new/prisma/seed-helpers/user-factory.ts
backend_new/prisma/seed-staging.ts
backend_new/src/controllers/listing.controller.ts
backend_new/src/controllers/user.controller.ts
backend_new/src/enums/users/user-role-enum.ts
backend_new/src/modules/listing.module.ts
backend_new/src/services/email.service.ts
backend_new/src/services/listing.service.ts
backend_new/src/validation-pipes/listing-create-update-pipe.ts
backend_new/src/views/changes-requested.hbs
backend_new/src/views/listing-approved.hbs
backend_new/src/views/request-approval.hbs
backend_new/test/integration/listing.e2e-spec.ts
backend_new/test/unit/services/email.service.spec.ts
backend_new/test/unit/services/listing.service.spec.ts
shared-helpers/src/types/backend-swagger.ts

This pulls in the listing approval backend changes from the old backend into the new one. This adds all of the logic to know when to set the new statuses along with creating and send the new emails when applicable.
Unit and e2e tests have been added. But it is recommended to simulate the listing flow using the api endpoints.
The following steps can be done on http://localhost:3101/api after running a reseed of the new backend
Create an admin user - `/user/invite`(change the name and email to the appropriate values along with the jurisdiction id to the one in your prisma db locally
```
{"firstName":"morgan","lastName":"ludtke","email":"morgan.ludtke@exygy.com","roles":{"isAdmin":true,"isPartner":false,"isJurisdictionalAdmin":false},"leasingAgentInListings":[],"juris …
```

fix: listing approval changes

---

sites/partners/src/components/listings/PaperListingForm/sections/ListingIntro.tsx

fix: grid fix for listing intro

---

backend_new/prisma/seed-helpers/translation-factory.ts
backend_new/src/controllers/user.controller.ts
backend_new/src/services/email.service.ts
backend_new/src/services/user.service.ts
backend_new/src/utilities/csv-builder.ts
backend_new/src/views/csv-export.hbs
backend_new/test/integration/user.e2e-spec.ts
backend_new/test/unit/services/email.service.spec.ts
backend_new/test/unit/services/user.service.spec.ts
backend_new/test/unit/utilities/csv-builder.spec.ts
shared-helpers/src/types/backend-swagger.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3695)
This creates an endpoint for getting a csv export of users 
As per convo with Sarah we converted this to send the csv as an email
Unit and E2E tests were added, but you can also use http://localhost:3101/api/ to test further
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the …

feat: csv export for users

---

backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
backend/core/src/migration/1699916046696-enable-geocoding-flag.ts
backend/core/src/seeder/seeds/jurisdictions.ts
backend/core/test/jurisdictions/jurisdictions.e2e-spec.ts
backend/core/types/src/backend-swagger.ts
shared-helpers/__tests__/testHelpers.ts
sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
sites/partners/__tests__/pages/settings/index.test.tsx
sites/partners/src/components/settings/PreferenceDrawer.tsx

This PR addresses #3702 
The geocoding feature should not be released yet so we want to have it behind a feature flag.
Also there is a grid problem with the page. This is partially fixed with this PR
Some additional unit tests have been added
turn on the new feature flag in the jurisdiction table
```
UPDATE jurisdictions
SET enable_geocoding_preferences = TRUE
where id = (select id from jurisdictions where name = 'Alameda')
``` …

fix: add feature flag for geocoding

---

sites/partners/src/lib/users/signInHelpers.ts

This PR addresses #3681
Izzie was able to get a view into how this error was happening for users and what is a likely culprit is an additional space when copying the mfa code from an email. This PR trims the inputted data so that extra whitespace is not considered when validating the code
1. Create a partner account with MFA enabled. 
2. Log in with username and password
3. get the MFA code via email and put it in with additional whitespace
4. You should be able to login
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet …

fix: trim mfaCode on submit

---

sites/partners/tailwind.config.js
sites/public/tailwind.config.js

This PR addresses #3659 
Due to an object spread, the ui-components Tailwind config which had `purge` `enabled` set to `false` was overwriting the two config files in the Next.js apps. This fixes those configs so that purges can happen in production for vastly smaller CSS bundle sizes.
Verify the size of the primary CSS bundle, and verify the purge didn't cause any obvious styling bugs (admittedly hard to tell with 100% coverage of the applications).
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend …

fix: re-enable CSS purging to minimize Tailwind bundles

---

sites/public/src/pages/applications/contact/address.tsx

This PR addresses #3744
A regression in the application removed padding on the address verification page.
Ensure there's padding on the address verification page (for the main applicant address).
If you have one commit and message, squash. If you need each message to be …

fix: padding issue on address verify

---

sites/partners/next.config.js
sites/public/.env.template
sites/public/next.config.js

https://github.com/bloom-housing/bloom/issues/3752
This PR addresses #3752 
Adding a feature toggle for the Mandated Accounts feature
on localhost: 
- add the env variable: `SHOW_MANDATED_ACCOUNTS` to you `.env' to bloom/public
- run the app
- You can make a local code change that relies on the flag, for example you could log out `process.env.showMandatedAccounts && 'hello world'`
- Did the above review instructions
- @emilyjablonski are there any unit or e2e tests we can add for this? …

feat: MA-3752 add SHOW_MANDATED_ACCOUNTS flag

---

shared-helpers/src/views/forgot-password/FormForgotPassword.tsx

This PR addresses #3792 
The new seeds button needed its type to be defined as submit to trigger the email.
This can be tested by creating an account on the public or partners side that uses your email and then follow the forgot password flow.
If you have one commit and …

fix: update seeds button

---

sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx

This PR addresses #3774 
This work was originally done in [hba](https://github.com/housingbayarea/bloom/pull/655) but per support discussion, it's brought back into core 
on the partner's site -> create/edit listing page -> unit form the language should now clarify that its minimum monthly income …

fix: update labeling

---

backend/core/src/listings/listings.service.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3794)
As it currently stands when a listing is created, the listing isn't automatically added to the cache, instead the listing has to wait to be picked up by the cronjob or a user can update the listing to get the listing in the cache faster
this pr changes this so that the listing is auto added to the cache on created
create a listing
check the preview link, it should like to a listing and not throw an error
- Also review the acceptance criteria on the Netlify deploy preview (noting that these …

fix: on listing create, add to cache

---

backend_new/prisma/migrations/20231030230627_init/migration.sql
backend_new/prisma/schema.prisma
backend_new/prisma/seed-helpers/application-factory.ts
backend_new/prisma/seed-helpers/listing-factory.ts
backend_new/prisma/seed-staging.ts
backend_new/src/dtos/applications/application.dto.ts
backend_new/src/services/application-flagged-set.service.ts
backend_new/src/services/application.service.ts
backend_new/src/utilities/build-order-by.ts
backend_new/src/utilities/cron-job-starter.ts
backend_new/test/integration/application-flagged-set.e2e-spec.ts
backend_new/test/unit/services/application-flagged-set.service.spec.ts
backend_new/test/unit/services/application.service.spec.ts
shared-helpers/src/auth/AuthContext.ts
sites/partners/cypress/e2e/default/02-mfa.spec.ts
sites/partners/cypress/e2e/default/04-application.spec.ts
sites/partners/next.config.js
sites/partners/package.json
sites/partners/src/components/applications/ApplicationsColDefs.ts
sites/partners/src/components/applications/PaperApplicationDetails/DetailsAddressColumns.tsx
sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsAlternateContact.tsx
sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdDetails.tsx
sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
sites/partners/src/lib/applications/formatApplicationData.ts
sites/partners/src/pages/application/[id]/review.tsx
sites/partners/src/pages/listings/[id]/applications/pending/index.tsx
sites/public/next.config.js
sites/public/package.json
sites/public/src/pages/applications/contact/address.tsx

This PR addresses #3725 
This is the second of two PR for #3725, it does the remaining steps to get the listing application page on the partner site working.
It includes the view applications for a listing along with the the application flag set flow (seeing and resolving duplicates).
*NOTES*: 
- this does not have the application csv export functionality since that is dependent on #3771 
- There are issues with the layout of some buttons/links that are tied to the recent seed changes. Those have not been address as part of this
After reseeding the new backend and starting up both the new backend and partner site you can test the following pages and functionality:
- http://localhost:3001/listings/{listingId}/applications
- http://localhost:3001/application/{applicationId}
- …

fix: partner listings applications

---

backend_new/src/controllers/application.controller.ts
backend_new/src/services/application-csv-export.service.ts
backend_new/test/unit/services/application-csv-export.service.spec.ts
backend_new/test/unit/services/application.service.spec.ts
backend_new/test/unit/services/multiselect-question.service.spec.ts

Adds additional test coverage to the existing application export PR (without any lottery changes)

test: add additional test cov

---

backend_new/src/passports/mfa.strategy.ts
backend_new/src/permission-configs/permission_policy.csv
backend_new/test/integration/permission-tests/permission-as-public.e2e-spec.ts
backend_new/test/unit/passports/mfa.strategy.spec.ts

This PR fixes 2 overall issues we found in prisma bug bash:
1. User permissioning issues
a. users with the partner role were unable to accept the terms
b. public site users (users without a role) were unable to modify their user data
2. Some users were able to enter the wrong password but the correct email address and end up logging in instead of being locked out 
invite a user to the partner site, give them the partner role. As that user attempt to log in, you should now be able to log in
create a user on the public site. As that user you should be able to edit yourself via the public site
create or use an existing user. In the db change their lastLoginAt date to something well in the past (01/01/2024 works for example). Incorrectly enter the user's password when attempting to log in. …

fix: perm and login fixes

---

sites/partners/src/components/users/FormSignInAddPhone.tsx
sites/partners/src/components/users/FormSignInMFAType.tsx

This PR addresses #3837 
With the change to the seeds button all submission buttons need to have `type="submit"`. This was added in most places, but was missed in the SMS MFA flow. For this PR it was added for both the add phone button and the "verify by phone" button.
Create an account that has MFA enabled. Log in with that account and choose "verify by phone". …

fix: add submit to sms mfa flow

---

sites/public/src/components/account/AccountCard.module.scss

This PR is a follow-up #3791 
Resolves a bug that removed the divider width for the account card
See that that divider is still present on account settings page and application page
If you have one commit and message, squash. If you need each message to be applied, rebase and …

fix: add divider width

---

sites/partners/package.json
sites/public/package.json
yarn.lock

Our public and partner sites recently started showing "internal server error" when loading specific pages in netlify. For example https://bloom.exygy.dev/listings. This is only happening on deployed version in Netlify. The issue appeared to have happened in the past depending on what node version you were on, however in the last few days people were reporting that it is related to a version of the netlify plugin. This PR updates it to the latest.
This cannot be tested locally. However, a version of this branch was deployed to [bloom.exygy.dev](https://bloom.exygy.dev) and the page began to work again. 
- Pull the changes down locally and test …

fix: upgrade netlify plugin

---

backend_new/package.json
backend_new/prisma/seed-staging.ts
backend_new/src/controllers/application.controller.ts
backend_new/src/controllers/listing.controller.ts
backend_new/src/dtos/listings/listing-csv-query-params.dto.ts
backend_new/src/enums/listings/review-order-enum.ts
backend_new/src/enums/listings/view-enum.ts
backend_new/src/modules/listing.module.ts
backend_new/src/services/application-csv-export.service.ts
backend_new/src/services/listing-csv-export.service.ts
backend_new/src/services/listing.service.ts
backend_new/src/types/CsvExportInterface.ts
backend_new/src/utilities/format-local-date.ts
backend_new/src/utilities/is-empty.ts
backend_new/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
backend_new/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
backend_new/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
backend_new/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
backend_new/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
backend_new/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
backend_new/test/integration/permission-tests/permission-as-public.e2e-spec.ts
backend_new/test/jest-with-coverage.config.js
backend_new/test/unit/services/application-csv-export.service.spec.ts
backend_new/yarn.lock
package.json
shared-helpers/src/types/backend-swagger.ts
sites/partners/src/lib/hooks.ts
sites/partners/src/pages/api/adapter/[...backendUrl].ts
sites/partners/src/pages/index.tsx

This PR addresses #3732 
This PR adds the listings csv export functionality to the backend. It is a complete rewrite from the old csv export functionality. This first writes the listings and units csvs and then archives them before sending as the response. It is a branch of https://github.com/bloom-housing/bloom/pull/3771, so if you haven't reviewed that, please do so first.
That PR doesn't actually zip up the file, so we may want to update that to get the file size even smaller, like here.
Updates for access control need to added as well as tests.
1. pull down this branch
2. there are new dependencies, so please run `yarn`
3. open up "backend_new/prisma/constants.ts" and edit to your desired seed number, for testing this
4. `cd backend_new`, seed the db with `yarn setup:dev` and start …

Listings CSV

---

sites/public/src/components/applications/ApplicationMultiselectQuestionStep.tsx

This PR addresses #3834
moves preference url to desired position
make sure you have preference with link on application.
Go to preference step in application => it should display url in correct position.
Make sure it looks without link / description etc.
If you have one commit …

fix: move preference url below preference description

---

shared-helpers/__tests__/views/multiselectQuestions.test.ts
shared-helpers/src/views/multiselectQuestions.tsx
sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
sites/public/src/components/shared/FormSummaryDetails.tsx
sites/public/src/lib/helpers.tsx

Pulls over [this HBA PR](https://github.com/housingbayarea/bloom/pull/660)

fix: foreign language in export

---

backend/core/.env.template
backend/core/src/auth/services/user.service.ts
backend/core/src/email/email.service.ts
backend/core/src/shared/utils/get-public-email-url.ts
shared-helpers/src/auth/AuthContext.ts
shared-helpers/src/utilities/getListingRedirectUrl.ts
shared-helpers/src/views/sign-in/FormSignIn.tsx
sites/public/src/components/account/ConfirmationModal.tsx
sites/public/src/pages/applications/start/choose-language.tsx
sites/public/src/pages/create-account.tsx
sites/public/src/pages/forgot-password.tsx
sites/public/src/pages/reset-password.tsx

#3760 #3756
- Redirect after Create Account Confirmation Email
- Redirect after Create Account Resend Confirmation Email
- Redirect after Create Account Timeout
- Redirect after Forget Password Email
- Redirect after Forget Password Timeout
- Edited TypeORM email service
Toggle SHOW_MANDATED_ACCOUNTS var to true
- As a signed out user, do the following:
- Go to a listing, click apply online, create an account, go to email, click link, and then you should be redirected to application
- Do the same, but this time hit the 'Resend Confirmation" button in the modal, should work
- Then if …

feat: 3760/redirect to application

---

api/src/controllers/listing.controller.ts
api/src/services/listing.service.ts
api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
shared-helpers/src/types/backend-swagger.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3779)
This creates a new endpoint on the listing controller, this takes in the same arguments as the normal get listing by id endpoint, but instead of returning a Listing (typed) it returns a version that is typed for the typeorm version and returned as a json obj
The easiest way to test this piece in particular is to hit the localhost://3101/api site and tests the new external listing endpoint then double check that the data matches up with what you would expect given the typeorm typing
- Also …

feat: external listing endpoint

---

api/prisma/migrations/03_mfa_code_to_single_use_code/migration.sql
api/prisma/migrations/04_allow_single_use_code_login_jurisdiction_flag/migration.sql
api/prisma/schema.prisma
api/prisma/seed-helpers/user-factory.ts
api/prisma/seed-staging.ts
api/src/dtos/jurisdictions/jurisdiction.dto.ts
api/src/passports/mfa.strategy.ts
api/src/services/auth.service.ts
api/src/services/email.service.ts
api/src/services/sms.service.ts
api/test/integration/auth.e2e-spec.ts
api/test/integration/jurisdiction.e2e-spec.ts
api/test/integration/permission-tests/helpers.ts
api/test/unit/passports/mfa.strategy.spec.ts
api/test/unit/services/auth.service.spec.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3898)
This changes the prisma schema for the jurisdiction table to have a new boolean flag 
and changes the user_accounts table for mfa_code -> single_use_code
as per the tech doc: https://docs.google.com/document/d/18DuWgsrZszJCO90knNSQ4yXj7fvwzZ9ZvHmV0rGe2nk/edit#heading=h.7pkgraqutwu2
e2e and unit tests were updated so you can run those locally
attempt to log in to the partner site as an mfa enabled user
attempt to log in to the public site as a non mfa user …

fix: 3898/passwordless schema changes

---

api/src/services/user.service.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3931)
updates user creation and user update around userRoles
a non-admin user should be able to update a user, but attempted changes to the target user's roles will not take
if a partner user in jurisdiction A, and a jurisdictional admin attempts to create a partner with the same email as the partner user in jurisdiction B that user should just be added to jurisdiction B 
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes …

fix: user update/create fixes

---

sites/public/tailwind.config.js

This PR addresses #422 previously made here: https://github.com/metrotranscom/doorway/pull/479 but needs to be in hba and core
This is a follow-up which supports tailwind loading from the Account Card in shared helpers.
This can be tested by running yarn build / yarn start in sites/public and the sign-in page styling should show as expected. Specifically, there should be margin around the create account header and buttons on the sign-in page
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes …

fix: load shared helpers tailwind

---

api/src/services/email.service.ts
api/src/services/listing.service.ts
api/test/integration/listing.e2e-spec.ts
api/test/unit/services/email.service.spec.ts
api/test/unit/services/listing.service.spec.ts

This PR addresses - found issue during doorway bug bash
The changes requested email is not properly getting sent because we are sending the wrong parameters to the email service function. This issue was solved in the old backend but missed in the migration to Prisma
Testing the full flow of the Listing approval. But specifically the step of an admin requesting changes to a submitted listing …

fix: update to correct juris on change requested

---

api/src/services/application-flagged-set.service.ts
api/test/unit/services/application-flagged-set.service.spec.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3954)
We forgot to add pagination to afs this does that
Create a listing (or use a listing that exists)
add some applications that would be afs
let the job run (or force the job to run)
make sure the listing's application tab loads, make sure you can open the afs tab
- Either explicitly ask a clarifying question, request changes, or approve the PR if there …

fix: afs needs to be paginating

---

api/src/services/application.service.ts

This pulls across a hotfix into hba for core

fix: Application perm hotfix (#680)

---

api/src/guards/throttler.guard.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3950)
this changes the logging at bit more to see if I can get the original IP instead of the proxy ip

fix: Proxy attempt3

---

api/src/guards/throttler.guard.ts
sites/partners/src/pages/api/adapter/[...backendUrl].ts
sites/public/src/pages/api/adapter/[...backendUrl].ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3950)
This puts the final touches on rate limiting, sets up ip forwarding on partners and public nextjs api so we correctly lock ips that are abusing our system
You can't really test this locally, only want to really test this is is to test in a hosted env
you can throttle yourself locally if your throttle limit is low and you make enough api requests but this fixes stuff in the various proxy layers we have so that side of things is impossible to test locally  …

feat: Throttle update for proxy

---

api/src/services/application-csv-export.service.ts
api/src/services/application.service.ts
api/test/unit/services/application.service.spec.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3935)
We currently have a few problems with application export, this fixes the one that can bring down our api.
What was happening was an application on a listing sufficiently large (Ancora Place on HBA prod) caused the memory usage of the api to spike. This cuts it down pretty significantly. See: https://docs.google.com/spreadsheets/d/1skQA1nS5473r19VJAKxmjWbgS53Fz9bPPYGi7-Ofkos/edit?usp=sharing 
for some examples when ran locally for memory usage
If you use the seed data, you shouldn't notice any difference, if you pull down prod backup, and run this against Ancora Place while monitoring your memory usage, you should see your memory usage spike but it should stay under a 200MB spike basically  …

feat: better memory management on app export

---

sites/public/src/pages/applications/contact/address.tsx

This PR addresses #3973
In the prisma changeover, the applicant.workAddress value was changed to applicant.applicantWorkAddress but the field names and associated errors in address.tsx had not been updated so the address wasn't being saved correctly.
Apply to a listing, indicate "yes" to the work in county, fill out the work address, complete the application, see the work address on the application summary page, submit, see that the work address successfully saved on the partner's side.
- Also review the acceptance criteria on the Netlify deploy preview (noting that …

fix: update naming to applicantWorkAddress

---

sites/partners/src/pages/listings/[id]/applications/index.tsx

This PR addresses https://github.com/metrotranscom/doorway/issues/534
Jurisdictional admins should always be able to see demographic information on application exports.
Sign in to a jurisdictional admin account. Navigate to a listing with applications. Click "Export" on the applications tab. Open CSV file and confirm the demographic columns appear (the most right columns). 
Ran frontend partner cypress and unit tests. …

fix: juris admin demographics

---

api/src/controllers/app.controller.ts
api/src/services/app.service.ts
shared-helpers/src/types/backend-swagger.ts

feat: a cuppa

---

api/src/services/application-csv-export.service.ts
api/test/unit/services/application-csv-export.service.spec.ts
api/test/unit/services/application.service.spec.ts

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3935)
This should speed up the time to get an application export pretty significantly. 
This should also keep our memory footprint lower than it used to be (in line with the recent change for better memory management)
- Easiest way to check this is to use a listing with >9k applications tied to it
- request an application export for that listing
- you should notice the export shows up much faster and importantly the data in that csv **should **not** have changed
- you should also see the memory footprint remain low (around 200MB on my machine locally)
- Pull the changes …

fix: cuts time to get an app export

---

sites/partners/cypress.config.ts
sites/public/cypress.config.ts

Adds flag to turn on Run All button for Cypress spec tests. Speeds up dev QA work.
https://docs.cypress.io/guides/references/experiments#End-to-End-Testing
Run yarn test in either public or private. Confirm "Run %{numberOfTests}} specs" is present next to E2E specs. Click and watch all tests run.
Tested public and private Cypress test suites.
- Also review the acceptance criteria on the Netlify deploy preview (noting that …

test: Add Run All button to Cypress

---

api/src/decorators/hasHttps.decorator.ts
api/src/dtos/application-methods/application-method.dto.ts
api/src/dtos/listings/listing-event.dto.ts
api/src/dtos/listings/listing.dto.ts
api/src/dtos/multiselect-questions/multiselect-link.dto.ts
api/test/integration/listing.e2e-spec.ts
api/test/integration/multiselect-question.e2e-spec.ts
api/test/integration/permission-tests/helpers.ts
api/test/unit/services/listing.service.spec.ts

This PR addresses #3972 
Adds backend url validation for URL fields. It should only affect listing create / edit as rest uses frontend validation, so it probably won't make into backend validation. But make sure they still work.
There is an issue with `buildingSelectionCriteria` when it sends some redundant fields when we manually remove url (so edit, and remove link and click save) it works fine on delete click tho.
Create / edit listing with digital application -> put invalid url into custom url field (without protocol and / or invalid). On submit it should populate error for it.
make sure rest fields are working:
- listing create -> open House (to disable FE validation OpenHouseForm.tsx -> comment out `type='url'` line 154)
- settings -> preference url and option url ( to disable FE …

fix: add backend url validation

---

api/src/services/application.service.ts

This PR addresses #4060 
Previously, the dto was being passed which doesn't include the confirmationCode. Passing the mappedApplication resolves this.
This can be tested by filling out an application with an email and ensuring the application confirmation email comes through correctly with a confirmation code.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes …

fix: pass mappedApplication

---

api/src/permission-configs/permission_policy.csv

jurisdictionAdmin permissions for unitType, unitRentType and unitAccessibilityPriorityType were not properly set. Set all to read.
Create a listing as a jurisdictional admin.
Api and partner site test suites were run and passed.
- Either …

fix: Correct JurisdictionAdmin Perm Policy Misalignment

---

api/src/controllers/listing.controller.ts
api/test/integration/api-key-guard.e2e-spec.ts

removes API pass key from listing read endpoints

fix: reading a listing shouldn't be protected

---

api/prisma/migrations/20240520173759_application_user_id_index/migration.sql
api/prisma/schema.prisma

This PR addresses (Something Yazeed did)
This creates a new index on application to speed up reading applications by their user_id (this happens primarily on the public site looking at a user's application list
Make sure a public user can see their applications
make sure a user can submit an application, then use that application to autofill in the next application
make sure a partner can view applications and make sure they can submit a paper application …

feat: new application index on user_id

---

api/prisma/migrations/12_add_script_runner_translations/migration.sql
api/src/services/email.service.ts
api/src/views/script-runner.hbs

Email translations and template for script runner to use to send emails to Fremont Families applicants.
Language translations done using google translate.
I tested by replacing this [call](https://github.com/bloom-housing/bloom/blob/main/api/src/services/application.service.ts#L662-L666) with a call to the new email service function and completing an application. …

feat: Fremont Familes Email Template for Script Runner

---

api/prisma/seed-helpers/translation-factory.ts
api/src/controllers/script-runner.controller.ts
api/src/dtos/script-runner/bulk-application-resend.dto.ts
api/src/modules/script-runner.module.ts
api/src/services/script-runner.service.ts
api/test/unit/services/script-runner.service.spec.ts
shared-helpers/src/types/backend-swagger.ts

This connects the script runner to the bulk application resend email server
log in to partners site as an admin user, 
pick a listing, create an applicant with first name, last name, middle name, and email filled in 
head to localhost:3101/api or localhost:3100/api use the new script runner end point, inputting the listing id you added that applicant to
you should get an email (assuming you put your email in) 
- Either …

feat: bulk app resend script runner

---

shared-helpers/src/utilities/formKeys.ts
sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx
sites/public/src/pages/applications/review/demographics.tsx

This PR addresses [#issue](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/628)
Currently there are two issues with the rendering of the race field options. First, if the user selects an option with suboptions, selects another option with suboptions and then deselects a top level option, but sets of sublevel options will close and remove selections/inputs. Secondly, specific to the public flow, if the user selects race options, hits the next button, then hits the back button, the original selections are not shown.
To fix both of these problems, the useMemo dependency array needed to be reduced to just the register.
Flow 1: Go through public site online application flow
Flow 1a: Select `Asian`, select a …

fix: Demographics Race Field Render Issue

---

docs/pull_request_template.md

This PR addresses #(insert-number-here)
Please include a summary of the change and which issue(s) is addressed.
------------------------------
The above is the updated template. I removed some outdated information, and then generally tried to make it smaller, and to make the checklist more …

docs: updated pr template

---

sites/public/src/pages/applications/contact/address.tsx
sites/public/src/pages/applications/household/member.tsx

fix: use the correct error keys for State and Zip

---

api/prisma/seed-dev.ts
api/prisma/seed-helpers/translation-factory.ts
api/src/controllers/script-runner.controller.ts
api/src/services/email.service.ts
api/src/services/listing.service.ts
api/src/services/script-runner.service.ts
api/src/views/lottery-published-admin.hbs
api/src/views/lottery-published-applicant.hbs
api/src/views/lottery-released.hbs
api/src/views/partials/header.hbs
api/test/integration/listing.e2e-spec.ts
api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
api/test/unit/services/email.service.spec.ts
api/test/unit/services/listing.service.spec.ts
api/test/unit/services/script-runner.service.spec.ts
shared-helpers/src/types/backend-swagger.ts
sites/partners/__tests__/pages/listings/lottery.test.tsx

This PR addresses #4161
Adds an email notification when a lottery is released to partners. It should send to everyone w access to the listing.
Re-seed the database to get the new translations, in other environments we will use the script runner. Add a partner user with your email and add them to a closed listing that has a lottery. Additionally, update an application to have one of your emails. As an admin, run and release the lottery. Ensure the partner receives the lottery released email. Login as the partner user, and publish the lottery. Ensure the partner receives the lottery published email and the applicant receives their version of the lottery published email.
Copy lives [here](https://docs.google.com/document/d/130OuxoQnKnukoVr_SPQq57A0JZ4vycdcS9q0EX2Gkso/edit#heading=h.l124kyiwnb …

feat: lottery released email

---

sites/public/src/components/account/StatusItemWrapper.tsx

This PR addresses #4248 
Followup from merge issues.
Ensure build works.

fix: build resolution

---

api/src/controllers/application.controller.ts
api/src/dtos/applications/public-apps-filtered.dto.ts
api/src/dtos/applications/public-apps-view-response.dto.ts
shared-helpers/src/types/backend-swagger.ts

This PR addresses #4248 
This is another follow up since the flaws in my mapTo function was preventing data from coming through to the FE.
This can be tested by signing into the public side, applying to a listing, going to the my applications page, finding the publicAppsView call and ensure there is more information on the listing than just name and id

fix: clean up dto

---

api/prisma/migrations/16_add_duplicates_view/migration.sql
api/prisma/schema.prisma
api/src/controllers/application-flagged-set.controller.ts
api/src/services/application-flagged-set.service.ts
api/test/integration/application-flagged-set.e2e-spec.ts

Alternative grouping of flag sets in the duplicates cron job

fix: alternative way of duplicate grouping

---

api/package.json
api/yarn.lock

https://github.com/bloom-housing/bloom/security/dependabot/200
Upgrades google translate and recaptcha to resolve a [Dependabot alert on protobufjs](https://github.com/bloom-housing/bloom/security/dependabot/200).
Release notes for the breaking version are [here](https://github.com/googleapis/google-cloud-node/releases/tag/translate-v8.0.0), looks like an upgrade to their Node version.
I ensured that google translate was working correctly by creating a new listing with custom text fields and translating it on the public site. But we also have automated tests around this. I didn't make a specific ticket to resolve the dependency. …

chore: manual dependabot - protobufjs

---

sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
sites/partners/src/components/listings/ListingFormActions.tsx

This PR addresses #4384 
This PR refactors the listing form actions to better allow for customizations and readability. 
Since this is PR is meant to isolate the refactor, I suggest doing a code only review on this PR and provide feedback on the new structure, commenting and testing technique. 773 would be the best place to discuss functionality updates.

fix: refactor ListingFormActions file

---

api/prisma/migrations/20_create_feature_flag_table/migration.sql
api/prisma/schema.prisma

This PR addresses [#(1287)](https://github.com/bloom-housing/bloom/issues/1287)
Creates new feature flag table with desired fields.
Run migrations locally. Open query and insert a record into the table.

feat: create feature flag table

---

shared-helpers/__tests__/testHelpers.ts
sites/partners/__tests__/pages/application/index.test.tsx
sites/partners/__tests__/pages/listings/applications/index.test.tsx
sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsAlternateContact.tsx
sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
sites/partners/src/pages/application/[id]/index.tsx

This PR addresses #4563 
* Create a suite of unit tests for the application details view page
* Minor code cleanup and fixes in taste components
* By running a full test sweep or targeting the newly added suite.

4563/ Parteners site application page integration tests

---

sites/public/src/pages/disclaimer.tsx
sites/public/src/pages/privacy.tsx
sites/public/src/patterns/PageHeaderLayout.module.scss
sites/public/src/patterns/PageHeaderLayout.tsx

This PR is a follow up to #4605 
As part of the Doorway uptake, I remembered that the core base layout is actually the inverse and supporting Doorway without pattern divergence will require this inverse prop.
This should have no visual changes on disclaimer or privacy policy page.

fix: inverse styling support

---

api/src/dtos/listings/listing.dto.ts
api/test/integration/listing.e2e-spec.ts

This fixes some flaky api e2e tests
run `yarn test:e2e` in the api directory tests should pass regularly

fix: flaky test updates

---

api/src/services/application-flagged-set.service.ts
yarn.lock

This PR addresses [#1261](https://github.com/metrotranscom/doorway/issues/1261)
NOTE: this has already been merged into Doorway, but we would like to keep it in sync with core
The AFS cron job is occasionally failing in Doorway starting the other day. In order to figure out why it is failing we will need to know what listing it fails on as well as the rule and rule key it complains about.
This PR does two things:
- Adds a try catch around the creation of the flag set so that it doesn't fail the entire job, but rather just that one duplicate set.
- Adds additional logging. More info on what listings the job is getting run for as well as if it fails what did it fail on
Running the AFS job locally still works.
1. make sure you have the following env variables set
``` …
```

fix: add additional logging to afs job (#1262)

---

sites/public/src/pages/_app.tsx

[Slack context](https://exygy.slack.com/archives/C0203460K6Y/p1750097400474679)
Turns Lakeview themeing on regardless of the deployment environment

refactor: apply jurisdictional theme class in prod

---

api/prisma/seed-staging.ts
sites/public/src/components/listing/ListingViewSeeds.module.scss
sites/public/src/components/listing/listing_sections/Apply.tsx
sites/public/src/components/listing/listing_sections/Availability.tsx
sites/public/src/components/listing/listing_sections/DateSection.tsx
sites/public/src/components/listing/listing_sections/InfoCard.tsx
sites/public/src/components/listing/listing_sections/LeasingAgent.tsx
sites/public/src/components/listing/listing_sections/LotteryResults.tsx

Undergoing design review [here](https://www.figma.com/board/OMHo1PQ639gKJRF1NLpbMv/Availability-States?node-id=0-1&p=f&t=5QJf3qeYXYYrWJly-0)
Please include a summary of the change and which issue(s) is addressed.

refactor: mixed availability

---

api/test/unit/services/script-runner.service.spec.ts
shared-helpers/__tests__/stringFormatting.test.ts
shared-helpers/src/locales/general.json
shared-helpers/src/utilities/stringFormatting.ts
sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
sites/public/__tests__/components/browse/ListingBrowse.test.tsx
sites/public/__tests__/components/listing/ListingViewSeeds.test.tsx
sites/public/__tests__/components/listing/ListingViewSeedsHelpers.test.ts
sites/public/__tests__/components/listing/listing_sections/AdditionalFees.test.tsx
sites/public/__tests__/components/listing/listing_sections/RentSummary.test.tsx
sites/public/__tests__/lib/helpers.test.tsx
sites/public/src/components/browse/ListingCard.tsx
sites/public/src/components/listing/ListingViewSeeds.tsx
sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
sites/public/src/components/listing/listing_sections/AdditionalFees.module.scss
sites/public/src/components/listing/listing_sections/AdditionalFees.tsx
sites/public/src/components/listing/listing_sections/Apply.tsx
sites/public/src/components/listing/listing_sections/Availability.tsx
sites/public/src/components/listing/listing_sections/Eligibility.tsx
sites/public/src/components/listing/listing_sections/RentSummary.tsx
sites/public/src/components/listing/listing_sections/UnitSummaries.tsx
sites/public/src/lib/helpers.tsx
sites/public/src/lib/hooks.ts

This PR addresses #5030
This PR addresses a bash on the Detroit production data in the [Detroit seeds environment](https://bloom-detroit.netlify.app/listings). Each change has a comment on it with a description of the bug it is fixing and usually a link to a broken listing.
[There are QA notes with screenshots of each in the issue and example listings I recommend looking at but also here is a list](https://github.com/bloom-housing/bloom/issues/5030):
* The What to Expect section should render markdown content
* The `per year` in the HMI table should show on the subtext line instead of inline
* NaN should not be showing in the Additional Fees section
* Missing `Costs not included` header in Additional Fees section
* Section 8 copy is duplicated, should only show under the rent table and …

fix: detroit prod data qa

---

sites/public/cypress/support/commands.js
sites/public/src/patterns/SiteHeader.tsx

This PR addresses [5045](https://github.com/bloom-housing/bloom/issues/5045)
This PR addresses issue #5045 
Update `data-testid` selector to prevent testid from changing with UI changes unrelated to the feature under test with the goal to reduce test flakiness. 
**Before** `data-testid` would change based on number of elements in navbar
**After** `data-testid` no longer uses index and will not change based on number of elements in navbar
**NOTE** - This PR only addresses the components setting the `data-testid` within bloom core. Any component where the `data-testid` is set on a component imported from ui-components will need to be a separate PR. This limits the scope of this PR to just the Public site and corresponding cypress tests.
- All automated tests continue to pass
- Manually test …

test: remove index from data-testid on public site

---

sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
sites/public/src/pages/applications/financial/income.tsx
sites/public/src/pages/applications/start/choose-language.tsx

This PR partially addresses #4991 by fixing #5041 and #5040 
This PR adds three different null checks based on common application flow testing.
1. Currently the community types (programs under the hood) from Detroit prod have no options set. This will need to be handled by updating the data but as a partial step, I added a null check so the paper application form can load even with these listings attached to them.
2. Detroit prod data had {en} set for the languages field on the jurisdiction table. This resulted in no options appearing on the choose-language.tsx page. This check allows for one button to show.
3. Common app flows with unit groups were failing on the income step because of the verify income logic. This PR checks for units before verifying the income. I also made a follow up …

fix: add null checks

---

sites/partners/src/components/listings/ListingFormActions.tsx
sites/partners/src/components/listings/PaperListingForm/index.tsx
sites/partners/src/pages/listings/[id]/edit.tsx

This PR addresses #(5270
Please include a summary of the change and which issue(s) is addressed.
1-Having the right permission find a listing in draft status (preferably not created/or last edited by you). 
3-Go ahead and try to edit it.  
4-Then click on save
expected: 
The timestamp and user name should be updated in the text located below the button actions:
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very …

updated hour to be 12 hours
