shared/ui-components/.storybook/addons.js, shared/ui-components/package.json, shared/ui-components/src/cards/property_title_image.tsx, shared/ui-components/src/headers/hero.tsx, shared/ui-components/stories/index.tsx, yarn.lock
a couple minor notes:
- the story errors were just typescript syntax that I'm not sure how we missed before, but were easy enough to fix. NB: declare things as string not String was most of them.
- I thought I added a prettier block to package.json but didn't so there's some noisy reformatting here. Will plan to address that asap.
=> add the storybook viewport plugin and fix some (unrelated) story errors

apps/public/package.json, package.json, services/listings/package.json, shared/styles/package.json, shared/ui-components/package.json, yarn.lock
also, update dependencies for @types, tailwind, and webpack (just to stay current)
=> Move eslint + prettier up to the root workspace 

shared/ui-components/.storybook/config.ts, shared/ui-components/.storybook/webpack.config.js, shared/ui-components/package.json, yarn.lock
Pulls `index.scss` from `@dahlia/styles` into Storybook so our stories will be styled.
Had to do the stuff in the `fix-linting-errors` branch before I could run Storybook and do commits, so this branch is branched off that branch and this PR is based on that branch to show an appropriate diff. Can rebase as needed before merging to master.
=> Include CSS from @dahlia/styles in Storybook

apps/public/pages/listings.tsx
Unit summaries got changed after I worked on then and path have been changed. This one updates the path.
=> Fix unit summaries for listings directory

apps/public/pages/HousingCounselors.tsx, docs/DeployAppsNetlify.md, docs/DeployServicesHeroku.md, shared/ui-components/src/page_components/HousingCounselor.tsx
Some old ```@bloom``` package naming snuck in with #84, so correcting that and throwing in some rough deployment documentation that I was working on (@jaredcwhite and @software-project, feel free to add to those whenever you come across new things).
=> Fix the package name and add deployment docs

apps/public-reference/package.json, services/listings/package.json, shared/ui-components/package.json, yarn.lock
This adds it to yarn.lock, which seems to be necessary for correct install of the listings service on Heroku.
=> Make bloom-housing/core version explicit

.gitignore
This is really a downstream problem, but it seemed best to fix it here for the future. The goal is to prevent cypress videos from being added to checkins from non-reference apps.
=> Update gitignore to prevent cypress artifacts

apps/public-reference/cypress/integration/navigation.ts, apps/public-reference/next.config.js, apps/public-reference/pages/redirect.tsx, package.json, services/listings/__tests__/lib/url_helper.test.ts, services/listings/src/index.ts, services/listings/src/lib/url_helper.ts, shared/core/src/listings.ts, shared/ui-components/src/page_components/listing/ListingsList.tsx, yarn.lock
This PR adds descriptive url "slugs" to the end of listing page URLs:
`/listing/jsQvgvy6eJy56TNCFfQp8` => `/listing/jsQvgvy6eJy56TNCFfQp8/the_triton_55_triton_park_lane_foster_city_ca`
The bare "id-only" URLs will still work; they issue an immediate 301 redirect to the pretty version. This PR adds a general purpose `Redirect` component to accomplish this.
The url slug is available as an attribute `urlSlug` on the `Listing` type.
Minor version bump of `eslint-typescript` to [allow function definitions](https://github.com/typescript-eslint/typescript-eslint/pull/1736). This was necessary to avoid an eslint error on [this line](https://github.com/bloom-housing/bloom/blob/add-url-slugs/apps/public-reference/pages/redirect.tsx#L15).
Closes #215
=> Add pretty URL slugs to listing pages

apps/public-reference/.env.template, apps/public-reference/netlify.toml, docs/Analytics.md, docs/DeployAppsNetlify.md, yarn.lock
Adds a key for local development testing that won't both anything else.
Also cleans up a yarn.lock reference to an older version of /core
=> Add local development GTM key

backend/core/src/entity/Listing.ts, backend/core/src/listings/listings.service.ts
Master branch uses Data Mapper and the PR changes that to use Active Record
- No need for class-transformer in Data Mapper (otherwise typescript complains about missing database access methods),
- Explicit dependencies in Data Mapper (one can see exactly what service depends on because it's injected in the constructor),
- Active Record requires entity classes to extend `BaseEntity` and based on what I see in [typeorm-model-shim](https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js) this is not going to work with models exporting since model shim is only providing empty definitions for decorators
=> Make listings service and tests use active record

shared/ui-components/package.json
It didn't work as a devDependency since it needs to end up in node_modules for implementing sites to compile correctly. Otherwise you'll get `Invalid module name in augmentation. Module 'jwt-decode' resolves to an untyped module`...
=> Make @types/jwt-decode a runtime dependency

apps/partners-reference/pages/_error.jsx, apps/public-reference/pages/_error.jsx
Fixes #345, which was annoying me this morning.
I'm not sure if I'm missing some intended behavior with pageTitle being a JSX.Element here, but it was the unhappiness causing the error, and it seems to work reasonably as a string.
=> Fix the JS error on the error page

apps/partners-reference/pages/_app.jsx, docs/Authentication.md, shared/ui-components/__tests__/authentication/RequireLogin.test.tsx, shared/ui-components/package.json, shared/ui-components/src/authentication/RequireLogin.tsx, shared/ui-components/src/authentication/UserContext.tsx, shared/ui-components/src/authentication/index.ts, shared/ui-components/src/authentication/token.ts, shared/ui-components/src/authentication/useRequireLoggedInUser.ts
This PR adds a utility component `<RequireLogin>` and hook (`useRequireLoggedInUser`) to help manage protected front end routes.
`<RequireLogin>` only renders its children if the user is signed in, or the path doesn't require login. Login is based on props using either a blacklist (`requireForRoutes`) or whitelist (`skipForRoutes`), both of which can be RegExp. If a user isn't logged in and the requested path matches the appropriate list, the user will be redirected to the `signInPath` prop. If no lists are provided, login is required for all paths other than the sign in path.
Closes #387
=> Add utility hook + component to require login to access a page

shared/ui-components/src/locales/general.json
This was customized for both Alameda and SMC, so I think we're better off just having the more standard text here in core. My understanding is that the "under 6" language is an SF thing, and it'll be easy enough for them to override the string in their own implementation.
(cc: @akegan, as perhaps the smallest possible customization to try next week)
=> Update occupancy description to match most housingbayarea sites

apps/public-reference/pages/redirect.tsx
This is just to make an annoying console warning go away. It should not have any functional effect (and if so, that's probably a bug).
The warning in question looks like:
```
[1] Warning: Invalid DOM property `http-equiv`. Did you mean `httpEquiv`?
[1]     in meta (at redirect.tsx:11)
[1]     in head
[1]     in Head
[...]
```
See also https://github.com/facebook/react/issues/10863 and https://github.com/facebook/react/issues/11160 for the backstory. I did a view-source on the redirect page after making the change, and it seems to be doing the transformation as promised.
=> Use react-specific httpEquiv syntax in redirect

backend/core/src/entity/user.entity.ts, shared/ui-components/src/forms/ErrorMessage.tsx, shared/ui-components/tailwind.config.js, shared/ui-components/tsconfig.json, yarn.lock
This removes a couple of unused imports that were causing build errors for Storybook, but then I just went ahead and disabled that error entirely in the tsconfig.json used for Storybook since it turns out there's one that's now autogenerated into `backend/core/client.ts` and that seemed like it might be too complicated to fix. We should watch and make sure we don't silently ignore typescript errors that we care about in the real apps.
This also has a yarn.lock update that seems unrelated since there are no package.json updates anywhere. I'm guessing there was a missing yarn.lock update in one of the commits we merged yesterday.
=> Fix minor errors with the storybook build

apps/public-reference/lib/ApplicationConductor.ts, apps/public-reference/pages/applications/contact/address.tsx, apps/public-reference/pages/applications/contact/alternate-contact-name.tsx, apps/public-reference/pages/applications/contact/alternate-contact-type.tsx, apps/public-reference/pages/applications/contact/name.tsx, apps/public-reference/pages/applications/financial/income.tsx, apps/public-reference/pages/applications/financial/vouchers.tsx, apps/public-reference/pages/applications/household/ada.tsx, apps/public-reference/pages/applications/household/add-members.tsx, apps/public-reference/pages/applications/household/current.tsx, apps/public-reference/pages/applications/household/live-alone.tsx, apps/public-reference/pages/applications/household/member.tsx, apps/public-reference/pages/applications/household/members-info.tsx, apps/public-reference/pages/applications/household/preferred-units.tsx, apps/public-reference/pages/applications/preferences/general.tsx, apps/public-reference/pages/applications/preferences/intro.tsx, apps/public-reference/pages/applications/preferences/live-or-work.tsx, apps/public-reference/pages/applications/reserved/units.tsx, apps/public-reference/pages/applications/review/demographics.tsx, apps/public-reference/pages/applications/review/summary.tsx, apps/public-reference/pages/applications/review/terms.tsx, apps/public-reference/pages/applications/start/choose-language.tsx, apps/public-reference/pages/applications/start/what-to-expect.tsx, shared/ui-components/src/forms/ProgressNav.stories.tsx, shared/ui-components/src/forms/ProgressNav.tsx, shared/ui-components/src/locales/general.json
This PR cleans up most of the warnings that we were seeing in the application forms.
- Missing Unique key warnings caused  by `<ProgressNav />`
- Missing Unique keys on a few of the form pages
- Fixed `<Link>` not having nested `<a>` tags for back buttons
- Fixed bug where the conductor was serializing the string literal `undefined` to sessionStorage if no listing was defined (which would then prevent the page from reloading properly).
I'm still seeing a couple warnings resulting from dynamically generated text:
This occurs when the page text is updated based on a variable that's only available client-side (e.g. comes from local storage/an existing object - the version that React rehydrates the page with is different from Next.js's SSR. This doesn't really seem to be causing usability …
=> Clean up application form warnings

backend/core/package.json, services/listings/package.json
Heroku service startup was starting to consistently fail because it was taking more than a minute, and investigation led to us trying to run `yarn install` every time we started up the service.
This should fix things for both the legacy listings service and the new nestjs backend core.
=> Don't rerun yarn install during heroku app startup

backend/core/jest.json, backend/core/src/auth/auth.controller.spec.ts, backend/core/src/auth/auth.service.spec.ts, backend/core/src/auth/constants.ts, backend/core/src/entity/revokedToken.entity.ts, backend/core/src/entity/user.entity.ts, backend/core/src/seed.ts, backend/core/src/user/user.controller.spec.ts, backend/core/src/user/user.service.spec.ts, backend/core/test/applications/applications.e2e-spec.ts, backend/core/test/lib/url_helper.spec.ts, backend/core/test/listings/listings.spec.ts
This is a downpayment on #474. It looks like it's not just the jest config, but the actual tests need help (or I'm using them so incorrectly that they need much better documentation).
Based on the error messages that I was getting, I first updated all the relevant tests to make sure we were using jest's expect and not the one from cypress/chai, which seems to be a common monorepo problem.
Once I got past that, things got more interesting with the entities not reflecting metadata correctly and the app not starting up in many cases. I tried to update the metadata to include the actual database column types, which seemed to help but then created a new set of problems. @bencpeters or @pbn4, do you know how this was working right before? Is it something that broke with the upgrade to jest26 or …
=> fix backend/core test failures

apps/partners-reference/cypress/support/index.ts, apps/partners-reference/package.json, apps/public-reference/package.json, backend/core/package.json, services/listings/package.json, shared/core/package.json, shared/ui-components/package.json, yarn.lock
- Fixes the port numbers in the partners-reference Cypress API tests to match the new numbering scheme in #468. 
- Makes explicit the peerDependencies for the Cypress webpack processor, which is the last thing for fixes #137. 
- Bumped the babel and cypress versions globally while I was at it.
=> Fix minor issues with Cypress for partners-reference

.circleci/config.yml, package.json
Fixes #368
Fixes #425 (at least for CI)
Note that backend/core auth tests are failing for lack of a database. I split that off into #517 so that we can get at least some of the new coverage in the meantime.
There's also a build failure with partners, but that's already fixed in #500.
=> Expand CircleCI Coverage to include backend/core and app builds

apps/public-reference/pages/applications/contact/address.tsx, apps/public-reference/pages/applications/contact/alternate-contact-contact.tsx, apps/public-reference/pages/applications/contact/alternate-contact-name.tsx, apps/public-reference/pages/applications/contact/alternate-contact-type.tsx, apps/public-reference/pages/applications/contact/name.tsx, apps/public-reference/pages/applications/financial/income.tsx, apps/public-reference/pages/applications/financial/vouchers.tsx, apps/public-reference/pages/applications/household/ada.tsx, apps/public-reference/pages/applications/household/add-members.tsx, apps/public-reference/pages/applications/household/live-alone.tsx, apps/public-reference/pages/applications/household/member.tsx, apps/public-reference/pages/applications/household/members-info.tsx, apps/public-reference/pages/applications/household/preferred-units.tsx, apps/public-reference/pages/applications/preferences/general.tsx, apps/public-reference/pages/applications/preferences/select.tsx, apps/public-reference/pages/applications/review/demographics.tsx, apps/public-reference/pages/applications/review/summary.tsx, apps/public-reference/pages/applications/review/terms.tsx, apps/public-reference/pages/applications/start/choose-language.tsx, apps/public-reference/pages/applications/start/what-to-expect.tsx, backend/core/seeds.json, services/listings/listings/triton-test.json, shared/ui-components/src/headers/Hero/__snapshots__/Hero.stories.storyshot, shared/ui-components/src/page_components/listing/__snapshots__/ListingsGroup.stories.storyshot
Closes #513 
Also loads in the `listingId`query parameter to pull in the requested listing data. Currently has a fallback using the previous behavior, so we should file a separate issue to handle the real error condition of an invalid/missing ID.
=> Support dynamic listing IDs and add name to progress nav

docs/DeployAppsNetlify.md
Netlify does not install yarn unless it detects a yarn.lock, even if YARN_VERSION is defined in the configuration. Ours lives at the monorepo root in version control, which Netlify can't see since we set the build root to be the app directory. Adding a no-op version here, similar to what we did for the public app in #177.
=> Add a no-op yarn.lock in partners-reference for netlify

shared/ui-components/package.json, shared/ui-components/styles/navbar.scss, shared/ui-components/styles/utilities/_setup_bulma.scss, yarn.lock
Closes #505 
Just needed a few required variables/functions loaded in to placate the updated Bulma SCSS utilities in 0.9.
=> Upgrade to Bulma 0.9

apps/partners-reference/netlify.toml, apps/public-reference/netlify.toml
Some nest endpoints were getting double slashes, which made them unhappy, so standardizing on no trailing / in LISTING_SERVICE_URL in the toml files to line up with the implicit practice in .env.template.
=> Align backend URLs for netlify + remove trailing slashes

apps/public-reference/pages/listing.tsx
I created a check for null (buildingAddress or buildingAddress.lat || buildingAddress.lng) - I'm not sure if the situation exists when buildingAddress has few records, but not have lat & lng.
=> Do not show map if lat & lng are null

apps/public-reference/lib/hooks.ts, apps/public-reference/pages/applications/start/choose-language.tsx, apps/public-reference/pages/create-account.tsx, apps/public-reference/pages/sign-in.tsx, shared/ui-components/src/authentication/UserContext.tsx
I created a basic version of the redirect. I'm not sure about a couple of things so please leave your feedback :)
To achieve 2 things:
- redirect the user to the latest path
- show success modal
I had to save a path before the change. We cannot use history.go(-1), because it is impossible to attach extra params to the URL.
So, I created property in the UserContext to store the last path, and additional method to change localization with query param including user name (to show it in the modal).
Also, the login success modal seems to work only on the homepage.
=> Added basic version of redirect

apps/partners-reference/layouts/application.tsx, apps/public-reference/cypress/integration/navigation.ts, apps/public-reference/package.json, apps/public-reference/pages/account/applications.tsx, shared/ui-components/src/cards/__snapshots__/ImageCard.stories.storyshot, shared/ui-components/src/headers/SiteHeader/SiteHeader.tsx, shared/ui-components/src/headers/SiteHeader/__snapshots__/SiteHeader.stories.storyshot, yarn.lock
Quick PR to add the now-required ariaDescription to the Modal component on the My Applications page. I just reused the same string that we're using for the modal title, but there's probably a better best practice per: https://www.w3.org/TR/wai-aria-practices-1.1/#alertdialog
This also fixes a number of test failures that snuck in from the last few PRs merged -- one each for public build, public cypress, and partners build (which still has an open issue I'll fix in a different PR).
=> Fix modal ariaDescription on My Applications page + fix tests

apps/public-reference/pages/applications/household/members-info.tsx, apps/public-reference/pages/applications/household/preferred-units.tsx, shared/ui-components/src/locales/general.json
Addresses 2/3rds of #576 -- this should fix the first two text related issues, but I'll leave that open until we handle disabling of income validation.
@slowbot - The CSS might need adjustment in one or both cases, so feel free to change as needed.
=> Text tweaks to support applications pilot

apps/public-reference/package.json, apps/public-reference/pages/applications/review/terms.tsx, apps/public-reference/types/mdx.d.ts, shared/ui-components/package.json, shared/ui-components/tailwind.config.js, shared/ui-components/types/markdown-to-jsx/index.d.ts, yarn.lock
They finally landed a PR to fix @types/markdown-to-jsx, so I went ahead and switched over to it before we forgot. Unrelated, other than it's another minor build cleanup in ui-components, but I also enabled `removeDeprecatedGapUtilities` for tailwind, which is officially a 2.0 deprecation, but we're not using it currently and the warning message at startup/build was annoying.
fixes #347
=> Use proper @types for markdown-to-jsx

apps/public-reference/layouts/application.tsx, apps/public-reference/pages/applications/household/preferred-units.tsx, apps/public-reference/pages/applications/review/confirmation.tsx, apps/public-reference/pages/applications/review/demographics.tsx, apps/public-reference/pages/applications/start/choose-language.tsx
Issue: #589 
Disabled:
"Sign In" link in main navigation
"Already have an account" section on start/choose-language
"Save and finish later" on applications/household/preferred-units and applications/review/demographics
"Create Account" screen on /applications/review/confirmation
=> Disabled login flow elements

shared/ui-components/src/forms/DOBField.tsx
Age/year validation was broken in Safari but worked in Chromium-based browsers. This fix ensures it works consistently.
=> Fix age validation for DOBField

backend/core/ami_charts/AlamedaCountyLIHTC2020.json, backend/core/ami_charts/AlamedaCountyTCAC2019.json, backend/core/ami_charts/OaklandFremontHUD2020.json, backend/core/ami_charts/SanMateoCountyTCAC2019.json, backend/core/ami_charts/SanMateoCountyTCAC2020.json, backend/core/ami_charts/SanMateoHUD2020.json, backend/core/src/lib/ami_charts.ts
This adds the active AMI charts from housingbayarea to backend/core, so they're all available for test listings to use.
=> add ami charts from housingbayarea for testing ease

.circleci/config.yml, shared/ui-components/src/locales/general.json, yarn.lock
- disable the currently-broken Cypress e2e test until we have a working test DB backend for it
- fixed a couple minor package changes in an earlier PR that didn't get reflected in yarn.lock
- fixed a text string with a few extra words that didn't belong
=> fix three minor lingering annoyances

backend/core/ormconfig.ts
Heroku production plans are set up to require SSL, which is a Good Thing for security, but we need to turn it on.
=> use an SSL connection in prod and allow a self-signed cert for it

shared/ui-components/src/locales/general.json
Fixes #671.
Also fixes a bunch of other cases where I don't think we need to use the word "lottery" explicitly.
=> reduce use of the word "lottery" when not needed

backend/core/src/applications/applications.controller.ts, backend/core/test/applications/applications.e2e-spec.ts
Fixes a bug that @pbn4 found. While applying with no email, email confirmation was throwing an error.
=> Fix email confirmation when there is no email

backend/core/ami_charts/AlamedaCountyTCAC2020.json, backend/core/src/lib/ami_charts.ts
This just copies the AlamedaCountyTCAC2020 AMI chart over from housingbayarea, so that we can load listings that reference it easily for testing.
=> add AlamedaCountyTCAC2020 AMI chart to ease testing real listings

backend/core/README.md, yarn.lock
There was a minor regression in #782 of yarn.lock so it fell out of sync with the package.json files. This fixes that by just checking in what's generated by running `yarn`. 
Also there's a minor doc addition tagging along.
=> Fix regression in yarn.lock

apps/public-reference/pages/applications/start/choose-language.tsx
I noticed an infinity loop in the choose-language step, fixed by adding condition (if listing is null).
=> Fixed infinity loop

apps/public-reference/pages/applications/review/demographics.tsx
Closes #818 
Demographics form is persisted, but it was an issue with initial values (only in frontend side, context still had saved values).
=> Set default values for the demographics form

apps/public-reference/pages/applications/contact/address.tsx, apps/public-reference/pages/applications/contact/alternate-contact-contact.tsx, apps/public-reference/pages/applications/contact/name.tsx, apps/public-reference/pages/applications/household/member.tsx, shared/ui-components/src/forms/DOBField.stories.tsx, shared/ui-components/src/forms/DOBField.tsx, shared/ui-components/src/forms/PhoneField.tsx, shared/ui-components/src/forms/__snapshots__/DOBField.stories.storyshot
The idea is to do not validate the phone field and DOB when the `required` prop is set to `false` and length = 0 or undefined.
Implemented for partners MVP purposes.
=> "required" prop in PhoneField and DOBField

sites/partners/next.config.js
Fixed build problems with not existing /listings path inside next.config.js
It has been moved to dynamic route because generating a page for each listing/application details is unnecessary in this case - and not optimal performance perspective (e.g generating a million pages for million applications).
=> Removed not existing paths from the config

sites/partners/lib/hooks.ts, sites/partners/pages/index.tsx, ui-components/src/authentication/client.ts
This PR is not covered by any issue.
- Filtered application list to show items depends on user role
Admin user sees all listings, leasing agents - only for his own listings.
=> Filtered listings by permission

sites/public/pages/listing.tsx
Household Maximum Income translations weren't being resolved in Mobile view  
Issue:
After Fix:
=> fix household maximum income translations on mobile view

ui-components/src/locales/es.json, ui-components/src/locales/general.json, ui-components/src/locales/vi.json, ui-components/src/locales/zh.json
Closes: #1073 
**Updated:**
"lottery_results" --> header under lotteryResults
"lottery_results_coming_soon" --> completeResultsWillBePosted under lotteryResults
"lottery_download" --> downloadResults under lotteryResults
"which_household_member" --> whichHouseholdMember under displacedTenant
"address_displaced" --> whatAddress under displacedTenant
"additional_resources" --> viewAdditionalHousing in welcome
"logged_out_error_no_account" --> afterMessage in timeout
=> Updated translations

backend/core/src/applications/applications.service.ts, backend/core/test/applications/applications.e2e-spec.ts
Plain user input is now converted to tsquery with prefix support
Add tests for improved search
resolves #969
=> Add better support for applications search

ui-components/src/blocks/AppStatusItem.tsx
While exploring creating a npm package fork, I ran into an issue where I couldn't change the @bloom-housing org name in package.json because there was an `@bloom-housing/ui-components` import from _within_ ui-components.
This seems like a mistake, so this change switches it to a local import instead. This might be something we can lint for?
=> Remove self package reference in ui-components

backend/core/src/shared/email.service.spec.ts, backend/core/src/views/partials/feedback.hbs, backend/core/src/views/partials/footer.hbs, backend/core/src/views/register-email.hbs, sites/public/pages/account/dashboard.tsx, sites/public/src/ConfirmationModal.tsx
=> Fix message after account confirmation

backend/core/src/seed.ts, sites/public/cypress/integration/navigation.ts
The navigation suite was broken by this PR https://github.com/bloom-housing/bloom/pull/1124 (It's not flake, the suite is failing consistently / broken after the change - looks like changing the listing name changes the URL slug)
=> fix/broken Cypress tests on master

sites/public/pages/listing.tsx, ui-components/src/global/blocks.scss, ui-components/src/page_components/listing/listing_sidebar/ApplicationSection.tsx, ui-components/src/page_components/listing/listing_sidebar/Apply.tsx, ui-components/src/page_components/listing/listing_sidebar/LeasingAgent.tsx, ui-components/src/page_components/listing/listing_sidebar/WhatToExpect.tsx, ui-components/src/page_components/listing/listing_sidebar/events/DownloadLotteryResults.tsx, ui-components/src/page_components/listing/listing_sidebar/events/LotteryResultsEvent.tsx, ui-components/src/page_components/listing/listing_sidebar/events/OpenHouseEvent.tsx, ui-components/src/page_components/listing/listing_sidebar/events/PublicLotteryEvent.tsx
This supersedes #1088. Resolves #1084 
---
**Desktop**
- Unit Table
Sidebar:
- Due Date
- Open House
- Waitlist
- How to Apply / Post Lottery: Download Results
- Lottery Date
- What to Expect
- Contact Leasing Agent
**Mobile**
- Unit Table
- Due Date
- Waitlist
- How to Apply / Post Lottery: Download Results
Process Accordion:
- Open House
- Lottery Date
- What to Expect
- Contact Leasing Agent
=> Clean up aside block styling and add missing mobile blocks

sites/public/lib/hooks.ts, sites/public/pages/applications/start/choose-language.tsx
This is a fix following up on #1111 to ensure the user is redirected to the correct listing after signing in.
=> Use correct listingId when redirecting from Sign In

sites/public/pages/listing.tsx
Following QA on the Nova listing and their ask to remove the credit history and rental history sections for lack of language, this PR makes all three of the additional eligibility sections optional (previously it required an empty string and the headers would still appear). Ran this past Kathy 👍
=> Make additional eligibility sections optional

backend/core/src/shared/units-transformations.ts, sites/public/pages/listing.tsx, ui-components/__tests__/helpers/getTranslationWithArguments.test.ts, ui-components/index.ts, ui-components/src/helpers/getTranslationWithArguments.ts, ui-components/src/tables/StandardTable.tsx
Addresses #1065 
When a listing had `bmrProgramChart` set to true, the console was reporting to translation errors.
The issue was that `unit-transformations` was sometimes passing a translation key (i.e. `t.key`) and sometimes (in the case of BMR) passing an english string (i.e. `20% AMI units`). This produced the console errors because `StandardTable` was passing every incoming string as if it were a key, so there were "missing keys". So it was both untranslated, and not a key.
The tricky part about this fix is that `X% AMI Units` can't just be passed as a key as it has an argument, and I didn't see a precedent for that anywhere. Following the format `t.key,argumentName:argumentValue` I'm allowing the headers of `StandardTable` to be passed header key strings that include optional …
=> fix: bmr translation issue

ui-components/package.json
Addresses #820 
Images and Icons (specifically within the Icon story) were not appearing at our public Storybook (https://storybook.bloom.exygy.dev/). The issue ended up being that we just weren't indicating where our assets were supposed to live.
This was tested locally by first removing the current storybook build (lives at storybook-static), and then from within ui-components, building storybook with `yarn build-storybook` and serving it locally with `npx http-server ./storybook-static`. Can confirm no images appear on master with these steps, but they do on this branch. If you ever end up switching between master and this branch locally to test it out, you might also want to clear your browser's cache in between.
=> fix: storybook images not appearing in public build

sites/partners/public/images/icons.svg, sites/public/pages/applications/review/terms.tsx, sites/public/public/images/icons.svg, ui-components/__tests__/overlays/LoadingOverlay.test.tsx, ui-components/public/images/icons.svg, ui-components/src/actions/Button.stories.tsx, ui-components/src/icons/Icon.scss, ui-components/src/icons/Icon.tsx, ui-components/src/overlays/LoadingOverlay.scss, ui-components/src/overlays/LoadingOverlay.stories.tsx, ui-components/src/overlays/LoadingOverlay.tsx
Addresses #1193 
The submit button on the Terms page for the Application was allowing multiple clicks before the form was submitted. This PR uses the "loading" state of the button component to provide visual feedback as well as preventing additional clicks.
In addition, I:
* Refactored the loading overlay components to use the spinner in the icons SVG
* Changed the spinner SVG so it uses CSS animation (apparently SMIL is deprecated, also buggy in Safari)
* Equalized the spinner icon SVG across our three packages (previously the public site was out of date)
I manually tested the Terms page of the Application Form, and wrote an example in Storybook for `LoadingOverlay` and `Button` with the loading state.
=> Add spinner to the Application Form terms page upon submit

backend/core/client.ts, backend/core/src/listings/dto/listing.dto.ts, backend/core/src/listings/entities/listing.entity.ts, backend/core/src/seeds/listings.ts, backend/core/types/src/backend-swagger.ts, ui-components/src/page_components/listing/ListingsList.tsx
No pre-existing issue
`Open Waitlist` was showing on the listings overview page for every listing regardless of whether or not it had a waitlist. New logic flow is if there is a current size and max size of a waitlist, and there are spots, show `Open Waitlist` otherwise nothing. You can see the bug here on staging: https://ala.bloom.exygy.dev/listings
Checked out the /listings page on both desktop and mobile. I locally have listings with and without a waitlist.
=> fix: waitlist open showing for every listing

CHANGELOG.md, backend/core/types/src/backend-swagger.ts, sites/public/pages/applications/preferences/all.tsx
No issue, made ad-hoc while testing and was super quick.
Yesterday I merged changes to allow custom select text on preferences and there was a bug. The select text would repeat itself before each individual preference instead of just once at the top. This fixes that! 
You can test it out locally on the Triton 2-pref listing.
=> fix: preference select text issues

ui-components/.storybook/preview-head.html, ui-components/src/config/NavigationContext.tsx, ui-components/src/navigation/LanguageNav.stories.tsx
Addresses #1263 
This PR fixes a display issues with the "Code" samples in Storybook, as well as problem preventing certain components using `LinkComponent` from displaying the right styles.
Verify in Storybook.
- N/A -I have added tests that prove my fix is effective or that my feature works
=> Storybook styling fixes

CHANGELOG.md, ui-components/src/helpers/preferences.tsx
I noticed, for Test listing with 0 preferences - paper application form doesn't work. That's because 
Choose `Test listing(0 pref)`, then try to submit an application.
=> Fixed paper app submission error if there are no preferences

CHANGELOG.md, ui-components/src/config/NavigationContext.tsx, ui-components/src/global/navbar.scss, ui-components/src/headers/SiteHeader.stories.tsx, ui-components/src/headers/SiteHeader.tsx
Addresses #1313
(1) Bug where title/logo would overlap the menu hamburger on mobile view
(2) Request from SF to allow logo to be just an image in additional to an image + text
(3) Request from SF to allow logo to exist at multiple set widths, small / medium / large
Ran into tons of issues accomplishing this due to our 3rd-party use of the Bulma nav bar which led me to create #1345 - lots of context in that ticket!
Check out the new stories ensuring you test each one in a mobile view as well :)
=> feat: navbar custom widths and image only support

ui-components/__tests__/tables/MinimalTable.test.tsx, ui-components/__tests__/tables/StandardTable.test.tsx, ui-components/src/global/tables.scss, ui-components/src/tables/MinimalTable.stories.tsx, ui-components/src/tables/MinimalTable.tsx, ui-components/src/tables/StandardTable.stories.tsx, ui-components/src/tables/StandardTable.tsx
Addresses #1160 
You can now wrap `img` tags in `TableThumbnail` values for `StandardTable` and `MinimalTable` components. They'll be displayed automatically as thumbnails. There's also `flushLeft` and `flushRight` props for `MinimalTable`.
=> Add table image thumbnails and minimal flush styles

CHANGELOG.md, backend/core/package.json, backend/core/src/application-flagged-sets/application-flagged-sets.service.ts, backend/core/src/applications/applications.service.ts, backend/core/test/afs/afs.e2e-spec.ts, yarn.lock
Addresses # (#1362)
This PR addresses two problems:
- incorrectly displaying totalFlagged (backend ignored listingId query param when counting totalFlagged in AFS table)
- a race condition when two applications were added in similar time, resulting in one of them not being captured by an AFS table (e.g. a duplicate set contained one application less than it should). The new implementation now runs the entire application insert and AFS creation as a transaction with serializable isolation level. This now leads to potential read/write dependencies between transactions and PSQL aborting one of the ongoing transactions (in a case where two users submit an application in the same time). I have implemented basic expontential backoff retry logic with `async-retry` package, but the maximum number …
=> Issue 1362/total flagged bug

CHANGELOG.md, sites/partners/pages/listings/[id]/index.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx, sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/FormListingData.tsx, sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx, sites/public/pages/applications/contact/alternate-contact-contact.tsx, ui-components/src/blocks/ViewItem.scss, ui-components/src/forms/Textarea.scss, ui-components/src/global/forms.scss, ui-components/src/locales/es.json, ui-components/src/locales/general.json, ui-components/src/locales/vi.json, ui-components/src/locales/zh.json, ui-components/src/page_components/listing/listing_sidebar/LeasingAgent.tsx
Adds the leasing agent section for listings management. Added the bottom since we don't have the tabs in there yet. Email should auto-populate due to the preset defaults in the prototype. The styling changes are to make the Textarea consistent with the text fields, and the text fields consistent with the Figma. I saw the styling inconsistencies in this PR and not the previous ones bc this section has both textareas and text fields.
Create a new listing in partners at listings/add
Add the new leasing agent section, save as draft
Restart the app
Look at the listing you created in public and check the new fields
In partners visit listings/[id-of-listing-you-just-made] and see the detail version of the form as well
=> 1349/leasing agent section, listings management

CHANGELOG.md, backend/core/src/shared/units-transformations.ts
#1397 
Fixes totalAvailability for units. It takes into consideration unit's status
Change unit status for a certain type to unavailable. Go to listings page and on unit summary section availability should say `WAITLIST`
=> Fix units availability display

CHANGELOG.md, sites/partners/pages/listings/[id]/index.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalDetails.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalEligibility.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailApplication.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingDetails.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailListingIntro.tsx, sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/AdditionalDetails.tsx, sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx, sites/partners/src/listings/PaperListingForm/sections/FormListingData.tsx, sites/partners/src/listings/PaperListingForm/sections/ListingIntro.tsx, ui-components/src/blocks/ViewItem.scss, ui-components/src/locales/general.json
Addresses #1315 #1317
Adds the intro and building details sections for listings management MVP
Create a new listing in partners at listings/add, exercise the new fields, check the detail version of the form
The listings pages themselves are not currently working so not able to check out the public app
=> 1317/listings management, building details & intro

backend/core/src/listings/dto/listing.dto.ts, backend/core/src/listings/entities/listing.entity.ts, backend/core/src/migration/1625041988613-add-additional-notes-column-to-listing.ts
Adds migration for Listing.additionalApplicationSubmissionNotes and removes field definition from DTO (it's inherited from Listing and does not require changes (?)).
NOTE: No template because it targets another PR
=> Add additionalApplicationSubmissionNotes migration

CHANGELOG.md, ui-components/src/config/NavigationContext.tsx, ui-components/src/headers/SiteHeader.tsx, ui-components/src/navigation/Breadcrumbs.tsx, ui-components/src/navigation/TabNav.tsx
Addresses #1378 
React has reserved the "aria" prop for future use. I renamed the aria prop on LocalizedLink to be `ariaProps` to avoid that naming collision, while preserving the ability to stuff that prop with any aria-related props. 
Test that this works by verifying that the aria props are still being passed through to the link component as expected.
Spin up Storybook and:
=> #1378 Use specific aria props in LocalizedLink

CHANGELOG.md, sites/partners/README.md, sites/partners/package.json, sites/public/README.md, sites/public/package.json
[City Of Detroit PR #195](https://github.com/CityOfDetroit/bloom/pull/195)
Addresses #194
- Add debug flags to the `yarn dev` commands for the frontends.
- Also updates the readmes with instructions for adding a vscode launch.json config
- Moves the partners debug port from `2930` to `2931` to so debug and http ports are aligned.
- Adds debug flag to public site with debug port at `2930`
=> Add debug flags and instructions for debugging frontends

backend/core/src/listings/dto/listing.dto.ts
This change addresses a serialization bug we ran into (https://github.com/CityOfDetroit/bloom/issues/183); TLDR serializing the response to `GET /listings` was dropping the `unitsSummarized` field.
The core difference that I believe is responsible: the Detroit response to that request is a `PaginatedListingsDto` (which wraps an array of `ListingDto`s), whereas the Exygy response is just an array of `ListingDto`s. I wasn't able to figure out why serialization was dropping `unitsSummarized` in our case, but I did discover that relying on the `Transform` decorator instead of using a getter method fixed this issue. And using `Transform` in this way seems to also match what is done for the `units` field in the `ListingDto` already. 
I tested this using the existing `backend/core` tests.
=> Make unitsSummarized a Transform field within Listing (#259)

sites/public/pages/housing-counselors.tsx
Addresses CityOfDetroit/bloom#171
If the getInitialProps fails, the page will fail to render. So make the
rendering optional so that at least the empty page will be able to be
displayed. Needed to get Detroit's cypress tests passing.
Use the sfgov default for HOUSING_COUNSELOR_SERVICE_URL in .env. Then go to `localhost:3000/housing-counselors`.
=> Let the counselor page render if no props.

CHANGELOG.md, lerna.json, sites/partners/next.config.js, sites/partners/pages/index.tsx, sites/partners/pages/listings/[id]/edit.tsx, sites/partners/pages/listings/[id]/index.tsx, sites/partners/pages/listings/add.tsx, sites/partners/src/ListingGuard.tsx
Addresses #1581 (issue)
In this PR:
- Added a new `ListingGuard` component to show listing pages (add, details, edit) for admins and allowed leasing agents
- Removed `SHOW_LM_LINKS ` environment variable
- Updated 'Add listing' button to be visible for admin users only
Admin:
1. Log in as an admin user
2. Check if on the main page the "Add listing" button is visible
3. Check if you can add/edit listing
User:
1. Log in as a user
2. Check if on the main page the "Add listing" button is hidden
3. Check if you can add/edit listing which is no assigned to the logged user (you shouldn't)
User (with assigned listing):
1. Log in as a user
2. Check if on the main page the "Add listing" button is hidden
3. Choose a listing where the currently logged user is a leasing agent
3. Check if you can …
=> 1581 - Update buttons/pages visibility depending on a user role

CHANGELOG.md, backend/core/src/listings/listings.service.spec.ts, backend/core/src/shared/dto/filter.dto.ts, backend/core/src/shared/filter/index.ts
Add support for IN comparison for lists
Addresses CityOfDetroit/bloom#255 
Add support for commas-separated lists to filters. Also ensures that provided comparison is valid.
- Adds an `IN` comparison type
- If the filter specifies an `IN` comparison, treat the filter value as a comma-separated list
- Handles if there are extra commas and spaces between the commas and the value
- Add tests to listings service spec. (We should also start writing tests for the addFilters code itself)
- Adds switch statement to `addFilters()` to ensure that the provided comparison is a valid one
In the future we may want to add validation to the `$comparison` FilterParam, but this works well for now.
Please describe the tests that you ran to verify your changes. Provide instructions so we can review. Please …
=> Add support for comma-separated lists to filters, ensure comparison is valid

CHANGELOG.md, sites/partners/lib/hooks.ts
Addresses #1635 
Only first 10 listings were showing up on partners. Pagination is not yet enabled on that page and `limit=all` was only enable for stale cache.
=> Add limit all to listings call on partners

sites/public/pages/index.tsx, sites/public/pages/listings.tsx
If no data is returned for listings, return an empty array (otherwise the build will fail) - may want to un-do this change once the core issues are resolved(?)
=> netlify build issues

CHANGELOG.md, backend/core/scripts/listings-importer.ts, backend/core/src/application-methods/dto/application-method.dto.ts, backend/core/src/seed.ts, backend/core/src/seeds/listings/listing-coliseum-seed.ts, backend/core/src/seeds/listings/listing-default-seed.ts, backend/core/src/seeds/listings/listing-triton-seed.ts, backend/core/test/listings/listings.e2e-spec.ts
Addresses #1663
With the changes to application methods, our seed data listings now need to uniquely create application methods tied to each specific listing. The bug we were visually seeing was that only one of our seed data listings had `Apply Online` showing when they should all show `Apply Online` because only one listing had the `Internal` application method tied to it.
I also updated the listings importer to properly add application methods (and fixed an existing bug around reserved community type).
Re-seed the database and check the listings for `Apply Online`, as well as importing a new listing with the `Internal` application method and a `reservedCommunityType`.
=> 1663/when seeding data, create application methods unique to each listing

ui-components/__tests__/overlays/Modal.test.tsx, ui-components/src/overlays/Modal.tsx
Addresses https://github.com/CityOfDetroit/bloom/issues/412
The empty footer was being displayed when no actions were present, so we make the actions prop optional and hide the footer when it is not present.
Unit tests passed and visual inspection showed the footer not present in the modal when actions were not passed.
=> Make actions an optional prop and hide the footer when not present.

sites/public/src/ListingView.tsx, ui-components/__tests__/page_components/LeasingAgent.test.tsx, ui-components/src/locales/general.json, ui-components/src/locales/general_OLD.json, ui-components/src/locales/vi.json, ui-components/src/locales/zh.json, ui-components/src/page_components/listing/listing_sidebar/LeasingAgent.tsx
This change adds a field to the `LeasingAgentProps` to optionally include data (name and website URL) about the listing management company. If present, the management company name and a link to the website will be shown in the `ListingView`. Screenshot:
To view this change locally, it'll be necessary to make a change to `sites/public/src/ListingView.tsx` (to pass in the `managementCompany` prop to the `LeasingAgent` component).
=> Add two lines to the LeasingAgent UI component to display information about the listing management company

CHANGELOG.md, sites/partners/pages/index.tsx
Addresses #1760
Adds the "None" label instead of "Invalid date" text if a date is not defined.
Open the listings page in the partners and find a listing with no due date (e.g: TEST: DEFAULT, FCFS). In the "Application due date" column you should see the "None" label.
=> 1760/add none label if applicationDueDate does not exist

CHANGELOG.md, sites/partners/pages/index.tsx
Addresses #1687
See @slowbot  comment: https://github.com/bloom-housing/bloom/issues/1687#issuecomment-915309807
The goal is to reset a page to 1st on limit change.
Open partners and set 8 as items limit, then move to the next page and change limit to e.g. 100. The table should list items and the page should be 1st.
=> Reset page to 1 on limit change

CHANGELOG.md, sites/public/pages/applications/household/add-members.tsx, ui-components/__tests__/forms/HouseholdMemberForm.test.tsx, ui-components/src/forms/HouseholdMemberForm.stories.tsx, ui-components/src/forms/HouseholdMemberForm.tsx, ui-components/src/global/text.scss
Addresses #1721
Removes business logic from HouseholdMemberForm component.
Start an application. At the household members part, add some household members, and click the edit button to ensure the routing works properly to each individual person.
=> 1721/remove business logic from HouseholdMemberForm component

CHANGELOG.md, sites/partners/lib/hooks.ts, sites/partners/src/listings/PaperListingDetails/DetailsUnitDrawer.tsx, sites/partners/src/listings/PaperListingForm/UnitForm.tsx, sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/Units.tsx, ui-components/src/forms/Field.tsx, ui-components/src/locales/general.json, ui-components/src/tables/StandardTable.tsx, yarn.lock
Addresses #1706
Adds the ability to create ami chart overrides in listings management, and also due to lots of state issues refactors the UnitForm component.
Create a new listing. Set an ami chart. Set an ami percentage from the dropdown (will pulls unique ami percentages from the selected dropdown). The table should populate with the ami chart values. Change one of the values (creating an override). Save the unit. Re-open the unit before saving the listing and ensure the override is still there. Change the percentage and the chart and ensure the override isn't sticky.
Save a listing with a unit with an overrides and view the details page for that unit and ensure the only value saved as an override is the one(s) that was overridden and that the default values aren't duplicated.
Ensure …
=> 1544/ami overrides + unit form refactor

commitlint.config.js, package.json, yarn.lock
`commitizen` is the cli that builds the commit message
`commitlint` lints the message to ensure it follows the conventional commit standard (just in case!)
=> chore: add conventional commit linting

CHANGELOG.md, sites/partners/src/listings/Aside.tsx, sites/partners/src/listings/PaperListingForm/index.tsx, ui-components/src/locales/general.json
Addresses #1772
When clicking the Publish button on a listing, it will show a confirmation prompt before saving the new `active` listing status.
Ensure the modal is displayed when attempting to publish a listing.
=> feat: Show confirmation modal when publishing listings

sites/partners/src/listings/PaperListingForm/UnitForm.tsx
Some form issues slipped through the AMI override PR and on current dev you can't do add listing --> open the unit form
Somehow lint issues also got through even though the job passed on the PR. I looked at adding the appropriate dependencies to all four dependency arrays and that broke functionality each time, so I'm disabling the rule in these cases.
=> fix unit form issues

backend/core/src/migration/1632428425207-update-ala-signup.ts
Alameda has a new notification sign-up URL. No issue, came out of a meeting with their team.
=> fix: update alameda's notification sign up URL

CHANGELOG.md, sites/public/pages/listings.tsx, ui-components/__tests__/page_components/ListingCard.test.tsx, ui-components/src/page_components/listing/ListingCard.scss, ui-components/src/page_components/listing/ListingCard.stories.tsx, ui-components/src/page_components/listing/ListingCard.tsx
Addresses #1879
Allows for new optional subheader prop on ListingCard as well as optional classnames to style both headers.
New Storybook story
=> feat: new subheader prop and custom class names on ListingCard

CHANGELOG.md, backend/core/src/applications/applications.service.ts, backend/core/src/applications/dto/application.dto.ts, backend/core/src/applications/entities/application.entity.ts, backend/core/src/migration/1632218920979-add-confirmation-code-to-application.ts, backend/core/src/seeds/applications.ts, backend/core/test/applications/applications.e2e-spec.ts, backend/core/types/src/backend-swagger.ts
Addresses # (https://github.com/bloom-housing/bloom/issues/1074)
Add random 8 character hex string confirmation code to applications. Existing applications confirmationCode addition is handled by a migration.
=> Add random 8 character hex string confirmation code to applications

CHANGELOG.md, sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/AdditionalEligibility.tsx, ui-components/src/overlays/Overlay.tsx
Addresses #1961
Modals in LM (publish, close) were preventing page scroll after being closed.
In LM try close a published listing, and ensure you can scroll on the page afterward.
=> fix: modals no longer prevent scroll after being closed

.github/workflows/pre-release_components.yml
The action is failing for auth reasons, but that's actually a good thing for now because it seems it wants to version every package even if one changed, so I'm purposefully not fixing the auth issue to let it version and then fail to commit those versions to iterate on the getting the version bumps solid.
=> chore: update auto-release scripts, token on checkout

CHANGELOG.md, sites/partners/lib/formatApplicationData.ts
This PR addresses #2094
Before fixing, the paper form (only, the public app saves fields correctly) saved the last name as a first name.
1. Submit a new paper application with the first, middle, and last name.
2. In the summary, verify if the data is correct.
If you have one commit and message, squash. If you need each …
=> fix: Updates lastName on application save

backend/core/src/migration/1635546032998-add-jurisdictional-email-signatures.ts, backend/core/src/seed.ts, backend/core/src/seeds/listings/listing-default-sanjose-seed.ts, backend/core/src/shared/email/email.service.spec.ts, backend/core/src/shared/email/email.service.ts, backend/core/src/views/partials/footer.hbs
This PR addresses #2082 #2086
If no jurisdiction is passed to an email, don't include a jurisdictional footer (previously was always saying Alameda's).
If a specific jurisdiction is passed, use a jurisdictional-specific footer (new ones for San Jose and San Mateo).
I restructured a little how we are storing the translations to reduce duplication. We had a lot duplicated between the general translations and Alameda's. Now we have a general object and overwrite it where we need to with jurisdictional specific ones.
Doesn't support adding multiple jurisdictional footers atm, which I don't think was requested anyway, so it's one jurisdiction's footer or none.
On partners:
* Create listings specific to Alameda, San Jose, and San Mateo (it's fine if they're drafts)
* On the users piece, add a …
=> feat: jurisdictional email signatures

backend/core/src/auth/dto/user-profile.dto.ts, backend/core/src/auth/entities/user.entity.ts, backend/core/src/migration/1634848388161-add-phone-number.ts, backend/core/test/user/user.e2e-spec.ts, backend/core/types/src/backend-swagger.ts
Add a phone number column to the user_accounts table.
This change adds a phone number to the user_account table, adds the corresponding migration, and updates the swagger API.
0. Start a local server via `yarn dev:all`.
1. Go to http://localhost:3100/docs and use the auth/login endpoint to log in as one of the test accounts.
2. Use the auth token to set the bearer token for subsequent requests (click the lil' "lock" icon, and paste the auth token)
3. GET the user JSON through the user endpoint
4. Paste the user JSON into the request body of the PUT user/{id} endpoint, and modify the phone number field
5. GET the user JSON again through the user endpoint, and verify the phone number was set.
To run the added test:
`cd backend/core && yarn test:e2e:local --testPathPattern user.e2e-spec` …
=> Add a phone number column to the user_accounts table

backend/core/src/seed.ts, backend/core/src/seeds/listings/listing-coliseum-seed.ts, backend/core/src/seeds/listings/listing-default-one-preference-seed.ts, backend/core/src/seeds/listings/listing-default-sanjose-seed.ts, backend/core/src/seeds/listings/listing-default-seed.ts, backend/core/src/seeds/listings/listing-triton-seed.ts, backend/core/src/seeds/listings/shared.ts, sites/partners/cypress/fixtures/listingImage.json, sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
This PR addresses #1837 
This updates the seeds so that each jurisdiction has different preferences by adding ` - <Jurisdiction Name>` to each preference and assigning them to their corresponding jurisdictions.
Run `yarn db:reseed` and you should see different preferences for each jurisdiction. If you got to the L.M. form, you should be able to select different preferences in relation to the jurisdiction selected for that listing. …
=> feat: adds jurisdictions to pref seeds

backend/core/src/migration/1620660845209-seed-translation-entries.ts, backend/core/src/shared/email/email.service.ts, sites/partners/cypress/fixtures/listingImage.json, sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
This PR addresses #2192
This removes a sentence from the lottery section of the email confirmation. It also updates the logic in the email service to base lottery/noLottery off of the listing review order type.
This includes an update to the seeds for local and dev, but I will also run the following SQL to update it in other environments:
```
update translations set translations = jsonb_set("translations"::jsonb, '{confirmation, whatToExpect, lottery}', to_jsonb('Applicants will be contacted by the agent in lottery rank order until vacancies are filled.'::text)) where id = <translation id to update>
```
Reseed and apply to a listing that has a review order type of "lottery" (set the lottery radio on the L.M. form). The email confirmation should no longer have the sentence with the lottery …
=> feat: updates email confirmation for lottery

ui-components/__tests__/actions/Button.test.tsx, ui-components/src/actions/Button.tsx
Add ariaLabel as a prop to the Button component. This is used in https://github.com/CityOfDetroit/bloom/pull/753 to make our icon buttons accessible.
Ran `yarn test` on ui-components.
=> Add ariaLabel prop to Button component

sites/public/lib/hooks.ts
This rewraps public's fetchBaseListingData with a try catch, so build in cypress passes (it's dependent on the backend and should be handled differently in the long run).
=> fix: fetchBaseListingData

sites/partners/src/listings/PaperListingForm/index.tsx
This PR addresses #2189 
The code that was generating the event data for the lottery results PDF wasn't actually getting added to the data being saved from the frontend to the API. That's now been fixed.
Try to add and save a Lottery Results PDF in the Listing Admin.
If you have one commit and message, squash. If you …
=> fix: lottery results uploads now save

sites/public/src/forms/applications/FormSummaryDetails.tsx
This PR addresses #2261
This fixes an issue where if you fill out an application with one set of preferred units under an account, then apply to another listing with different preferred units, the translation string would be wrong.
Complete an application with SRO as an available unit type and choose SRO as your unit type preference
Create an account with that application
Apply to another application logged in
You should see this on your last application summary string …
=> fix: prefUnits on autofill summary

backend/core/src/shared/units-transformations.ts
This issue came up because there are jurisdictions like San Mateo and San José on production, that don't have ami charts, but units were added to listings with those jurisdictions before we tied ami charts to jurisdictions. This is marked as only a partial fix, because while it does fix the issue, we also need to add the ami charts, which are in progress at least for SJ.
You can test this by:
1. create a new draft listing with
2. create a unit and select an ami chart (there should be one per jurisdiction from the seed)
3. save the listing
4. in your local db, reassign the ami chart you selected to a different  jurisdiction
5. edit the listing and one of the overrides on the listing (you shouldn't be able to select an ami chart now)
6. save the listing and you …
=> fix: units with invalid ami chart

sites/public/pages/account/dashboard.tsx, sites/public/pages/create-account.tsx, sites/public/src/ConfirmationModal.tsx, ui-components/src/locales/es.json, ui-components/src/locales/vi.json, ui-components/src/locales/zh.json, ui-components/src/notifications/AlertBox.tsx
This PR addresses #2285 #1238 #2297
In all languages:
* Every string on the new race options checkboxes at http://localhost:3000/applications/review/demographics
* Every string on http://localhost:3000/sign-in (note that email in Spanish and Vietnamese is email)
* Every string on http://localhost:3000/create-account (except for birth date placeholder text)
Note: I also created #2298 because as part of this I realized that alert boxes are not currently translated. I fixed the one account confirmation alert box here and created the issue to follow up on all the others.
- Also review the acceptance criteria on …
=> chore: missing translations

ui-components/src/headers/Hero.scss, ui-components/src/headers/Hero.tsx
This PR addresses a release bug with [DAH-968](https://sfgovdt.jira.com/browse/DAH-968)
Around 777px, we were seeing that button text for secondary hero buttons was cut off for spanish
This PR switches from 6 to 4 columns and tweaks the max width of the div to make the buttons look OK in spanish at any size. 
1. Open up `/?path=/story/headers-hero--with-secondary-button` on the review app, and check the styles at varying screen widths.
2. Manually update the buttons to longer strings (e.g. "Aquilar" and "Comprar") and see that they aren't cut off
3. Verify that the buttons don't get comically large at larger screen sizes …
=> fix: fix hero button width with secondary button

.github/workflows/pre-release_components.yml, package.json
If a pre-release version already exists, bump to the next version
=> fix: force a release number if one exists

sites/public/pages/forgot-password.tsx, ui-components/src/page_components/sign-in/FormSignIn.tsx
Consumers are currently unable to uptake ui-components because we re-added a nextjs dependency - this PR just removes it.
Ensure the forgot password link still works as expected.
=> fix: remove next dependency from ui-components

backend/core/src/seeder/seeds/ami-charts/default-ami-chart.ts, sites/partners/src/listings/PaperListingForm/UnitForm.tsx
This PR addresses #2364 
This updates the unit form so that ami charts correctly populate the household data (before it assumed that all household sizes (1-8) had a value for each ami percentage. This also adds 120 percentages to one of the seeds.
Pull this down and reseed. Edit or create a new listing and add a unit and select `AlamedaCountyTCAC2021` with `120` as the percentage. You should see incomes for household sizes of 3, 4 and 5. You should be able to enter overrides and save.
- …
=> fix: ami charts without all households

ui-components/.jest/setup-tests.js, ui-components/index.ts, ui-components/src/helpers/useIntersect.ts, ui-components/src/page_components/listing/ListingMap.scss, ui-components/src/page_components/listing/ListingMap.stories.tsx, ui-components/src/page_components/listing/ListingMap.tsx
This PR addresses #2413 
This PR adds a new `useIntersect` React hook which will supply state to control the visibility of an element relative to
an ancestor element (or by default the browser viewport). The map widget on listings then uses this so the map is only initialized once the browser scrolls down close to the map region (there's an extra buffer of 500 pixels).
Wait a beat after the listing has loaded, then scroll as fast as possible to the bottom of the listing, and you'll notice the map loads once it has become visible. Also you can reload & start at the top of the listing, and scroll down slowly, and likely by the time you get to the map it will have already loaded.
- Pull …
=> feat: only show MapBox map when it's in the viewport

ui-components/src/blocks/ImageCard.scss, ui-components/src/blocks/ImageCard.stories.tsx
This PR addresses #2267
Makes the image card gradient less harsh on mobile and to have it cover less of the image. Also makes both the desktop and mobile versions be less harsh in Firefox and Safari.
There may be some slight color contrast issues when the ImageCard text wraps on three lines on mobile on a shorter image. Since this is a small category of listings (likely less than 5 on DAHLIA, and none of Bloom) and the current solution to that makes all the cards look worse, we are going to accept that in the short term as we are about to pick up the re-design of the ImageCard titles.
This is a blocker for DAHLIA's release of the Listing Directory re-write.
You can look at the stories under ImageCard in the Storybook deploy preview.
- …
=> fix: image gradient obscures image on mobile, is harsh in safari (#2267)

ui-components/src/page_components/forgot-password/FormForgotPassword.tsx
Just copy/pasted two types from our shared-helpers library into a ui-component that was pulling them in because we don't want any shared-helpers dependencies in ui-components. We want shared-helpers have a dependency on our backend and we don't want that for ui-components. This change was also causing a build issue for consumers because we didn't add shared-helpers to ui-components dependencies.
Essentially no change just a copy pasta. You can see the two types I copied [here](https://github.com/bloom-housing/bloom/blob/7faf3a2b382ee2c7840e870e25d22bfc960d1256/shared-helpers/src/catchNetworkError.ts#L5).
=> fix: remove shared-helpers dependency from FormForgotPassword

ui-components/src/page_components/sign-in/FormSignIn.tsx
Removing a dependency on shared-helpers from ui-components
=> fix: remove shared-helpers dependency from FormSignIn

sites/public/pages/preview/listings/[id].tsx, ui-components/src/notifications/AlertBox.scss, ui-components/src/notifications/AlertBox.tsx
This PR addresses #2157 & #2249
There was an accessibility improvement to be made to the `AlertBox` component. In addition, the preview notice bar when previewing a listing being edited wasn't actually using a real `AlertBox` at all, so now it is.
You can view the `AlertBox` in Storybook, or if you try to log in on public/partners and use the wrong credentials. Using VoiceOver, you can verify the alert icon isn't announced by the screen reader, and that the X close button is announced as "close alert".
In addition, you can verify the correct visuals of the preview bar when [previewing a listing](https://deploy-preview-2497--dev-bloom.netlify.app/preview/listings/b832fd76-b212-46ec-9a07-18ac795a5c54).
- Review the code itself from a …
=> fix: use the correct AlertBox component for preview listing notice

sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/ListingIntro.tsx
- [ x] This change addresses the issue in full
This fix resolves the issue where "you must first select a jurisdiction" was blocking users from setting the program when a default jurisdiction is set. This issue was initially found at https://github.com/CityOfDetroit/bloom/issues/1080.   
This issue can be tested by creating an admin user with one listing assigned to them from a single jurisdiction. Once this is set, create a new listing and attempt to add programs to that new listing. Additionally, editing existing listings from a single jurisdiction can test persistence of the program information.
- [x ] My code follows the style guidelines of this project
- …
=> fix: select programs working with single jurisdiction

docs/pull_request_template.md
Updates the PR template to include reminders about adding QA notes to the associated issue.
=> chore: update pr template to include qa note reminders

sites/partners/pages/forgot-password.tsx, sites/partners/pages/sign-in.tsx, sites/public/pages/forgot-password.tsx, sites/public/pages/sign-in.tsx, ui-components/src/page_components/forgot-password/FormForgotPassword.tsx, ui-components/src/page_components/sign-in/FormSignIn.tsx, ui-components/src/page_components/sign-in/FormSignInAddPhone.tsx, ui-components/src/page_components/sign-in/FormSignInErrorBox.tsx, ui-components/src/page_components/sign-in/FormSignInMFACode.tsx, ui-components/src/page_components/sign-in/FormSignInMFAType.tsx
Removes shared-helper and axios dependencies from ui-components
(1) We don’t want shared-helpers to be used in ui-components at all because we need shared-helpers to have our backend as a dependency and we don’t want the backend in the component library, and (2) if we were going to add shared-helpers to the component library it would also need to be added explicitly to the ui-component package json, and since it isn’t, that is what right now is breaking consumers with errors “could not resolve shared-helpers”. The long term fix is to refactor those components to use much more generic props that don’t relate to network status, and to get our build CI job up and running.
=> fix: remove shared-helpers dependency from ui-components

ui-components/src/blocks/FormCard.tsx
This PR addresses #2204 
This pull request adds screen reader compatibility to the public housing application, reading listing names first on each application page. Instead of putting listing names in the page titles (which show in browser tabs), this was a much simpler solution - swapping the h5 tag in the FormCard ui-component for h1, which is automatically read by the screen reader.
Navigate to a housing application in public. 
Turn on screen reader (press F5 on mac).
While traversing through the application, the screen reader should read the listing name first on every application page.
- Read and understand the issue, and ensure the author …
=> fix: swap listing name h5 with h1 for screen reader compatibility

ui-components/__tests__/headers/SiteHeader.test.tsx, ui-components/src/headers/SiteHeader.stories.tsx, ui-components/src/headers/SiteHeader.tsx
One more small change to fix accessibility issue on home page Language Nav component. Adding an optional `languageNavLabel` prop to the SiteHeader component which will include an `aria-label` attribute on the LanguageNav component
Related to https://github.com/bloom-housing/bloom/pull/2624 We need the ability to pass the aria label to the Language Nav component which is called by the Site Header component.
Inspect the Site Header with Language story in storybook. You should now see an aria-label
`<nav aria-label="Choose a Language" class="language-nav">`
- Also review …
=> Add optional prop for Language Nav aria label

backend/core/src/auth/controllers/auth.controller.ts, backend/core/src/auth/dto/token.dto.ts, backend/core/types/src/backend-swagger.ts
This fixes an issue with the client using the Authservice.token method to refresh the token. The generated token client was passing null in for data, which is not valid JSON. This addresses that by specifying an ApiBody with an empty object, so that the generated client passes an empty object instead of null.
The easiest way to test this locally is to modify the `expiresIn` value on line 35 of `backend/core/src/auth/auth.module.ts` so you don't have to wait the ten minutes. Sign in to the partners portal, watch the network tab and see the calls to /auth/token be successful.
- Pull the changes down locally and test that the acceptance criteria …
=> fix: authservice.token data null issue

backend/proxy/Dockerfile, backend/proxy/default.conf, backend/proxy/shared-location.conf
This PR addresses #2710
This change adds nginx proxy caching configuration for GET `/jurisdictions/*` endpoints. 
Set up local nginx + backend:
1. Start backend with `yarn dev` on 3100 port (default)
2. in `backend/proxy/default.conf` change https to http in every `proxy_pass` config 
3. Go to backend/proxy directory and build nginx image with `docker build . -t bloom_nginx`
4. Start nginx proxy with `docker run -it --expose 80 -p 9000:80 -e PORT='80' -e BACKEND_HOSTNAME='[my ip]:3100' bloom:latest` where [my ip] can be retrieved from `ipconfig getifaddr en0` on MacOS.
5. Fetch GET /jurisdictions with `curl http://localhost:9000/jurisdictions` and observe first request in backend log, then fetch for the second time and you should not see any new logs as nginx should serve next response
6. …
=> feat(proxy): add nginx config for jurisdictions

backend/core/src/listings/dto/listing-published-create.dto.ts, backend/core/src/listings/dto/listing-published-update.dto.ts
This PR addresses [#1289](https://github.com/CityOfDetroit/bloom/issues/1289) (QA)
The change in the initial ticket resulted in not being able to publish any listing with `Available Units` selected, because `isWaitlistOpen` was being sent as null, and was listed as still being a required field on listing publish.
Ensure you can publish a listing with `Available Units` selected, and toggle between `Open Waitlist` with a waitlist size and then `Available Units`. …
=> fix: make isWaitlistOpen optional

backend/core/src/jurisdictions/entities/jurisdiction.entity.ts, backend/core/src/migration/1655309692011-flag-for-features.ts, backend/core/src/seeder/seeds/jurisdictions.ts, backend/core/src/shared/units-transformations.spec.ts, backend/core/test/jurisdictions/jurisdictions.e2e-spec.ts, backend/core/types/src/backend-swagger.ts, sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx, sites/partners/src/listings/PaperListingForm/sections/BuildingFeatures.tsx, sites/public/pages/listing/[id]/[slug].tsx, sites/public/pages/preview/listings/[id].tsx, sites/public/src/ListingView.tsx
This PR addresses adding a setting around exposure of accessibility features
This creates a jurisdictional setting that controls whether the new accessibility features is exposed or not
check out on partners side, by default the new accessibility features should not be showing on either the listing form, or the listing detail page
in the database update the new enableAccessibilityFeatures jurisdictional setting to be true on a jurisdiction your user has access too
the features should be showing up now
- Also review the acceptance criteria on the Netlify deploy preview …
=> feat: creating setting wall for accessibility feat

backend/core/src/seeder/seeds/jurisdictions.ts
At the moment on dev you are unable to send emails. This was an existing data issue surfaced by this [commit](https://github.com/bloom-housing/bloom/pull/2843/files#diff-68c2a0379eb7c1ee8cc5467d1333b6f7fe2eca6ee9a12c2b5dfe162180d358a3R69). We slightly changed how jurisdictions are being seeded such that the mock data in that file is now overwriting any jurisdictions we had added in the migrations. The migration files had the correct `emailFromAddress` but this file did not, so I just updated the values.
=> fix: fix email from address

ui-components/src/page_components/listing/listing_sidebar/ExpandableSection.tsx
No related issue, but a quick fix to unblock SF to allow for custom React styling in the expandable section. There are no breaking changes (see [existing stories](https://deploy-preview-2902--dev-storybook-bloom.netlify.app/?path=/story/listing-sidebar-expandable-section--default)).
=> fix: allow jsx in expandable section

ui-components/src/forms/Field.tsx, ui-components/src/forms/HouseholdSizeField.tsx, ui-components/src/forms/Textarea.scss, ui-components/src/global/forms.scss, ui-components/src/notifications/ErrorMessage.tsx, ui-components/src/page_components/sign-in/FormSignInErrorBox.tsx
increase the margin between error message and input field, add line height to error message text
#2911
There's been a request to decrease the line height and increase the top margin of the error message in the Field component. I figured it wouldn't hurt to use a className to increase customization.
Go into Storybook, look out the Field component example with a Text Field Error, modify the message (either through the debugger or storybook file) to be really long. Compare with the dev storybook and hopefully you can see a smaller line height (1.25 rem) and a top margin that matches the text input's label bottom margin.
Perform the same path above for the TextArea component
Additionally, inside storybook, trigger an error in the following components (by putting …
=> feat(errormessage): add classname to errormessage; apply styles to Field

backend/core/src/application-flagged-sets/application-flagged-sets.service.ts, sites/partners/src/flags/flagSetCols.tsx
this is a hotfix for: https://github.com/bloom-housing/bloom/pull/2946
it resolves a backend-crashing bug that happens when a user hits the flagged-set page on the partners site
=> fix: fix for big timeout on flagged set

ui-components/package.json, ui-components/src/helpers/MultiLineAddress.tsx, yarn.lock
A [recent pr](https://github.com/bloom-housing/bloom/pull/2914) replaced the dompurify library (which sanitizes html) with sanitize-html which broke DAHLIA (attached screenshot). This fix uses the <Markdown /> component (which we already have access to via [markdown-to-jsx](https://www.npmjs.com/package/markdown-to-jsx) lib) which does some basic sanitization - although it's a bit hard to find out exactly what sanitization it does when the disableParsingRawHTML is set to false, it at least removes script tags! 
Just because this is blocking uptakes on dahlia, it'd be nice to fast track this! I'm open to reworking this with a different, longer-term solution. Also open to any other quick, potentially temporary fixes.
- Ensure …
=> fix: replace usage of sanitize-html

backend/core/src/listings/db/listing-query-builder.ts, backend/core/src/listings/types/listing-orderby-enum.ts, backend/core/src/seeder/seeds/listings/listing-default-seed.ts, backend/core/src/seeder/seeds/listings/listing-triton-seed.ts, backend/core/types/src/backend-swagger.ts, sites/public/lib/hooks.ts
This PR addresses #1740
Using the "published_at" field instead of the "application_open" field to determine the sorting of the listings seen on the listings page. Also added published_at to a majority of the seeded listings so that it can be tested locally.
Load the listings page and make sure that the listings are ordered based on published date. The dev environments have a lot of listings without published date so sorting might not be as noticeable.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend …
=> feat(listings): update default sort of listings

sites/partners/src/listings/PaperListingForm/sections/AdditionalDetails.tsx, sites/partners/src/listings/PaperListingForm/sections/AdditionalEligibility.tsx, sites/partners/src/listings/PaperListingForm/sections/AdditionalFees.tsx, sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx, sites/partners/src/listings/PaperListingForm/sections/BuildingFeatures.tsx
This PR addresses #2609 
The padding issue on the add listing form in mobile has to do with how the grid component is being used in the forms. By removing the additional layer of GridSection the mobile view can switch to the single column and still have the correct padding. Let me know if there is a use case that I am unaware of where the current style is needed
Things to note: 
- This works on both desktop and mobile for "add listing", but if you edit a current listing the width of the form doesn't work properly in mobile due to one of the tables. This is also happening in the dev site.
- Pull the changes down locally and test that the …
=> fix(paperlistform): adjust padding on add listing form

sites/partners/page_content/locale_overrides/general.json, sites/partners/src/listings/Aside.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx, sites/partners/src/listings/PaperListingForm/sections/LotteryResults.tsx
This PR addresses #2463
When a Lottery Result already exists and a user clicks to Edit it the page now shows "Edit Results" instead of "Add Results". It also shows the file that is currently uploaded instead of the dropzone.
After a user deletes the pdf the dropzone re-appears and the "post" button turns into "save". When it is saved the lottery result event is cleaned up from that listing rather than just deleting the file name associated to it.
Select a listing that is closed and has a lottery result already posted. Click "EDIT". Then click on the "Results Posted..." edit link. Should see "Edit Results" and the currently saved results shown. Ability to delete it as well.
There are currently no tests around the lottery results feature. I am willing to add tests but don't know if we want …
=> feat(lottery): add edit lottery results functionality

backend/core/src/auth/passport-strategies/local-mfa.strategy.ts, backend/core/test/user/user.e2e-spec.ts, shared-helpers/src/catchNetworkError.ts, ui-components/src/locales/es.json, ui-components/src/locales/general.json, ui-components/src/locales/tl.json, ui-components/src/locales/vi.json, ui-components/src/locales/zh.json
This PR addresses #2903 
This PR fixes the incorrect implementation of entering the wrong password too many times. Currently the incorrect count is getting updated correctly and also resetting correctly when a user finally signs in correctly. However, the last login time is not getting updated so the check for if they have waited the 30 minutes is always passing. 
Also this updates the UI to read the remaining attempt count in the error message displayed.
On the sign in page attempt to log in with a valid email (known user) but the incorrect password. Should get the error message with "5" failed attempts.
Repeat 4 more times and the error message should increment down.
On the sixth wrong one the lockout error should appear and not able to login or get the original error message for an …
=> fix(login): too many login attempts fix

sites/public/src/ListingView.tsx, ui-components/src/page_components/listing/AdditionalFees.stories.tsx, ui-components/src/page_components/listing/AdditionalFees.tsx
This PR addresses #3008
Prevents the application section from showing a `null` string in the fee field, and hides the whole section if there is no data.
(1) Checkout listing/af6c3dc9-e6a1-4deb-8d7c-08675b148e3e on [dev](https://dev-bloom.netlify.app/listing/af6c3dc9-e6a1-4deb-8d7c-08675b148e3e/emily_jablonski_1380_w_12_th_ave_broomfield_co) vs this branch's public [preview](https://deploy-preview-3016--dev-bloom.netlify.app/listing/af6c3dc9-e6a1-4deb-8d7c-08675b148e3e/emily_jablonski_1380_w_12_th_ave_broomfield_co), and ensure it doesn't show null for app fee.
(2) Checkout listing/c324cf20-9f58-4ba5-89e4-67dc861ab1ec on [dev](https://dev-bloom.netlify.app/listing/c324cf20-9f58-4ba5-89e4-67dc861ab1ec/kathy_cheng_67_montezuma_st_san_francisco_ca) vs this branch's public …
=> fix: null app fee

backend/core/src/migration/1661805250707-programAndPreferenceUpdates.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3007)
This covers the migration for updating application data for programs and preferences. What we were running into was that old data (program/preference data) and new data (multiselect question data) existing on applications for a listing was causing the application export to create duplicate columns. This migration should merge that data together into the new way
okay so testing this is kind of a pain locally, my recommendation is to go as follows:
1) before checking this branch out run a reseed
2) check this branch out
3) insert data into the following tables: 
```
SELECT
*
FROM programs;
SELECT
*
FROM preferences;
SELECT
*
FROM listing_programs;
SELECT
*
FROM listing_preferences;
```
4) update data in the …
=> fix: migration for application export clean up

backend/core/src/shared/units-transformations.ts, shared-helpers/src/summaryTables.tsx
This PR addresses #3035
While not passing rent and income values, we've sent probably `null` value that was processed anyway as valid number, so while formatting `parseFloat` returned `NaN`.
Now instead of `$NaN per month` it displays as `N/A per month` etc.
Not sure if that should also contain `$` before `N/A`
We need to have listing where in listing units we select nothing in `How is Rent Determined?`. While editing listing just remove existing values, at first it can throw error while saving, but after open listing unit and saving it again it should work fine.
- …
=> fix: return N/A if rent and income is NaN

shared-helpers/src/multiselectQuestions.tsx, sites/partners/src/applications/Aside.tsx, sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx, sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx, sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx, sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx, sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx, sites/partners/src/listings/PaperListingForm/sections/LotteryResults.tsx, sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx, sites/partners/src/listings/PaperListingForm/sections/Units.tsx, sites/partners/src/users/FormUserManage.tsx, sites/public/pages/applications/contact/address.tsx, sites/public/pages/applications/contact/alternate-contact-type.tsx, sites/public/pages/applications/contact/name.tsx, sites/public/pages/applications/financial/income.tsx, sites/public/pages/applications/financial/vouchers.tsx, sites/public/pages/applications/household/changes.tsx, sites/public/pages/applications/household/member.tsx, sites/public/pages/applications/household/preferred-units.tsx, sites/public/pages/applications/household/student.tsx, ui-components/src/forms/DOBField.tsx, ui-components/src/forms/Field.tsx, ui-components/src/forms/FieldGroup.tsx, ui-components/src/forms/HouseholdSizeField.tsx, ui-components/src/global/forms.scss, ui-components/src/notifications/AlertBox.scss, ui-components/src/page_components/sign-in/FormSignInErrorBox.tsx, ui-components/src/tables/StandardTable.stories.tsx
#3078 Just noticed a few visual discrepancies we have in the application on error states when I was walking through page by page comparing to SF, and fixing a bug for SF around showing error states in field labels.
To test: Walk through the application and at every page, try to submit without filling anything out.
Ensure that when a required field is in an error state, that the field itself as well as its label is red.
Additionally, ensure that when data is entered into a field in an error state, that updating the field removes the error state.
=> refactor: cleanup application error state styles

backend/core/src/migration/1664300247901-setsAfsLastRunAt.ts
This sets the afsLastRunAt to "now" so that we don't have re-process everything.
=> feat: adds setsAfsLastRunAt1664300247901 migration

sites/partners/page_content/locale_overrides/general.json, sites/partners/pages/application/[id]/applicationsCols.tsx, sites/partners/pages/listings/[id]/applications/pending/index.tsx, ui-components/src/global/vendor/ag_grid.scss
Two small frontend issues from the duplicates bash
(1) Use a translation string for the closed listing alert
(2) Accessibility color contrast issue on the application link when the row is selected
=> fix: duplicates ux issues

ui-components/src/sections/InfoCardGrid.scss, ui-components/src/sections/InfoCardGrid.tsx
Pulling [this](https://github.com/housingbayarea/bloom/pull/494) fix into core - it was a hotfix so no issue was created, happy to make one though!
=> fix: heading size issues on resources page

backend/core/src/email/email.service.ts, backend/core/src/listings/dto/listing-published-create.dto.ts, backend/core/src/listings/dto/listing-published-update.dto.ts, backend/core/src/listings/entities/listing.entity.ts, backend/core/src/listings/listings.service.ts, backend/core/src/listings/types/listing-availability-enum.ts, backend/core/src/listings/types/listing-review-order-enum.ts, backend/core/src/listings/views/config.ts, backend/core/src/migration/1663959354563-new-listing-type-enum.ts, backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts, backend/core/src/seeder/seeds/listings/listing-triton-seed.ts, backend/core/src/seeder/seeds/listings/shared.ts, backend/core/src/shared/units-transformations.ts, backend/core/types/src/backend-swagger.ts, shared-helpers/src/summaryTables.tsx, sites/partners/__tests__/PaperListingForm/sections/DetailUnits.test.tsx, sites/partners/__tests__/testHelpers.ts, sites/partners/cypress/integration/03-listing.spec.ts, sites/partners/pages/_app.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailUnits.tsx, sites/partners/src/listings/PaperListingForm/formTypes.ts, sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts, sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx, sites/partners/src/listings/PaperListingForm/sections/Units.tsx, sites/public/lib/helpers.tsx, sites/public/src/ListingView.tsx
This PR addresses #3081
At the moment for all the what to expect updates that are based on this new "3 types of listings" model, we are checking 2 different fields in order to determine the full listing’s type which has 3 distinct categories (fcfs, lottery, waitlist) ([slack context](https://exygy.slack.com/archives/C01Q4QG5R8Q/p1663353081218739?thread_ts=1663342872.080439&cid=C01Q4QG5R8Q)). At the moment we have to check `listingAvailability` to see if that is `openWaitlist` and also `reviewOrderType` to see if that's `fcfs` or `lottery`.
We want to consolidate the unit waitlist question with the rankings and results question so we have one field we have to check for listing type, and also disable the lottery/fcfs question if waitlist is selected for units so that we cannot have …
=> feat: new listing type field

backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-boostrap.service.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-consumer.ts, backend/core/src/listings/listings-cron.service.ts, backend/core/src/shared/shared.module.ts
The changeOverdueListingsStatusCron in the listings cron service is actually running, but the logging level of non-local development is just "warn" and "error". So this PR changes the logging level for the two cron jobs from "log" to "warn".
Still digging into why the other cron job is not working. I believe it is related to redis, but by having this logging level correct we will know if it is getting triggered
=> fix: change the cron job logging level

.github/workflows/release_components.yml, README.md
This triggers the release step on merges to the `main` branch. Currently releases are currently only made when things get merged to `dev`. However, with the change of not using the dev branch we need to change it to the `main` branch. Along with this we also want to not do the pre-release and instead just do a full release of ui-components when a change is merged
=> feat: get rid of ui-component prerelease

ui-components/src/page_components/listing/listing_sidebar/QuantityRowSection.stories.tsx, ui-components/src/page_components/listing/listing_sidebar/QuantityRowSection.tsx, ui-components/src/page_components/listing/listing_sidebar/events/EventSection.stories.tsx, ui-components/src/page_components/listing/listing_sidebar/events/EventSection.tsx
This PR addresses #3144
At the moment in both of these components, we were allowing consumers to pass in custom JSX for certain props, but we were always nesting it in a `<p>` tag, which was causing nesting tag errors if the consumer content also contained `<p>` tags, so we needed to optionally render it with the tag only if the prop type is just a string.
Ensure existing stories have no visual regressions, and that the two custom content stories ([1](https://63729c3df23a7a000826ccf0--amazing-davinci-96c1cd.netlify.app/?path=/story/listing-sidebar-events-event-section--fragment-note) [2](https://63729c3df23a7a000826ccf0--amazing-davinci-96c1cd.netlify.app/?path=/story/listing-sidebar-quantity-row-section--custom-description)) also have no regressions or console errors (they have been …
=> fix: support jsx in EventSection, QuantityRowSection

backend/core/src/applications/applications.controller.ts, backend/core/src/auth/controllers/user.controller.ts, backend/core/src/listings/listings.controller.ts, backend/core/src/multiselect-question/multiselect-question.controller.ts, backend/core/types/src/backend-swagger.ts, sites/partners/lib/hooks.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3166)
This adds uuid validation to a few of our endpoints that previously let them through
This shouldn't affect any of the regular usage. So going to partner's and viewing individual listings, and going to an application's page then that works 
what this should prevent is if you were to navigate to the listing's page then by hand trim the UUID in the url to no longer have all the parts …
=> feat: adding UUID validation

sites/partners/pages/_app.tsx, sites/public/pages/_app.tsx
I mentioned this in standup ~2-3 weeks ago but the performance of the dynamic a11y linting we added is pretty significant in local development. #3051 was created but hasn't been prioritized. In the meantime I'd love to just comment it out to speed up local dev.
=> refactor: table a11y dynamic linting until performance issues are resolved

backend/core/src/listings/entities/listing-event.entity.ts, backend/core/src/migration/1668076003953-add-start-date.ts, backend/core/src/seeder/seeds/listings/listing-default-lottery-pending.ts, backend/core/src/seeder/seeds/listings/listing-default-lottery-results.ts, backend/core/src/seeder/seeds/listings/shared.ts, backend/core/types/src/backend-swagger.ts, shared-helpers/src/events.ts, shared-helpers/src/stringFormatting.ts, sites/partners/src/listings/PaperListingForm/formatters/EventsFormatter.ts, sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx, sites/public/src/ListingView.tsx
This PR addresses #3130
Date and time was stored in one field `startTime` i separated it to `startDate` for just date, and `startTime` for just time. 
Pick one listing and set its application process to lottery. Check if you can pass each date/ time field in section separately (so after saving and going back it will be there). Check public lottery section in public listing view, it should have few states:
- hidden - when no date, start time, and end time irrelevant.
- display only date - date filed, no start time, end time irrelevant
- display date + start time - date filled, only start time (or start time and end time same)
- display date + start time + end time - all filled …
=> feat: add startDate field to listing events

backend/core/.env.template, backend/core/src/app.module.ts
once deployed this should (hopefully) get it so that the new cookies are stored properly on hosted environments 
associated readings: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
=> fix: resolves cookies not storing issue

package.json
Changes the order of our commit message linting - now runs the conventional commit formatter before the linter. Previously, if linting failed, sometimes the only way to get past [failures from ignored files](https://github.com/eslint/eslint/issues/15010) was to commit with `--no-verify` which then skipped the conventional commit check linter.
To test this, in a component file locally, add a variable you don't use and try to commit with a valid conventional commit formatted message. Linting should run and the commit should fail.
Then try to commit in a not-conventional-commit format w/out a lint error (i.e. just `test`) and that should fail.
=> chore: run commit message formatter before linter

backend/core/src/shared/units-transformations.spec.ts, backend/core/src/shared/units-transformations.ts
This PR addresses [586](https://github.com/housingbayarea/bloom/issues/586)
The HMI table on the public listing details page currently shows a table for all housing sizes up to the max household all units have. It does not take in to account that units also have a minimum occupancy count. So for example a property that has a minimum household of size 4 is still showing the rows for household of size 1, 2, and 3. 
This change takes the minimum into account and only displays the range that are eligible. There is also one edge case that is handled where the minimum is larger than 8 (or the largest value in the table) we will still show 8 (or largest value). This case hasn't come up yet, but could in the future. A follow up PR will tackle the language change to "8+".
Additionally if there is …
=> fix: limit hmi table to min and max occupancy

sites/partners/__tests__/pages/settings/index.test.tsx, sites/partners/__tests__/pages/users/index.test.tsx
This fixes the two broken partner unit tests with the auth cookie change. It is pointed to the cookie update PR
1. Update the mock service worker urls to point to the new `/api/adapter/` endpoint
2. The token is no longer set as a session storage. So to simulate a logged in user we now need to set the cookie
=> fix: fix partner unit tests

.gitignore, sites/partners/__tests__/pages/users/index.test.tsx, sites/partners/page_content/locale_overrides/general.json, sites/partners/src/lib/hooks.ts, sites/partners/src/pages/listings/[id]/applications/index.tsx, sites/partners/src/pages/users/index.tsx
This PR addresses #3282, https://github.com/CityOfDetroit/bloom/issues/1594
This carries over all of the fixes from the bug bash we did on Detroit's export CSV feature. 
It fixes the following things:
- Change "Export" to "Export to CSV"
- Unify the success message location in translation file
- Make the success toaster more determinant. (doesn't reappear randomly)
- Make the buttons the bigger size
Unrelated to the user export it also adds the success toaster to the application export feature since we now get that functionality for free.
Go to the users page on the partners site and click "Export to CSV". The success toaster should appear and not reappear later until you click the export button again
- Read and understand the issue, and ensure the author has added …
=> fix: user export fixes

backend/core/src/application-flagged-sets/application-flagged-sets.service.ts, backend/core/src/applications/services/applications.service.ts, backend/core/src/migration/1680216626425-fixing-marked-as-duplicate-flag.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3227)
There was an issue where MarkedAsDuplicate on applications was not correctly capturing if the application had been marked as a duplicate or not. 
This has 2 pieces, 1st is a fix for new data coming in to markAsDuplicate correctly. The 2nd piece is a fix for existing applications data to set that field properly
Go to the partner's site
head to a listing with flagged applications
resolve an application, you should now see that marked as duplicate is set properly for the record that was selected, and for the record that was not selected
go back and set that record to be pending, you should see the marked as duplicate field updated properly
- Read and understand the issue, and ensure the …
=> fix: resolves issues around markedAsDuplicate

backend/core/src/applications/types/form-metadata/form-metadata-extra-data.ts, backend/core/src/applications/types/form-metadata/form-metadata-options.ts
This PR addresses [#606](https://github.com/housingbayarea/bloom/issues/606)
Right now on production if you have a preference with a long option name (>128 characters) that also collects an address, if you try to submit an application with that address filled out the submission fails. The form field key includes the option name + there is a max length applied on the backend. This PR removes that validator on the key.
Adding this preference and selecting it and adding an address will cause the application submission to fail on main.
Option name: `At least one member of my household was required to relocate from current Dublin residence due to demolition of dwelling or conversation of dwelling from rental to for-sale unit (1 point)` and `Collect the applicant address`. …
=> fix: remove max length from extra data app fields

backend/core/src/auth/dto/user-basic.dto.ts, backend/core/src/main.ts, backend/core/test/user/user.e2e-spec.ts, backend/core/types/src/backend-swagger.ts
This PR is related to the comment: https://github.com/metrotranscom/doorway/pull/47
We were exposing too much user data publicly with the leasing agent data that gets returned with a listing
This pr pulls out much of the sensitive data 
on the public site (not logged in) if you go to apply for a listing with the console open (keep tabs of network traffic) you should be able to see the data that gets returned from the call for that listing
you should no longer see sensitive data as part of the leasing agent data in that listing 
alternatively you could check localhost:3100/docs and verify the /listings endpoints return data set for a listing's leasing agent section is sensative-info-less
- …
=> feat: removing sensative info from leasing agent

shared-helpers/src/locales/es.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json
This PR addresses #3416
added translations
go for example to create-account -> type in first name with more than 64 characters, click create account. Now error should appear, test for all added languages.
If you have one commit and message, squash. If you need each message to …
=> fix: add translation for 64 characters error

backend/core/package.json, backend/core/src/seeder/seed.ts, yarn.lock
This PR addresses _Heroku deployment_
With the most recent change of moving the purge calls from partners to the backend the deployment to the heroku failed. This is due to the way we have our backend setup. The yarn lock file is at the base level of the bloom repo and when deploying the backend all it knows about is what is in the backend/core directory. Because of this it does not find a yarn lock file and instead tries to do a fresh install using npm and the package.json file. For the most recent change it grabs the version of `@nestjs/axios` specified in package.json (2.0.0) and tries to download all of the dependencies. We don't have a high enough version of axios that we are requesting so the install fails.
This PR solves that problem by downgrading @nestjs/axios which is ok with …
=> fix: downgrade version of nest axios

backend/core/src/listings/listings.service.ts, sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3418)
There is an issue where if a listing already has a building selection criteria of a pdf upload (or really any upload) then attempting to switch it to a url will store both with the upload taking precedence 
Go in to edit or create a listing
upload a file for the building selection criteria
this should save correcty
go back in to edit the listing and switch the building selection criteria to be a url
this should save correctly now too
- Also review the acceptance criteria on the Netlify …
=> fix: now removes criteria file if a url is input

sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx, sites/partners/src/components/listings/PaperListingForm/sections/AdditionalEligibility.tsx, sites/partners/src/components/listings/PaperListingForm/sections/BuildingDetails.tsx, sites/partners/src/components/listings/PaperListingForm/sections/CommunityType.tsx, sites/partners/src/components/listings/PaperListingForm/sections/LeasingAgent.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ListingIntro.tsx, sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx, sites/public/package.json, yarn.lock
This PR addresses #3430, #3232
There are two issues happening on the Listing edit/add form in partners. Both are due to components re-rendering when they shouldn't need to.
1st issue: When clicking save the errors are not highlighting the fields that need resolution. This is happening because there is an additional re-render that is triggering the useEffects in Units.tsx and CommunityType.tsx, LeasingAgent.tsx. Both of which are resetting the values in the form,
- Fix # 1: Change Reset in Units.tsx to a setValue when the value is undefined or null. One has to be selected so this works in all cases.
- Fix #2: Change reset in CommunityType.tsx to a setValue. This one works, but if an error happens on submission it will reset it back to the original value if you change it to the unset value …
=> fix: partners highlight field on backend error

sites/partners/src/lib/applications/formatApplicationData.ts
This PR addresses #3513
No matter what you select on the "Time Submitted" field on the paper application for AM/PM it always selects AM on submission. This is due to a mismatch in the mapping of formatting when converting it to a 24 hour string. A capital "A" is for AM/PM whereas a lower case "a" is for am/pm. We need it to be lowercase because that is what we get back from the timeField.
Go to a listing and create a manual application submission in partners. Select "PM" when selecting the "Time Submitted". On save it should now display pm on this page along with the applications table. 
You should be able to also edit the application and it should properly save the new time. …
=> fix: get correct time period for submitted

backend/core/src/listings/cache-purge.service.ts, backend/core/src/listings/listings-cron.service.ts, backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts, backend/core/src/listings/tests/listings.service.spec.ts
This PR addresses #3499 
The proxy cache is only getting purged when a listing is updated. There is another case where a listing is scheduled to get closed via the listings cron job. In this job we check on all open listings that have an application due date in the past. Once those are updated in the DB with the new status we need to also purge the listings endpoint in the proxy (the endpoint used on the listings search page). This is now being done after the save to the DB.
Notes:
- Since cron jobs cannot use any service that has request scope I made a new cache-purge service that both the listings service and the listings cron service uses.
In order to test this locally you will need to have the proxy running locally (instructions here: …
=> fix: do a cache purge on listings cron job

sites/partners/src/components/listings/PaperListingDetails/sections/DetailListingData.tsx
This PR addresses #3495 
Removes updated_at field from details listing page
On partners go to listing. It should have just `listing id` and `date created` fields in first section
If you have one commit and message, squash. If you need each message to be applied, rebase and …
=> fix: remove updated_at field from listing details page

backend_new/Procfile, backend_new/package.json, backend_new/tsconfig.json
These are the required changes in order to get the prisma backend to work in Heroku.
- Add Procfile so that the correct start command is done (by default it tries to do npm start)
- The start:prod command was point to the wrong directory.
Also of note, Heroku had to add this buildpack https://github.com/timanovsky/subdir-heroku-buildpack and add the PROJECT_PATH env variable
=> fix: add correct command to run on heroku

backend/core/src/listings/cache-purge.service.ts, backend/core/src/listings/listings.service.ts
This PR addresses #3565 
The change a month ago to fix the proxy cache purge is only working for one of the use cases. This is because the statuses used to determine if a cache purge should happen is incorrect. The "listing" value is updated right before the cache service is called so when checking the old status it is no longer accurate. To solve this a new variable is stored to keep track of the statuses 
1. Use the instructions in the backend proxy readme to startup the proxy locally https://github.com/bloom-housing/bloom/blob/main/backend/proxy/README.md.
2. Make sure the `PROXY_URL` is set in the .env for the backend and `BACKEND_PROXY_BASE` is set in the .env for the public site. sample `PROXY_URL=http://localhost:9000` and `BACKEND_PROXY_BASE=http://localhost:9000`
3. Start up the …
=> fix: use correct statuses for deciding to purge

backend/core/src/email/email.service.ts
Forget password emails for SJ users are coming in Spanish if the user has no language set. This is because when we do the DB query and language is null it returns the first row from the translation table that is of the correct jurisdiction. In this case it happened to be Spanish. This PR fixes that by only doing the custom translation fetch if the "language" value exists (is not null) 
The easiest way to test this is to grab the production data and copy it to your locally running database and then do the following steps.
1. Log into partners as an admin user
2. Create a new jurisdictional admin user that has the jurisdiction of San Jose
3. Log out and confirm your new account (click on email link, accept terms and set password)
4. logout and click "forgot …
=> fix: only email language if user has set language

sites/partners/page_content/locale_overrides/general.json, sites/partners/src/components/listings/PaperListingDetails/DetailsUnitDrawer.tsx, sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
This PR addresses #3567
Changes label for `Monthly Minimum Income` on partners site.
go to edit listing in partners site -> add unit -> select `fixed amount` first label should be `Monthly Minimum Income`.
In listing details page click `view` on unit that has above filled. It should also be `Monthly Minimum Income` now.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining …
=> fix: update label for monthly minimum income

backend_new/package.json, backend_new/src/controllers/user.controller.ts, backend_new/yarn.lock
When attempting to deploy the new backend to Heroku there was a typing error. This PR solves that by getting the user from the request in a more safe pattern. I don't know why this works locally, I think VSCode thinks it can infer from the incorrect package what the type is.
This is proven to work with the deployment to bloom-prisma backend. https://dashboard.heroku.com/apps/bloom-prisma/activity/builds/e1039a2f-1ff9-4151-a5d6-18c977372092
=> fix: change how user is retreived from req

backend/core/src/shared/units-transformations.ts
This PR addresses [#295](https://github.com/metrotranscom/doorway/issues/295)
Keys for four and five bedrooms were missing in sorting array, so they were before other sorted units for listings
You need to have listing with all types of units (especially 4, 5 bedrooms). On listing page they should be ordered now (sro -> studio -> 1 br -> ...)
- Either explicitly ask a clarifying question, request changes, or approve the PR if …
=> fix: add four and five bedrooms keys to sort array

sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx, sites/partners/src/components/listings/helpers.tsx, sites/partners/src/components/users/FormUserManage.tsx, sites/partners/src/pages/application/[id]/index.tsx, sites/partners/src/pages/application/[id]/review.tsx
This PR addresses #3633
Currently in partners for status tags, we are sometimes using the light primary variant and sometimes the darker secondary variant. We need to use the lighter primary version everywhere in partners for status tags.
Ensure when a listing is in an open or closed state that the pill is the primary / lighter version.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there …
=> fix: use primary tag variants in partners

sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3628)
this fixes an issue where editing a listing's unit meant the ami percentage value as reset
Create or edit a listing
add a unit and select an ami percentage that is NOT the first value in the select. 
for example if ami percentage options are 20, 40, 60, 80, 100 select something larger than 20 (so you can verify the fix is in place)
Then change one of the maximum annual income set values (it can be anything, but the more memorable the better)
so your values should look something like:  
save the unit then go in and edit. The values you set should be there
- Pull the …
=> fix: amiPercentage being unset on unit edit

sites/partners/package.json, yarn.lock
This dependency is frequently flagged by security checks and in the process of upgrading it, I noticed it doesn't appear to be used anywhere. I would also assume if it was used it would be in the public package file as well.
=> fix: remove electron

.circleci/config.yml, backend_new/src/main.ts, sites/public/next.config.js, sites/public/package.json, sites/public/src/lib/hooks.ts, sites/public/src/pages/listing/[id].tsx, sites/public/src/pages/listing/[id]/[slug].tsx
The public cypress tests are flaky because when starting up the app we were not correctly waiting for the backend to startup. Along with this having a separate port for the new backend was causing more headaches than it was solving. This cleans up those.
Nothing should change for your local. Cypress tests should now pass in CI …
=> fix: use consistent ports in cypress

backend/core/src/listings/listings.service.ts
This PR addresses #3722 
When a listing is edited after it has been requested for approval another request for approval email was getting sent. This has been happening many times for the same listing in HBA since the admin/jurisdictional admin make edits and don't publish right away. This change checks the previous status for both pendingReview and changesRequested so that only an email is sent the first time is goes to that status
1. Make sure you have two users set that can receive emails - An admin and a partner.
2. While signed in as the partner submit a listing for approval. Admin user should receive an email
3. While signed in as the admin make a change to the same listing with "save and exit" rather than "publish". No email should be sent.
- Read and …
=> fix: only send listing approval email once

sites/public/src/lib/applications/AppSubmissionContext.ts, sites/public/src/lib/applications/ApplicationConductor.ts, sites/public/src/pages/_app.tsx, sites/public/src/pages/applications/contact/address.tsx, sites/public/src/pages/applications/contact/alternate-contact-contact.tsx, sites/public/src/pages/applications/contact/alternate-contact-name.tsx, sites/public/src/pages/applications/contact/alternate-contact-type.tsx, sites/public/src/pages/applications/contact/name.tsx, sites/public/src/pages/applications/financial/income.tsx, sites/public/src/pages/applications/financial/vouchers.tsx, sites/public/src/pages/applications/household/ada.tsx, sites/public/src/pages/applications/household/add-members.tsx, sites/public/src/pages/applications/household/changes.tsx, sites/public/src/pages/applications/household/live-alone.tsx, sites/public/src/pages/applications/household/member.tsx, sites/public/src/pages/applications/household/preferred-units.tsx, sites/public/src/pages/applications/household/student.tsx, sites/public/src/pages/applications/start/autofill.tsx
This PR addresses #3737
There are two changes here but I can't guarantee that either of them are going to solve the issues with errors on fields other than `income`. You can reproduce the income issue just in HBA because we had commented out the income period field being required. You can test out these changes in HBA from [a PR up with the same changeset](https://github.com/housingbayarea/bloom/pull/654).
* We currently have a bug where the in-progress application kept in session storage wasn't actually getting fully reset when starting a new application. We were using the spread operator on a single blank application object, but spreading creates a shallow copy of nested objects, so things like alternate contact were being maintained and "autofilled" throughout applying to different …
=> fix: verify application errors

backend_new/src/dtos/applications/application-multiselect-question.dto.ts, backend_new/test/integration/application.e2e-spec.ts, shared-helpers/src/types/backend-swagger.ts, shared-helpers/src/views/multiselectQuestions.tsx
This PR adds the multiselectQuestionId to `ApplicationMultiselectQuestion`, so that we can gain efficiency in tying application responses with preferences and programs to the multiselect question. The end result should be that when users submit an application, their preference and program responses will be saved with the multiselectQuestionId.
=> fix: application multiselect questions

backend/core/src/applications/helpers.ts, backend/core/src/applications/services/application-csv-exporter.service.ts
This PR addresses #3689
Adds geocoding fields to the CSV export. If I understand correctly, we are creating a `.csv` file from an `object`. So, if we have the same keys, they will override the previous ones. To avoid this, I followed the pattern that was already implemented for address.
Applications .csv files are send to email, so you must have access to account email.
Fill application that has `relationship to address holder` `name of addressholder` and is verified by radius.
If you export listing applications in partners page it now should have additional fields.
Test with multiple options / preferences  …
=> fix: add geocoding fields to csv export

sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
This PR addresses #3690
It is issue that was reported after merge of #3690.
in partners in edit listing page Housing Preferences -> edit preferences -> select preferences -> preview, there was the case where `(This preference provides additional details that will be included in the exported data)` overflowed with above text (for example here https://partners.bloom.exygy.dev/listings/14b211fa-e9a4-4541-a6d6-b5416ade1d55/edit -> Test radius geocoding preference).
It happen when no description and links present in option.
for different options variants (like with description, with links etc) check if that behaviour still exist.
- Pull the changes …
=> fix: provides additional fields info text overflows

sites/public/src/components/applications/ApplicationMultiselectQuestionStep.tsx
This PR addresses #3799
Display preference link in application process. Even though it seem that we can only add one link for preference i used map to display whole array of links (as it was implemented like this in other place: public listing view -> Housing Preferences).
fill application with preferences that have a link. On preferences step it will display link below title and description (if present)
- Either explicitly ask …
=> fix: add links to preference description

backend_new/src/services/listing.service.ts, backend_new/src/services/user.service.ts, backend_new/test/integration/listing.e2e-spec.ts, backend_new/test/integration/permission-tests/permission-as-admin.e2e-spec.ts, backend_new/test/unit/services/listing.service.spec.ts, backend_new/test/unit/services/user.service.spec.ts
This addresses an issue found during the bug bash. On the listings page in partners if you go to page two of the table and then change the per page to a number higher than the total listing count no listings are returned. This fixes it by resetting to the first page if that scenario hits the backend.
The same thing has been implemented for the users table
Also another issue was found on deletion of multiselect questions on a listing. When you deleted a preference on the listing edit page it wasn't actually disconnecting it from the listing in the DB. This change makes it so all are deleted before recreated in the listingmultiselectquestion table
Pagination:
- Make sure you have more than 8 listings and go to the listings page in partners.
- Click "next" button on …
=> fix: pagination and deletion fix

backend/core/src/migration/1705637577495-add-feature-collection.ts, sites/partners/__tests__/pages/settings/index.test.tsx
This PR addresses #3814 
Due to this new field being a non-null column the bloom-backend-main deployment fails as there are already dummy data in the table. This fix adds a default value to the featureCollection column so that the migration can successfully run. It will not be an issue in the production deployment as there is no map-layer data in the database yet
A reseed of the data did not catch this because that does a cleanse of the database before applying all migrations and then adding the seeded data. So in order to test this like how production would be the following must be done:
- Locally pull down the code one commit before the most recent commit (HEAD should be at `aa8e3a647`).
- Run a reseed. This should add the map-layer table to the database without the featureCollection …
=> fix: add default value for map layer

backend/core/src/applications/services/geocoding.service.spec.ts, backend/core/src/applications/services/geocoding.service.ts, backend/core/test/applications/applications.e2e-spec.ts
This PR addresses #3814 
While testing the e2e functionality of geocoding a bug was found when a listing has both a radius and map-layer preference tied to it. This is because the preferences were getting overwritten during the map-layer check if they were already updated on the radius check.
In order to solve this a small refactor was done to make sure the updated preferences are getting passed to each consecutive check.
- Create a preference that collects address and validates against a radius
- Create a preference that collects address and validates against a map layer
- On an open listing attach both of the above preferences to it
- Go to the public site and apply to the listing making sure to add address for both of the preferences
- Read and understand the …
=> fix: geocoding verification fix

backend/core/src/applications/services/applications.service.ts, backend/core/src/applications/types/application-multiselect-question-option.ts, backend/core/src/multiselect-question/types/multiselect-option.ts, backend/core/types/src/backend-swagger.ts, shared-helpers/src/views/multiselectQuestions.tsx, sites/partners/src/components/applications/PaperApplicationForm/MultiselectQuestionsMap.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
This PR addresses #3810 
Add maps to preference options with address, that will include latitude and longitude in option address object.
I got to exclude extraData field from submitting when option is unchecked, which seem expected, but let me know if you see any possible issues with that.
Also this will be visible in non geocoding app (as is address verification step in digital application).
1. Create paper application that has preference option with validation address radius method set.
2. select that option, fill address and save. 
3. Export applications -> `Passed Address Check` cell for that option should be either `yes` or `no` instead of `Needs Manual Verification` …
=> fix: Paper Application not saving lat long

shared-helpers/src/views/multiselectQuestions.tsx
This PR addresses #3833
This issue seem like some weird tailwind config issue, where on our remote envs for example class `.pt-5` is not generated. Strangely locally it works fine. But to not overcomplicate that i decided to align it to [this design](https://www.figma.com/file/Ne8jOyPpCBvlAhyaRlXgTq/Geocoding?type=design&node-id=1627-5899&mode=design&t=KhELQj7swCtDCkoM-4) (which btw seem like a thing that i should do anyway).
As that tailwind config is in UIC and it uses some old library for rtl, so not sure if it's easely upgradable (similar issues were solved by bumping tailwind). And testing it will be  problematic as it's only remote thing. I can see `pt-5` class was only used here anyways (not sure if other classes also are missing).
fill application to programs / preferences step. …
=> fix: spacing on preference pages

backend/core/src/map-layers/map-layers.controller.ts
This PR addresses #3852 
The jurisdictional admins are getting an unauthorized exception when loading the settings page because on page load a call to the map-layers endpoint is being done. We have a check on the front-end that catches any 403 exceptions and re-routes them to the unauthorized page. Since jurisdictional admins can access the settings page we should also allow the map layer endpoint to have j-admins to hit it.
Note:
- No tests are being added in this PR to catch this since we don't have a great setup for permission level testing. This functionality is also getting pulled over to the new backend here https://github.com/bloom-housing/bloom/pull/3844 and I will add an additional test to make sure this is covered there.
Sign into the …
=> fix: allow jurisdictional admin for map layers

backend_new/.env.template, backend_new/src/controllers/app.controller.ts, backend_new/src/controllers/listing.controller.ts, backend_new/src/modules/app.module.ts, backend_new/src/services/app.service.ts, backend_new/src/services/listing-csv-export.service.ts, backend_new/test/unit/services/app.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This moves the cronjob for cleaning up temp files into its own endpoint instead of hanging onto the listing controller
=> feat: moving temp file clean up cron

api/src/services/listing.service.ts
This PR addresses an issue with the listing cache not being cleared
Currently on the prisma backend we aren't clearing both a single listing and all listings 
This is a fix to do both under the correct conditions (listing is already on the public portal)
This is easiest to test if you have the proxy set up, edit a listing that is "live" on your local machine and you should see the update show in both the listing list and the listing "detail" page on public …
=> fix: fixing the cache purge

shared-helpers/src/auth/UseRequireLoggedInUser.ts, sites/public/src/lib/hooks.ts, sites/public/src/pages/applications/start/choose-language.tsx
This PR addresses #3769.
As part of the Mandated Accounts MVP, this PR redirects users to the sign-in page if they access an application page while not signed in. This prevents the case where signed-out users are directed to a page in the middle of an application.
To review this PR:
1. Ensure that you are not signed in. 
2. Check that when you access a page in the middle of an application (see [urls](https://github.com/bloom-housing/bloom/blob/9f35e7e1a995c63dd6bbf23a23ca8ece049b3843/sites/public/src/lib/applications/ApplicationConductor.ts#L41)), you are redirected to the `/sign-in` page. For example, `http://localhost:3000/applications/start/what-to-expect` or `http://localhost:3000/applications/review/summary`.
Note: This ticket does not include redirection for the case where a …
=> feat: add MA application check for signed-in user

sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
When a preference collects address but doesn't have a description or any links a null pointer exception happens when clicking the "preview" button when selecting a preference on a listing.
To test:
Assuming there is a preference that has at least one option that "collects address" and doesn't have a description or any links.
- In edit mode of a listing click "add preference".
- On the above mentioned preference click "preview"
- The preview should properly show
=> fix: null check on option links

sites/public/src/lib/applications/ApplicationConductor.ts, sites/public/src/pages/applications/review/summary.tsx
This PR addresses #3883
Originally we were using a calculation based on "completed sections" to determine if we should show the "Save and Return to Review" link, but that often resulted in the determination concluding it should show before the Review step had actually been reached. This PR makes that logic explicit: you have to reach Review before it will then display that link on previous steps.
Fill out an application, reach the Review step, then go back and edit previous data and verify that's when the link is available (and not any time before).
- Also review the …
=> fix: the Save and Return link should only show after the Review step has been reached

api/prisma/seed-helpers/application-factory.ts, api/src/controllers/application.controller.ts, api/src/permission-configs/permission_policy.csv, api/src/services/application.service.ts, api/src/services/user.service.ts, api/test/integration/application.e2e-spec.ts, api/test/integration/multiselect-question.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-public.e2e-spec.ts, api/test/unit/services/application.service.spec.ts, api/test/unit/services/user.service.spec.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3945)
This puts in place a series of security patches around permissioning:
1. applications gets account level permissions
2. reference table data is no longer accessible below partner level permissions
3. user updates gets a more secure lock when it comes to updating user roles
as a public user you should be able to do the follow still:
1. create account
2. apply to a listing
3. have autofill happen when you go to apply to a second listing
4. be able to see your list of applications
5. be able to see your update your user data
as a partner on the partner site:
1. you should be able to edit listings
as a jurisdictional admin on the partner site:
1. you should be able to create listings
2. you should be able to invite …
=> feat: security patch

api/prisma/migrations/08_updating_on_delete_cascades_listings_and_applications/migration.sql, api/prisma/schema.prisma, api/prisma/seed-dev.ts, api/prisma/seed-helpers/listing-factory.ts, api/prisma/seed-staging.ts, api/test/integration/listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
Updates the seed command so that when you run `yarn setup:dev`, the following is now true:
* If you were to go into partners and save a listing, all the required fields to publish are filled out, which includes developer, leasing agent details, application details, and an image
* Giving reserved community type a 50% chance of being included instead of always being included
* Ensuring there are units on every listing
* Ensuring there are at least 4 open listings added, and that every other listing has a digital app, so that when you run setup:dev there are guaranteed to be at least two listings with a digital application
You can run `yarn setup:dev` in `api/` and check it out, the randomization will result it in being slightly different every time.
=> test: update seeds + fix listing delete

api/src/guards/throttler.guard.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3950)
This is a take 2 of sorts, I think we need to use the forwarded ip here when its available (coming through one of the various proxies we have in place)
testing locally is impossible, I'll need to test this in a hosted env
=> fix: possibly throttling through the proxy stuff

sites/partners/src/components/listings/ListingFormActions.tsx
**This is a carry-over from HBA to address support issue**
This PR addresses #3996
This fix resolves the error below which was blocking users from clicking the "Approve and Publish" button from the detail (not edit) view. This is caused by a type mismatch. The frontend listing data had the ListingMultiSelectQuestionType shape but the update function in the listing.service was expecting an idDto for listing multiselect question data. After talking with @YazeedLoonat, it was decided to do the work on the frontend to format the data since other formatting work is already done there instead of on the backend. 
**Note**: Since the technical notes in the attached ticket present a more thorough investigation around consistent submitting of listing updates, I decided this one off fix was okay for …
=> fix: account for multiselect type mismatch (#686)

api/src/enums/user/view-enum.ts, api/src/services/auth.service.ts, api/src/services/user.service.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts, api/test/unit/services/user.service.spec.ts
This PR addresses [#issue](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4024)
Part 1: Jurisdictional Admin E2E Permission Tests were falsely passing because they we not correctly creating the test user and did not match the actual permissions juris admins have. To correct this, correctly called the user factory and updated the tests to match the expected permissions.
Part 2: In doing so, discovered that when a jurisdictional admin attempts to delete a user (from their jurisdiction or not) and error is thrown due to a missing field on the target user and then the target user is deleted anyway.
We now load the jurisdictions onto the target user and compare them properly with the jurisdictions the jurisdictional admin has access to before …
=> Fix: Update Jurisdictional Admin E2E Tests and Correct Jurisdictional Admin Delete User

sites/partners/cypress/e2e/default/03-listing.spec.ts
Fixes the failing Cypress partners tests by updating the longitude string to be more generic. Occasionally the geocoding package updates the numbers.
=> test: fix cypress longitude error

sites/public/src/lib/hooks.ts, sites/public/src/pages/index.tsx
This fixes an issue where during the getStaticProps call we were asking for the request but getStaticProps does not have access to the request as its a static generator
this fix should keep the public's listings list page working, the public listing detail page working, and shouldn't throw an error in the public site during build/initially when the public site has `yarn dev` ran
=> fix: restores getStaticProps functionality

api/.env.template, api/src/controllers/auth.controller.ts, api/src/controllers/script-runner.controller.ts, api/src/dtos/script-runner/data-transfer.dto.ts, api/src/services/script-runner.service.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/4079)
This creates an endpoint in the script runner controller, and a function in the script runner service to start doing data transfer
The new endpoint takes in the database connection string in order to connect to the db
Spin up the api locally -> head to lhttp://localhost:3101/api/ or http://localhost:3100/api/ -> get the production database connection string -> log in as an admin or juris admin user via the openapi doc -> hit the script runner's data transfer endpoint passing in the database connection string
you should get success: true on the openapi response, and your api terminal should have a console log with the jurisdiction id for San Mateo from the production db
- Read and …
=> feat: script runner data transfer part 1

api/prisma/constants.ts, api/prisma/seed-dev.ts, api/prisma/seed-helpers/alternate-contact-factory.ts, api/prisma/seed-helpers/application-factory.ts, api/prisma/seed-helpers/household-member-factory.ts, api/prisma/seed-helpers/jurisdiction-factory.ts, api/src/dtos/applications/alternate-contact.dto.ts, api/src/dtos/applications/household-member.dto.ts, api/src/enums/applications/alternate-contact-relationship-enum.ts, api/src/enums/applications/household-member-relationship-enum.ts, api/test/integration/application.e2e-spec.ts, api/test/integration/permission-tests/helpers.ts, shared-helpers/src/types/backend-swagger.ts, shared-helpers/src/utilities/formKeys.ts, sites/partners/src/components/applications/ApplicationsColDefs.ts, sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsAlternateContact.tsx, sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx, sites/partners/src/components/applications/PaperApplicationForm/FormMember.tsx, sites/partners/src/lib/applications/formatApplicationData.ts, sites/public/src/pages/applications/household/member.tsx
I ran into a lot of issues testing duplicate problems locally because of some invalid and missing seed data - this PR fixes a handful of problems related to seed data and a few bugs with how that data was showing up in the applications table. I added a comment to each fix. It also types two application fields with an enum that were previously just a set of strings the frontend was sending to the backend.
Run `yarn setup:dev` and check out the applications table on a listing to see more applications with more data and more variety.
Submit an application and fill out alternate contact and household member data to ensure it comes through as expected on the partners side to ensure the new typing places nicely.
- Read and understand the issue, and ensure the author has …
=> fix: improve seed data and validity

api/prisma/seed-dev.ts, api/prisma/seed-helpers/user-factory.ts, api/prisma/seed-staging.ts, sites/partners/src/components/users/FormUserConfirm.tsx, sites/public/cypress/e2e/account/account.spec.ts, sites/public/cypress/mockData/applicationData.ts, sites/public/cypress/mockData/userData.ts, sites/public/cypress/support/commands.js, sites/public/cypress/support/helpers.ts, sites/public/cypress/support/index.d.ts, sites/public/src/components/shared/FormSummaryDetails.tsx, sites/public/src/pages/account/dashboard.tsx, sites/public/src/pages/account/edit.tsx
This PR addresses https://github.com/metrotranscom/doorway/issues/631
This PR fixes two bugs on the user account screen:
1. Edit a field on the user account page, visit another page like the dashboard, go back in the browser and your change was not there
2. Edit a field on the user account page, edit another field, refresh, and only the second change persisted
It seemed like the problem with the first bug was that we are setting the form field defaults if the user profile is present, and when you go back in the browser, the profile is present and wasn't refetching, so I am fetching the user on page load, and after every user update I am re-setting the user object. Because I'm fetching on page load and that data is required in the UI, I pulled in our loading overlay over the card.
We were …
=> fix: saving user account info

sites/partners/src/components/listings/PaperListingDetails/DetailsUnitDrawer.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationDates.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailUnits.tsx, sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx, sites/partners/src/components/listings/PaperListingForm/index.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx, sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ListingPhotos.tsx, sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx, sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx, sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx, sites/partners/src/components/settings/PreferenceDrawer.tsx
This PR addresses https://github.com/bloom-housing/ui-seeds/issues/72
There are 5 pieces of feedback in the issue, this PR addresses 1, 2, and 4.
3 & 5 have been addressed separately in #4084
Sign into the Partners app and verify the revised button sizes and placements as described in the issue. …
=> fix: address various design QA for buttons

sites/partners/src/pages/application/[id]/review.tsx
This PR addresses https://github.com/bloom-housing/Bloom-Doorway/issues/51
The Save button was misaligned and flush with a bottom border on the duplicate applications review. This fixes the alignment and spacing.
https://deploy-preview-4129--partners-bloom-dev.netlify.app/application/52ee25ee-41f2-4495-961d-86e7de85c43f/review
=> fix: duplicate review alignment

sites/public/src/components/listing/ListingView.tsx
This PR addresses #4135
This PR updates the logic to show the submit application section to account for the mailing and dropoff addresses to be undefined but the address type is same as leasing agent.
Note: That this will be pulled into Doorway Asap
Create a listing with "Are postmarks considered?" marked as Yes, a paper app attached, indicate a received by date & time, and with both the mailing address and the drop-off address marked as same as the leasingAgentAddress... the submit application section should show on the public side with the corresponding postmark information.
- Either (1) …
=> fix: include check for address type

api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationAddress.tsx, sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts, sites/partners/src/lib/listings/BooleansFormatter.ts
This PR addresses [#638](https://github.com/metrotranscom/doorway/issues/638)
When updating a listing and removing the mailing, pickup, or drop-off address the existing address was still sticking around. This is happening due to the Prisma change over. Specifically because the field names of those were updated in Prisma and the new change was missed in one place in the partner site. This also exposed an issue with how we were deleting addresses, the address needs to be disconnected from the listing before it can be deleted from the listing table.
The following steps can be tested:
1. Add "another" mailing address, pick-up address, and drop-off address
2. Save the listing.
Both of these use cases should be tested for all three fields:
1. Select "at the leasing agent address" and then …
=> fix: allow removal of mailing address

sites/partners/src/components/listings/ListingFormActions.tsx, sites/partners/src/pages/listings/[id]/index.tsx
This PR addresses [#639](https://github.com/metrotranscom/doorway/issues/639)
When submitting a listing for approval not every field needs to be filled out. This can cause a side effect of when an admin approves the listing they then have to resolve the missing fields. The issue is made even worse if the admin chooses to approve from the details view rather than the edit view as only a generic error message happens (which also was broken). As a remediation this PR adds an additional error banner on the listing details view when this error happens so that the user knows the next step that needs to happen 
- As a partner user submit a listing that is missing at least one required field.
- Log in as an admin and click the "Approve & Publish" button for that listing (note: not on the edit …
=> fix: add error message for incorrect listing approval

sites/public/src/pages/preview/listings/[id].tsx
This PR addresses #4147 
This PR adds in language to the headers of the listings call on the preview page so that it matches the [slug.tsx] headers. This way the translation service is called within the listingService.findOne() call.
This can be tested by pulling this down locally, previewing a listing from the partner's side and see that most if not all strings are translating with the exception of a few particular fields such as "or one month's rent may be higher for lower credit scores" which are known by Sarah. If you wish you can uncomment the new line to see the difference.
- Either (1) …
=> fix: add language to headers

api/src/controllers/script-runner.controller.ts, api/src/dtos/script-runner/ami-chart-import.dto.ts, api/src/modules/script-runner.module.ts, api/src/services/script-runner.service.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses https://github.com/bloom-housing/bloom/issues/4041
Creates a new script runner endpoint that takes in the standardized string and creates the new ami chart
a unit test was added, but you can test via localhost:3100/api login, and then leverage the new script runner endpoint
=> feat: ami chart import script runner

api/src/services/application-flagged-set.service.ts, api/test/unit/services/application-csv-export.service.spec.ts, api/test/unit/services/application-flagged-set.service.spec.ts
This PR addresses #4144 
The AFS job is failing in both bloom and Doorway due to paper applications that don't have a first or last name. This adds a null check to make sure the AFS job won't run into this error when running
Add a paper application that doesn't have first and last name to a property. Then close the listing and run the AFS job
=> fix: add null check to afs rule key

api/src/services/listing.service.ts, api/test/unit/services/listing.service.spec.ts
This PR addresses #4140 
When a reserved community type already exists on a listing and should be removed it was not properly being removed because it needs to be "disconnected" rather than just set to undefined
Add a community type to a listing and save the listing. Then re-edit the listing and remove the reserved community type. The community type should no longer be on the listing
=> fix: add the ability to disconnect community types

api/prisma/migrations/13_application_lottery_positioning/migration.sql, api/prisma/schema.prisma, api/src/dtos/applications/application-lottery-position.dto.ts, api/src/dtos/applications/application-update.dto.ts, api/src/dtos/applications/application.dto.ts, api/src/services/application-csv-export.service.ts, api/test/unit/services/application-csv-export.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses https://github.com/bloom-housing/bloom/issues/4055
This adds the randomizer for lottery to the csv export 
it doesn't expose a way to do this, but there are unit tests to demo how it'll work
the endpoints and stuff are coming in a part 2, this is just the randomization logic and unit tests 
=> feat: adding randomization tooling to export service

api/src/services/script-runner.service.ts
This PR addresses #4094 
This PR updates the ami import script runner service to include more detailed instructions on how to pre-process ami data from Google Sheets. 
Read the comments and look through the notion page based on the commenting instructions
=> fix: ami import formatting instructions

sites/partners/src/components/shared/NavigationHeader.tsx, sites/partners/src/pages/listings/[id]/applications/index.tsx, sites/partners/src/pages/listings/[id]/applications/pending/index.tsx, sites/partners/src/pages/listings/[id]/lottery.tsx, sites/public/package.json, sites/public/src/pages/preview/listings/[id].tsx, yarn.lock
I ran into two issues with the Doorway release of the lottery empty state ([this core PR](https://github.com/bloom-housing/bloom/commit/4dbb6e3d10beeefa90798c904c5c797c497c8ee4))
* We weren't adding the API pass key on the lottery page
* The new lottery tab was missing from the applications page
These were added into the [Doorway release branch](https://github.com/metrotranscom/doorway/pull/706) already
=> fix: lottery rebase issues

api/prisma/migrations/14_add_lottery_status_enums/migration.sql, api/prisma/schema.prisma, api/prisma/seed-helpers/listing-factory.ts, api/src/controllers/listing.controller.ts, api/src/dtos/listings/listing-lottery-status.dto.ts, api/src/dtos/listings/listing.dto.ts, api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, api/test/unit/services/listing.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(4057)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4057)
Create lottery status enums and status change endpoint. Setup business logic for releasing to partners and retracting actions.
To understand how the status flow works, check out this [Miro board](https://miro.com/app/board/uXjVK4sw5X4=/)
Run migration and run backend in the terminal. Use the swagger open api for the following flows.
Flow 1: Login as an admin, attempt to change the status of a active listing to releasedToPartners, you should receive an error since listing is not closed.
Flow 2: Login as an admin, attempt to change the status of a closed listing to releasedToPartners, you should receive an error since it must be in approved.
Flow 3: Change the …
=> feat: lottery status (released to partners / retracted)

sites/public/src/pages/applications/review/confirmation.tsx, sites/public/styles/overrides.scss
This PR addresses #3987
The confirmation page you arrive at immediately following submitting a common app hadn't been restyled more in the new Seeds-oriented design theme. This PR makes those improvements to bring the page in line with the Figma mockup, including overrides to make the UIC application timeline left-aligned.
**Note:** the overrides CSS isn't intended to be high-quality. We should re-implement these "progress nav" components at some point in a fully Seeds-ified way, but that's beyond the scope of these immediate fixes. But if there's feedback we should try to improve this more thoroughly, I'm happy to work on it further.
Fill out a common app, and compare the confirmation screen with Figma.
- Review the …
=> feat: application confirmation styling updates based on design QA

api/prisma/seed-staging.ts, sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
This PR addresses #4174 
When making the backend call to get AMI charts on the partner site the jurisdiction id was not getting set. This was due to a change in Prisma where the jurisdiction field was changed to "jurisdictions" so the `watch` function was not looking for the correct field
*Note*: a new ami chart was added to the stage seeded data tied to the second jurisdiction so I'd recommend a reseed before testing
- Log into the partner site as an admin
- Add a new listing.
- Go to add a new unit within the listing and make sure that all AMI charts are accessible in the dropdown
- Set a jurisdiction to the listing and then try to add a unit. Only the AMI charts for that jurisdiction are accessible …
=> fix: filter ami charts by jurisdition

api/prisma/seed-helpers/listing-factory.ts, api/src/services/application.service.ts, api/test/integration/application.e2e-spec.ts, api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-public.e2e-spec.ts, api/test/unit/services/application.service.spec.ts, sites/public/src/pages/applications/review/summary.tsx, sites/public/src/pages/applications/start/choose-language.tsx
This PR addresses https://github.com/metrotranscom/doorway/issues/698
This PR updates the logic on the FE and BE to block application submissions from past due applications and listings that do not have the common application.
Note that these changes collides with a few existing bugs:
1) You'll notice the addToast line is commented out. I discovered a bug while testing this PR that results in infinite re-renders and subsequently, endless toasts. #4181 
2) If you change a listing that had a commonApp and answer no to digitalApp, the commonDigitalApp field remains true. The logic checks for both but I wrote up a ticket here: #4182 
3) application.e2e-spec.ts has significant amounts of duplicate (copy-pasta) code. Particularly in the creation of dtos. Instead, a base dto should be created …
=> fix: improve application submission logic

shared-helpers/src/views/multiselectQuestions.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx, sites/partners/src/lib/applications/formatApplicationData.ts, sites/public/src/components/applications/ApplicationMultiselectQuestionStep.tsx
This PR addresses #3835 and #3830
It aligns radio fields behaviour to checkboxes (for multiselect options), so it adds description, and geocoding fields (address, address holder name / relationship).
This component is reused both for programs and preferences, so even that is preferences change it might affect programs (but it shouldn't).
On partners portal set all preferences options to exclusive (for selected preference). Also test with `Can applicants opt out?` set to `yes` for preference. That will work both for digital app and paper app.
- make sure user can't submit empty radio preference for digital app.
- make sure programs, and checkboxes work as before.
- Review the code itself from a …
=> fix: radio preferences don't show description and geocoding fields

api/prisma/migrations/15_lottery_opt_in/migration.sql, api/prisma/schema.prisma, api/src/dtos/listings/listing.dto.ts, shared-helpers/src/types/backend-swagger.ts, sites/partners/page_content/locale_overrides/general.json, sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx, sites/partners/src/components/listings/PaperListingForm/index.tsx, sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx, sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx, sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts, sites/partners/src/lib/listings/BooleansFormatter.ts, sites/partners/src/lib/listings/formTypes.ts, sites/partners/src/pages/listings/[id]/applications/index.tsx, sites/partners/src/pages/listings/[id]/applications/pending/index.tsx, sites/partners/src/pages/listings/[id]/index.tsx, sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses #4049
Adds the lottery opt-in question on the partners listing form if the feature is toggled on. If a listing is saved with the opt-in toggle on, then there is also new copy in the preference drawer.
With the toggle on, create/edit a listing - in the rankings and results section, if the review order is lottery, a `Will the lottery be run in the partner portal?` question will toggle on. You should be able to save it as both values. When the toggle is saved as on, there will be new copy in the preference drawer. If the toggle is off, you should not be able to see the lottery tab.
I do think this deserves a partners Cypress test, but I think that would be a larger effort bc we would need to set up a new job that turns the toggle on …
=> feat: lottery opt in

sites/partners/__tests__/components/listings/ListingFormActions.test.tsx, sites/partners/src/components/listings/ListingFormActions.tsx, sites/partners/src/components/listings/PaperListingForm/index.tsx
This PR addresses [#747](https://github.com/metrotranscom/doorway/issues/747)
When the lottery toggle is on, on a closed listing with a lottery type, if a user is opted into the system lottery they cannot "post results" in the button list, but if a user is opted out they are able to post results.
When the lottery toggle is on, on a closed listing with a lottery type, if a user is opted into the system lottery ensure they cannot see the post results button. Opt out of the lottery and save, and when re-entering the edit state the post results button should be available. You will have to save in between states. …
=> feat: disable lottery upload if using system lottery

sites/partners/__tests__/pages/listings/lottery.test.tsx, sites/partners/page_content/locale_overrides/general.json, sites/partners/src/pages/listings/[id]/lottery.tsx, sites/partners/styles/lottery.module.scss
This PR addresses #4210
If you export lottery data as a partner, you should see a terms modal.
On a closed listing with a lottery as a partner where the lottery has been published to public, export the lottery data and ensure you see a terms modal with [this copy](https://docs.google.com/document/d/130OuxoQnKnukoVr_SPQq57A0JZ4vycdcS9q0EX2Gkso/edit?pli=1#heading=h.n9kz6ajsfrz) (Doorway-specific references removed).
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after …
=> feat: export with terms for partners

shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json
This PR addresses [#(4122)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4122)
Previous copy was misleading, changed to "Please go to your email to confirm this update". Translations also updated.
Using each language, change the email address in the public Account Settings page and verify the new copy appears in the alert.
=> feat: change email update copy

sites/partners/__tests__/pages/listings/lottery.test.tsx, sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses [#(4058)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4058)
Accidentally put the expiration date in the run lottery dialog. This PR removes it.
Sign into Partners as a admin, navigate to a closed listing opted into lottery, go to lottery tab, click Run Lottery. Should match image below.
=> fix: remove errant lottery copy

sites/partners/page_content/locale_overrides/general.json, sites/partners/src/components/listings/PaperListingForm/index.tsx, sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx, sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts
This PR addresses #4221
Only admins can now opt in / out of the system lottery. A partner will just see explanatory text that they are opted in / out.
As an admin, create a listing that opts in to the lottery and view the listing as a partner to see the opt in text. Do the same for opting out. Save changes in both states as a partner to ensure the partner user is not able to update the value.
=> feat: new opt in language for partners

api/src/services/user.service.ts, sites/partners/page_content/locale_overrides/general.json
This PR addresses [#770](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/770)
Returns 409 instead of 400 error for email in use (frontend already checks for 409 error code, and displays different message)
In http://localhost:3001/users create user with already existing email (for example: `admin@example.com`). Error should display expected message
=> fix: return proper exception for email in use

api/prisma/seed-helpers/address-factory.ts, api/prisma/seed-helpers/application-preference-factory.ts, api/prisma/seed-staging.ts, api/src/services/lottery.service.ts, api/src/utilities/application-export-helpers.ts, api/test/unit/services/application.service.spec.ts, api/test/unit/services/lottery.service.spec.ts, sites/partners/src/lib/hooks.ts, sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses #4056 
This adds the preference sheets to the lottery export as well as a few other things:
- preference sheets
- added
- demographics
- now based on role just like application csv export
- columns
- added preference rank
- still need to double check column order
- permissions
- UI is now hooked up to do a partner export
- head to the partners site
- on a closed listing with applications and preferences on the listing (and to make it easier claimed preferences on at least some of the applications)
- generate the lottery results
- get the spreadsheet export
you should notice individual sheets for each preference as well as the original raw sheet
- …
=> feat: adding preference sheets to lottery export

api/src/dtos/listings/listing-update.dto.ts, api/src/dtos/listings/listing.dto.ts, api/src/utilities/lottery-date-validator.ts, api/test/unit/utilities/lottery-date-validator.spec.ts, sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx, sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
This PR addresses [#(4212)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4212)
When a listing has lottery selected and has opted in to our lottery system, the lottery start date, start time and end time fields should be required. When any of the 3 fields are not filled out, an error will appear on save and all 3 fields will be highlighted. 
Create or edit a listing in the partners portal.
Save with First Come First Serve selected. No errors should appear.
Edit and save with Lottery selected and No selected for optin. No errors should appear.
Edit and select Yes for optin. Do not fill out start date, start time and end time fields. Error should appear and fields should be highlighted. Cancel edit.
Edit and select Yes for optin. Fill out …
=> feat: require lottery date time fields

api/src/services/lottery.service.ts, api/test/integration/lottery.e2e-spec.ts, api/test/unit/services/lottery.service.spec.ts
This PR addresses #4246 
Re-run of the lottery needs an extra step of resetting the application lottery positions so that it is starting from scratch.
NOTE: this is pointing to the history log PR because there was a bit of refactor that is not yet in main
This can be tested on the UI. Go to a closed listing and run the lottery. Check the order of the applications in that run. Click the re-run lottery button and re-export the results. The order should be different. Also notice the "re-run" in the history log sidebar
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) …
=> fix: add lottery re-run functionality

api/src/controllers/lottery.controller.ts, shared-helpers/src/types/backend-swagger.ts, sites/partners/__tests__/pages/listings/lottery.test.tsx, sites/partners/src/lib/hooks.ts
This PR addresses #4253
Lottery history logs are not currently filtering by ID. The issue was that the listing ID wasn't actually getting passed through to the endpoint and was coming in as undefined.
Create two listings and take lottery actions on each of them. Ensure their history logs only reflect the actions that were taken on that listing.
=> fix: lottery history log filtering

api/package.json, api/src/services/script-runner.service.ts, api/test/unit/services/application.service.spec.ts, api/test/unit/services/listing.service.spec.ts, api/test/unit/services/lottery.service.spec.ts, api/test/unit/services/script-runner.service.spec.ts, api/test/unit/services/translation.service.spec.ts, api/yarn.lock
There are several backend unit tests that happen to be working because we have a database running while the tests are running. If this were to not be the case these tests would start failing and there is even a failing test semi-related to this issue.
This PR mocks out all db calls that are needed in tests that are not already mocked out. 
To test:
- These are already passing in circleci, but to test it locally to make sure all are caught you can change your .env file to point to a non-existent DB. I did this by changing the port on the DB url
=> fix: remove db dependency from unit tests

shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json, shared-helpers/src/views/address/FormAddressAlternate.tsx, shared-helpers/src/views/multiselectQuestions.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx, sites/public/src/pages/account/edit.tsx, sites/public/src/pages/applications/contact/address.tsx, sites/public/src/pages/applications/contact/alternate-contact-contact.tsx, sites/public/src/pages/applications/contact/alternate-contact-name.tsx, sites/public/src/pages/applications/contact/alternate-contact-type.tsx, sites/public/src/pages/applications/contact/name.tsx, sites/public/src/pages/applications/household/member.tsx, sites/public/src/pages/create-account.tsx
This PR addresses #4260 
This PR updates the length validation on Zip Code fields to be 10 which matches the verify endpoint length. This also updates the error message be take in the length rather than hardcoding 64 characters.
This can be tested by attempting to fill out the application and zip code field with more than 10 characters and seeing the appropriate error message.
=> fix: update zip length requirement and error messaging

api/prisma/seed-helpers/listing-factory.ts, api/prisma/seed-staging.ts, api/src/controllers/script-runner.controller.ts, api/src/services/script-runner.service.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(4258)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4258)
Existing lotteries from before the opt in field was added now have `null` in the field. Thus if a change is made to the lottery on the partners portal, the listing could accidentally be opted in to the system lottery without the user knowing due to our frontend logic. To prevent this, we can run the new script to mark all existing lotteries with `null` in the opt in field to `false`.
Reseed local database. By default, there should be 2 lottery listings. If you check the db, they will have lotteryOptIn set to `null`. Login as an admin and go to the API UI. Call the `optOutExistingLotteries` script endpoint. You should see 2 printed in the console. Check the …
=> feat: opt out existing lotteries

sites/partners/next.config.js
This PR addresses #4273 
Adds comparison to next config
Test locally with show_lottery="TRUE", show_lottery="FALSE" and without show_lottery ever defined. The second two cases should hide the features.
=> fix: include comparison in next config

api/src/controllers/script-runner.controller.ts, api/src/services/script-runner.service.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses #4272
This fixes a bug that was causing the lottery translations script to fail. We are using the default translations, i.e. not tied to a jurisdictional ID, and not all jurisdictions had existing default translations across all languages.
Start the app, and via swagger log-in and run the new script. Ensure it succeeds and that the translations are in the database.
If you want to test the user flow, you can also submit an application in a foreign language while signed in to one of your own emails, and then run and publish that lottery to get the email (screenshot below).
- …
=> fix: lottery translations script bug

.circleci/config.yml, api/prisma/seed-staging.ts, sites/partners/cypress/e2e/default/09-lottery.spec.ts, sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts, sites/partners/cypress/fixtures/partnerUser.json, sites/partners/cypress/support/commands.js, sites/partners/cypress/support/index.d.ts, sites/partners/src/components/listings/ListingFormActions.tsx, sites/partners/src/components/listings/PaperListingForm/dialogs/CloseListingDialog.tsx, sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx, sites/partners/src/components/users/FormUserManage.tsx, sites/partners/src/components/users/JurisdictionAndListingSelection.tsx, sites/partners/src/pages/listings/[id]/lottery.tsx, sites/partners/src/pages/users/index.tsx
This PR addresses #4206
Adds a Cypress test for the partners lottery flow happy path (flow described in ticket). It is a longer test (took 54 seconds), and the partners Cypress suite is our longest suite, so this would increase time-to-green by one minute. I think we have space to reduce our other partners Cypress tests that are less effective or should be unit tests (added this to the workshop agenda).
Check out the test if you'd like!
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't …
=> test: lottery cypress test

sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx
This PR addresses #4243 
It seems like one of the other commits in to main fixes the issue of the drawer not opening, and this fixes the preview in the table so you can see the preview of the table before its changed
Create or edit a listing such that:
- the listing is closed, marked as running a lottery, marked as NOT running the lottery through the partner site
- upload lottery results
- go in to edit the listing and make sure you can edit the uploaded lottery results (delete results, switch to a different file, etc)
- Either (1) explicitly ask a clarifying question, (2) request changes, or …
=> fix: allows uploading lottery result update

api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, api/test/unit/services/listing.service.spec.ts
This PR addresses #4242 
This fixes a bug where updating a listing with lottery results uploaded was not working
Create or edit a listing such that: 
- it is closed
- it is set to lottery
- the lottery not run through the partner site (you will manually upload lottery results)
- manually uploaded lottery results
go back in to edit the listing -> attempt to save -> it should now save
=> fix: saving listing with uploaded lottery

api/src/services/lottery.service.ts
This PR addresses #(insert-number-here)
Lottery auto publish cron job was incorrectly binded and thus not running. Now correctly binded.
Set the `LOTTERY_PUBLISH_PROCESSING_CRON_STRING` env var to something in the next few minutes and run the api. Verify "WARN autoPublishLotteryResults job running" and "WARN Changed the status of ${number} lotteries" both appear in the console.
=> fix: correctly bind publish job

api/src/services/listing.service.ts
This PR addresses #(insert-number-here)
Unused import was removed in [saving listing with uploaded lottery](https://github.com/bloom-housing/bloom/pull/4277/files#diff-079326447730b9addbac740f4bcf63427c1f2c0c79be780bc72edcd7706580e4L2) but used in [listing duplication endpoint](https://github.com/bloom-housing/bloom/pull/4307/files#diff-079326447730b9addbac740f4bcf63427c1f2c0c79be780bc72edcd7706580e4R979). Merging missed to re-include import statement.
Run api locally and verify not import error occurs.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the …
=> fix: add back missing import

api/prisma/migrations/16_lottery_total/migration.sql, api/prisma/schema.prisma, api/src/controllers/lottery.controller.ts, api/src/dtos/applications/application-lottery-position.dto.ts, api/src/dtos/applications/application-lottery-total.dto.ts, api/src/dtos/listings/listing-update.dto.ts, api/src/dtos/listings/listing.dto.ts, api/src/dtos/lottery/lottery-public-result.dto.ts, api/src/dtos/lottery/lottery-public-total.dto.ts, api/src/services/lottery.service.ts, api/test/integration/lottery.e2e-spec.ts, api/test/unit/services/google-translate.service.spec.ts, api/test/unit/services/lottery.service.spec.ts, shared-helpers/src/types/backend-swagger.ts, sites/partners/src/lib/listings/formTypes.ts, sites/public/src/pages/account/application/[id]/lottery-results.tsx
Related to merge of: https://github.com/bloom-housing/bloom/pull/4275
This PR addresses #4224
Adds in the total number of applicants and number of applicants per preference into the public site lottery results page.
I created a new table that stores the totals in a very similar way to how we store lottery positions. I had performance concerns over querying the lottery positions table every time a user needs to see their results page as it will have 1000s of rows after just one lottery is run.
There's also some misc. test coverage.
Submit an application to a listing and claim a preference. Run and release the lottery. Ensure that the total number of applications and number of applications that claimed that preference are correct.
Handling listings without preferences or a user who doesn't …
=> feat: public lottery view, totals data

sites/partners/__tests__/lib/helpers.test.ts, sites/partners/cypress/support/commands.js, sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx, sites/partners/src/lib/helpers.ts
This PR addresses #4292
Allows you to enter partial dates in the partners listing form (i.e. `9/6/1994` instead of requiring `09/06/1994`)
Attempt to save a listing with a lottery date that has a partial month and day and ensure you don't receive an error.
=> fix: partial character date formatting

sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses #4300 
This PR completes an outstanding todo to include the releaseDate in the partners messaging seen in the issue description. It also handles the case of releasing and retracting by finding the most recent release date.
This can be tested by creating a lottery listing as an admin and releasing that lottery. Then as a partner user see the date and time reflected in the lottery publish card. You can also test retracting and releasing the lottery to see the time updated.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if …
=> fix: add releaseDate to partner card

api/src/services/listing.service.ts, api/src/services/lottery.service.ts, api/test/integration/lottery.e2e-spec.ts, api/test/unit/services/lottery.service.spec.ts
This PR addresses #4312 
A change to not send lottery published emails to applications that have been marked as a duplicate. Also changes the email we are sending the lottery results to to the email associated with the account that applied, as opposed to the email field on the application, since the account email has been verified. Chatted with Sarah about what this means for HBA and lottery without them having mandated accounts - before we would release lottery in HBA we may have to consider turning mandated accounts on for the public side experience of receiving results - and that we should still use the account email here so folks know when they receive an email they need to login with that email to see the results.
Submit two applications while logged in under different email …
=> fix: dont send lottery emails to duplicate applications

api/src/services/application-flagged-set.service.ts, api/test/integration/application-flagged-set.e2e-spec.ts, api/test/unit/services/application-flagged-set.service.spec.ts
This PR addresses #4208 
When the `DUPLICATES_CLOSE_DATE` and `DUPLICATES_PROCESSING_CRON_STRING` environment variables are set 
the new AFS cron job should run for all listings that meet either of the following scenarios:
- Listing is closed after `DUPLICATES_CLOSE_DATE`
- Listing is not yet closed
There is an issue with the second scenario for some listings because we currently don't remove the `closed_at` field when a listing is reopened. This means that the old job will still get triggered if the previously closed time was before the duplicate close date
1. Close a listing
2. Reopen the listing
3. Set `DUPLICATES_CLOSE_DATE` to now (or some time after the time stamp of when you first closed the listing) and restart backend
4. add applications. Preferably multiple and at least one …
=> fix: tighten the rules for which afs job

sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
This PR addresses #4360 
This PR updates the defaultSelected Logic within the "Select Preference" drawer to match on id rather than text to handle multiple preferences with the same name.
Run locally, Log in to partners as an admin, Add preferences with the same name or make multiple copies of existing preferences, Add only some of the preferences with the same name to the listing, Save, Go back to Edit and view the preferences, and only the ones you selected will show as checked. Previously, all with the same name would show as selected.
- Either (1) explicitly ask a clarifying question, (2) …
=> fix: match pref on id

package.json, yarn.lock
`commitizen` has a dependency `cz-conventional-changelog` which itself depends on a vulnerable version of minimist - and it isn't a ranged dependency, so it is explicitly pulling in the vulnerable version. I was able to upgrade `commitizen` and remove `cz-conventional-changelog` because we aren't using it anymore.
[Dependabot alert
](https://github.com/bloom-housing/bloom/security/dependabot/140)[Issue in commitizen
](https://github.com/commitizen/cz-cli/issues/945)
I ensured that even with removing the conventional changelog setup, commitizen still works for me locally.
If you have commitizen set up locally, you can try committing with an unformatted commit and ensure it fails.
- Review the code itself from a style …
=> chore: manual dependabot - minimist

README.md, sites/public/README.md
Adds additional instructions to setup helpful extensions for CSS autocompletion to the READMEs
=> docs: update readme w extension instructions

sites/partners/page_content/locale_overrides/general.json
This PR addresses #4446 
Changes copy of retract lottery modal
On partners site in lottery tab confirmation modal after clicking retract should have new copy
=> fix: update retract modal copy

api/src/passports/mfa.strategy.ts, api/src/passports/single-use-code.strategy.ts, api/src/utilities/passport-validator-utilities.ts, api/test/unit/passports/passport-validator-utilities.spec.ts
This PR addresses #4473 
This PR changes the function isUserLockedOut to return the verified failedLoginAttempts count explicitly. Before, it was failing to reset after the lockout period was over because of an assumption that it was pass by reference rather than value.
Note that there is an existing bug in core: https://github.com/bloom-housing/bloom/issues/4284
This can be tested locally by locking out a public user via 5 failed password attempts (you'll have to verify in network tab). Then, go into the DB and set that user's last login at date to be last year. Lastly, try to log in again with an incorrect password and see that the count has been reset (via the network tab).
- Review the code itself from a style …
=> fix: return updated failed login attempts

shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json
This PR addresses #4455 
Adds additional copy about a 1 hour expiry for password reset.
Go to the Forgot Password screen, enter an email address, and verify the updated copy in the toast notification.
=> feat: update toast messages for Forgot Password

api/src/services/listing.service.ts, api/test/unit/services/listing.service.spec.ts
This PR addresses #773 
During Qa, it was discovered that the publishedAt date was showing as none for many open listings. This was because we were not covering the case where a user publishes a listing from scratch, never first saving it as a draft.
Create a listing from scratch and publish it without saving it as a draft. In the partner's listing table, you should see today's date.
=> fix: publishedAt on create

api/src/services/listing.service.ts
This PR addresses [#(982)](https://github.com/metrotranscom/doorway/issues/982)
Listings with a BuildingSelectionCriteriaFile could not be duplicated due to an issue re-creating the asset. This is fixed by not passing the existing asset id to the new copy.
- Create or edit a listing to have a building selection criteria file.
- Copy the listing
- Confirm the building selection criteria file is present on the copy listing
- Publish the copy listing
- Go to the public site, view the copy listing, view the building selection criteria file
- Either (1) explicitly ask a clarifying question, (2) …
=> fix: building selection criteria adjustment

sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx, sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
This PR addresses [#977 ](https://github.com/metrotranscom/doorway/issues/977)
This PR updates the deleteModal open logic to handle an orderId=0. When a user applies online, the first household member is set to an OrderId of 0 but when added via the partner's side, it adds it with an orderId of 1. This PR also updates the ordering on the partner's side so that a user sees the household members in the order they added them (public side is already demonstrating this behavior). However, I stopped short of refactoring the orderId to be used more consistently to avoid any risks in conflicting with existing data. Instead, that work is captured here: https://github.com/bloom-housing/bloom/issues/4511
Note: I had originally assumed the orderId was null causing this issue but querying production …
=> fix: household member delete + order

api/src/utilities/application-export-helpers.ts, api/test/unit/utilities/application-export-helpers.spec.ts, shared-helpers/__tests__/formKeys.test.ts, shared-helpers/src/utilities/formKeys.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/1009
The ticket also mentions cleaning up the instances where doorway entered a space to get the "other" field to save which this PR doesn't cover.
This PR includes two different empty string checks in the formKeys file which prevents the selection of other without entering further information from being filtered out or being stored with a colon and space. 
This can be tested by 
a) submitting an online app with a mix of demographic data (including other selections without any text inputted) and going to the partners portal to see that it was stored correctly
b) submit a **paper** app to the same listing with a unique mix of demographic data also including empty other selections and then edit this paper app multiple times …
=> fix: handle empty other race options

api/src/services/listing-csv-export.service.ts, api/test/unit/services/listing-csv-export.service.spec.ts
This PR addresses #1027 
The listing units csv export is displaying the incorrect AMI Chart percentage. It is grabbing the first value from the amiChart instead of getting the percentage off of the unit table
Note:
- There are currently no tests that cover this part of the code and we should add those as a separate issue
After a clean reseed In the partner site click the "Export to CSV" button on the listings page and compare the values to the listings
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, …
=> fix: use correct ami percentage in csv

api/src/utilities/application-export-helpers.ts
This PR addresses [#(4536)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4536)
For preferences that required an address to be input, they were appearing for the application export but not for the lottery export. This adjustment allows it to work correctly for both.
On the partner site, create/update a listing to be a lottery listing with a preference that requires/allows for an address to be input.
Submit an application for the listing, claim the preference and include an address.
Export applications and verify the preference and preference address appear correctly.
Close the listing, run the lottery, export the lottery, and verify the preference and preference address appear correctly.
- Ensure the author …
=> fix: preference addresses not showing up in lottery export

sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
This PR addresses #4298
The Household Members section of an Application form was persisting across "Submit & New" saves in Partners, which this PR fixes.
Try saving a new Application with additional Household Members by clicking Submit & New, and then verify there are no members (the form is fully cleared).
=> fix: clear household members for Submit & New in Applications

api/src/main.ts, api/src/modules/email.module.ts, api/src/services/email.service.ts, api/src/services/user.service.ts, api/test/integration/user.e2e-spec.ts, api/test/unit/services/email.service.spec.ts, api/test/unit/services/user.service.spec.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/983, 
This PR pulls over the appropriate pieces from [this Doorway PR](https://github.com/metrotranscom/doorway/pull/1013). Specifically the additional logging around bulk email sends. The rest of the PR is not required in Core since we do not use AWS SES.
NOTE:
- An additional change of now logging "LOG" level via the logger
- I feel like we should get as much as possible in the logs as possible. I think this would have minimal impact since using `console.log` was already getting logged to papertrail
This can be tested by going through the flows that trigger a bulk email send and make sure that appropriate logging appears in the terminal
- Review the …
=> fix: add additional logging for bulk email sends

api/src/main.ts
This PR does not address a specific ticket but will be useful for using the API in deployed environments
If passkey is enabled for an environment you are not able to use the swagger UI. This adds an optional header option to the UI to be able to send the passkey in the request.
I tested that this did not impact the backend-swagger when running `yarn generate:client`
Start up the backend and go to `http://localhost:3100/api`. For all endpoints you should see "passkey" as a header field. If you enable passkey locally you should be able to use this UI to send any request.
- Either (1) explicitly …
=> fix: add passkey to swagger

sites/partners/src/lib/listings/UnitsFormatter.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/1059 and https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4220
This PR saves Studios and SROs to have zero bedrooms rather than null bedrooms. This doesn't change much in core but it is critical for filtering in doorway which is a feature core will likely get soon.
After merge, I will be running the following query in Core, HBA, and Doorway since querying existing data showed that all null bedroom units were Studios or SROs
`Update units set num_bedrooms=0 where num_bedrooms is null;`
This can be tested by creating SROs and Studios on the partner side and then checking the units table to ensure they are saved as zero rather than null number of bedrooms.
- Read and understand the …
=> fix: set studio + sro to zero bedrooms

api/src/controllers/listing.controller.ts, api/src/dtos/listings/listings-query-params.dto.ts, api/test/integration/listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-public.e2e-spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(4515)](https://github.com/bloom-housing/bloom/issues/4515)
Creates new listings list endpoint with the same functionality but uses a POST instead of a GET.
Using the API, call the new endpoint `listings/list` using POST. Should have the same results as the GET `listings?` endpoint.
=> feat: filterable listing list post endpoint

sites/partners/src/lib/applications/formatApplicationData.ts
This PR addresses #4502 
NOTE: Pulls over some but not all code from [this Doorway PR](https://github.com/metrotranscom/doorway/pull/979) to fix a user's inability to successfully save single digit dates i.e. `1/01/2025, 1/1/2025, 01/1/2025`
Run the same process from the Loom video in #4502 and you should be able to edit and save dates in either `M/D/YYYY` or `MM/DD/YYYY` format
=> fix: submission date time format on paper app

api/src/utilities/unit-utilities.ts
This PR addresses #4631
The units summarization process was failing to handle multiple units without rent information. The first unit was correctly handled with "t.n/a" in the getDefaultSummary function but then from there the inputs to a minMax function were t.n/a and null leading to the NaN. This fix avoids the minMax comparison if the unit's associated field is null.
Add multiple units of the same unit type to a listing that have no rent or rent as a percentage of income information. Ensure that the unit summary displays with n/a rather than NaN per month.
- Either (1) explicitly ask a …
=> fix: null checks in minMax process

api/prisma/seed-helpers/listing-factory.ts, api/src/dtos/listings/listings-filter-params.dto.ts, api/src/dtos/listings/listings-query-body.dto.ts, api/src/dtos/listings/listings-query-params.dto.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses #(4542)
Doorway frontend (as well as Detroit) send back strings for bedrooms and bathrooms. Filter being a number without casting the string to a number caused 500 errors and the map to break. Adding @Type casts the string to a number and allows for numbers to be sent as well. Still catches bad strings that are not numbers.
Other fixes caught:
- isArray accidentally removed from @ApiPropertyOptional for OrderBy and OrderDir fields, caused complaints in FE code, no errors
- Adjust listing-factory to alleviate issue in Doorway e2e tests
Spin up backend.
Test bedroom and bathroom filters. Use both numbers, numbers as strings and random strings (success, success, failure respectively) …
=> fix: minor filter adjustments for doorway

shared-helpers/src/locales/general.json, sites/public/__tests__/pages/sign-in.test.tsx
This PR addresses #4560 
This PR adds unit tests for:
- All page elements on page
- Field validation
- If user is not logged in
This PR does not add a test for:
- If user is logged in, they should be redirected to /account/dashboard. This currently is not happening, so I created a separate ticket to address this and handle the test after fixing.
- Run `yarn test:unit __tests__/pages/sign-in.test.tsx` in `public`
- LMK if i'm missing anything!
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you …
=> test: sign-in page integration test 

api/.env.template, api/package.json, api/src/utilities/s3-helpers.ts, api/yarn.lock
This PR addresses https://github.com/bloom-housing/bloom/issues/4590
- A private S3 bucket was spun up under the exygy aws account
- a service account that has the perms to upload and generate a presign url were spun up
- helper functions to upload/generate a presigned url were spun up 
The way I tested this was attaching the `uploadToS3Again()` & `generatePresignedGetURL()` to the health check endpoint and uploading there
you will need to add the new env variables, if you need help grabbing those lemme know
e2e tests will happen once we have this attached to endpoints
unit tests wouldn't really make much sense since this is pretty much just integration with AWS s3 code
- Review the code itself from a style point of …
=> feat: adds helper functions to generate presigned url

shared-helpers/package.json, sites/partners/package.json, sites/public/__tests__/components/browse/ListingBrowse.test.tsx, sites/public/__tests__/components/browse/ListingCard.test.tsx, sites/public/__tests__/components/listing/listing_sections/Availability.test.tsx, sites/public/__tests__/components/listing/listing_sections/MainDetails.test.tsx, sites/public/__tests__/lib/helpers.test.tsx, sites/public/package.json, sites/public/src/components/browse/ListingBrowse.tsx, sites/public/src/components/browse/ListingCard.module.scss, sites/public/src/components/browse/ListingCard.tsx, sites/public/src/components/listing/ListingViewSeeds.tsx, sites/public/src/components/listing/listing_sections/Availability.module.scss, sites/public/src/components/listing/listing_sections/Availability.tsx, sites/public/src/components/listing/listing_sections/MainDetails.tsx, sites/public/src/lib/helpers.module.scss, sites/public/src/lib/helpers.tsx, sites/public/src/pages/listings.tsx, yarn.lock
This PR addresses #4710
We ended up with some inconsistencies in listing statuses between the browse and detail pages in Seeds, and the introduction of the under construction status complicated things. This PR makes two updates, to:
1. The colors of the listing type messages on the browse page
2. The availability section at the top of the right rail on the detail page
This PR also temporarily updates just the Seeds browse page to also show closed listings until we have tabs, so that we can test that state.
You can compare [this deploy preview](https://deploy-preview-4689--bloom-public-seeds.netlify.app/listings) to the [core Seeds environment](https://bloom-public-seeds.netlify.app/listings).
For the browse page:
* The `Lottery` and `FCFS` review types are still primary, the `Open …
=> refactor: listing status messages

api/package.json, api/yarn.lock, shared-helpers/src/auth/catchNetworkError.ts, sites/partners/package.json, sites/public/package.json, yarn.lock
Related to https://github.com/metrotranscom/doorway/pull/1107 and https://github.com/metrotranscom/doorway/issues/1156
There is no official migration guide (see lots of people upsetti spaghetti about this [here](https://github.com/axios/axios/discussions/4996) lol). But there is a [community one](https://github.com/bmuenzenmeyer/axios-1.0.0-migration-guide). Because we already were on > 1 on the backend, it required no code changes. Our current version was released in 2022.
We use axios to fetch listings data on the public and partners sites, and on the partners site to upload an image. Ensure these flows work.
- Pull the changes down locally and test that the …
=> chore: upgrade axios

api/prisma/seed-helpers/listing-data/elm-village.ts, api/prisma/seed-helpers/listing-data/hollywood-hills-heights.ts, api/prisma/seed-helpers/listing-data/lakeview-villa.ts, api/prisma/seed-helpers/listing-data/sunshine-flats.ts, api/prisma/seed-helpers/reserved-community-type-factory.ts, api/prisma/seed-staging.ts, api/test/integration/reserved-community-type.e2e-spec.ts
#4740 
This PR addresses the following things:
* With more jurisdictions in the system we would like to have more pre-set listings for local development. This adds an additional listing to the Lakeview jurisdiction. I would like us to continue to add listings as we develop features so that we have a good representation of the ecosystem
* Reserved Community Type is currently tied to a jurisdiction, but outside of the db we don't care what jurisdiction it is tied to. Because of that this PR now only generates one set of the community types so there aren't duplicates in the dropdown (hopefully the flaky cypress test will be more consistent now)
* Adds the community types to the seeded data that were missing 
All tests should pass especially the cypress ones
After running the staging seeds …
=> fix: add more lakeview seeded data

api/src/dtos/auth/confirm.dto.ts, api/src/dtos/auth/update-password.dto.ts
This PR addresses [slack conversation](https://exygy.slack.com/archives/C03PB25AVTR/p1745414853923449)
On rare occasions confirmation tokens can be longer than 256 characters. This causes an issue when the user tries to confirm their account because we have a MaxLength of 256 on the token field
The confirmation and forget password flows should fully work
=> fix: remove token max length

api/prisma/seed-helpers/feature-flag-factory.ts, api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts
This PR addresses #4751 
The duplication (copy) of listings already works for listings that use unit groups instead of units. However, if you don't want to copy the units a small change was needed.
* Note: open question. Do we require a language change from "include units" to "include unit groups" when it is a unit group jurisdiction
To Copy with units groups
* Seed the staging data
* open up one of the "lakeview" listings in the partner site
* Click "copy" for the listing
* Enter a new listing name and submit
* Verify the listing along with the unit groups were transferred.
To copy without unit groups
* Seed the staging data
* open up one of the "lakeview" listings in the partner site
* Click "copy" for the listing
* uncheck the "include units" checkbox
* Click submit
* Verify the …
=> fix: allow duplication to not copy unit groups

api/src/dtos/listings/listings-filter-params.dto.ts, api/src/enums/listings/filter-key-enum.ts, api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, api/test/unit/services/listing.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(4764)](https://github.com/bloom-housing/bloom/issues/4764)
Detroit requires filtering by programs (aka multiselect questions (aka aka "community types" in Detroit)). To allow this, a new filter was added to the listings filter list. We can now filter listings based on associated multiselectQuestionIds, be that preferences or programs.
- Start up the backend.
- View the db table listingMulitselectQuestions and copy a multiselectQuestionId
- Go to http://localhost:3100/api#/listings/filterableList
- Pass in the copied id in the following format for the filter
`  "filter": [
{
"$comparison": "IN",
"multiselectQuestions": ["cd7a9210-3d47-44ab-9d68-4e77c5f392cf"]
}
]`
- Ensure the correct listings were returned
- Ensure the author has added …
=> feat: listing filter by mutliselect questions

sites/partners/__tests__/components/listings/ListingFormActions.test.tsx, sites/partners/__tests__/components/listings/PaperListingForm/index.test.tsx, sites/partners/__tests__/components/listings/PaperListingForm/sections/CommunityType.test.tsx, sites/partners/src/components/listings/ListingFormActions.tsx, sites/partners/src/components/listings/PaperListingForm/index.tsx, sites/partners/src/components/listings/PaperListingForm/sections/CommunityType.tsx
This PR addresses #4731, #4748
There was a lot of repeated code in ListingFormActions file. Since there wasn't that much difference between each role type in the buttons that are shown it was possible to remove the three if statements and add just a couple of extra checks to for specific actions.
I also noticed a bug where if the "hideCloseListingButton" was turned on partners could still see the close button
The following steps have been taken to test this refactor:
* All tests still pass
* Two new tests were added to the listingFormActions
* New integration tests were added for the PaperFormListing
* This [document](https://docs.google.com/document/d/1JR7l1v_x5p3vaAmABN30YlM3xJA8BHnlg7EFGzqOr5M/edit?usp=sharing) was written up to track what each scenario should show
In order to test …
=> fix: refactor listingFormActions

package.json, sites/public/.env.template, sites/public/next.config.js, sites/public/src/pages/listing/[id]/[slug].tsx, ui-load-tester.rb, utilities/ui-load-tester.rb
This PR addresses https://github.com/metrotranscom/doorway/issues/1271
This adds a ui load tester script
more importantly, this changes how we get listing data for the public listing detail page from `getServerSideProps` to `getStaticProps` this should mean that instead of the server generating the HTML for the public listing detail page each time it generates it once then holds onto it for 30 seconds before rebuilding it
Stand up the public site locally and verify you can hit the listing detail page
Aim the load tester at your listing detail page and make sure it stands up to most load tests (it'll break down at higher ends still)  …
=> feat: adds ui load tester & getStaticProps from getServerSideProps

api/src/permission-configs/permission_policy.csv, api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts, api/test/integration/permission-tests/permission-as-public.e2e-spec.ts, sites/public/src/lib/hooks.ts, sites/public/src/pages/listings-closed.tsx, sites/public/src/pages/listings.tsx
This PR addresses #4795 
As part of adding filtering by community type (detroit's version so functionally programs in the backend), we had to update the permissioning and add a new hook to the public side.
This can be tested by adding a console log for props.multiselectData and ensure the appropiate community types are coming through on a jurisdiction with swapCommunityTypeWithPrograms enabled.
=> fix: multiselect question public hook

sites/public/src/layouts/application-form.module.scss
This PR addresses #4897
* Set the applications process progress navbar color override to match the jurisdictions 
* Set app Jurisdiction to `Bloomington`
* Go to `/listings` and start the online application process
* The navigation progress bar should be in the jurisdiction color (in this case, blue)
* Switch application jurisdiction to `Lakeview`
* Repeat the application process 
* The navigation progress bar should match the new jurisdiction color (in this case, purple)
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very …
=> fix: update navbar to match jurisdiction color

sites/public/src/components/assistance/Assistance.tsx
This PR addresses #4423
It is request from [this comment](https://github.com/bloom-housing/bloom/issues/4423#issuecomment-2920367664)
It will change path to housing basics page (which is on detroit for now). Not sure if that should be `how-it-works` for core
i assume it was just placeholder.
go to `/get-assistance` page and click `Read about how it works`. It should redirect to `/housing-basics` (page itself is in bloom-detroit, so it will return 404)
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, …
=> fix: change path to housing-basics

sites/partners/cypress/e2e/default/03-listing.spec.ts, sites/partners/cypress/fixtures/listing.json, sites/partners/cypress/fixtures/minimalListing.json, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx, sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx, sites/public/src/pages/404.tsx
This PR addresses #5002
The "Are you using the common digital application?" has stopped autofilling.
The commit that "caused" it had a UIC upgrade that ended up including 10 UIC commits - [this is the UIC commit](https://github.com/bloom-housing/ui-components/pull/169) that causes the issue but I still don't know why. It did include a few package upgrades that might have had some unexpected effects.
Create or update a listing with a value for `Are you using the common digital application?` which appears after selecting `Yes` to `Is there a digital application?` and ensure the value re-populates after saving and reopening the form.
I updated our listing Cypress test to also re-open an entered listing to make sure all of the fields populate as expected, as we've had lots of bugs around …
=> fix: common app selection

sites/public/__tests__/components/browse/ListingCard.test.tsx, sites/public/src/components/browse/ListingCard.tsx, sites/public/src/components/listing/listing_sections/MainDetails.tsx
This PR addresses #4889 
* Remove feature-specific accessibility tags 
* Update tag generation calls to show accessibility tags also in the listing browse card and the listing preview page 
General Accessible tag:
* Go to the partner's site and enable any accessibility feature on an under-construction listing
* Go to the public site homepage and view the modified listing card (The "Accessible" tag should be visible)
* Go to the`/listings` page and verify that the listing card also contains the "Accessible" tag
* Click the listing card and verify that the "Accessible" tag is also visible on the listing specific page
- Pull the changes down locally and test that the …
=> fix: fix accessibility tag

api/prisma/migrations/27_add_super_admin/migration.sql, api/prisma/schema.prisma, api/prisma/seed-helpers/user-factory.ts, api/prisma/seed-staging.ts, api/src/dtos/users/user-role.dto.ts, shared-helpers/src/auth/AuthContext.ts, shared-helpers/src/types/backend-swagger.ts, sites/partners/__tests__/components/listings/ListingFormActions.test.tsx, sites/partners/__tests__/pages/admin/index.test.tsx, sites/partners/page_content/locale_overrides/general.json, sites/partners/src/pages/admin/index.tsx
This PR addresses #4533 
This PR adds a new page to the partner site `/admin` which allows the toggling of feature flags for jurisdictions. This page can only be viewed by a new role "superAdmin" which must be manually added to a user. It is also not exposed as a link anywhere so you must directly hit it.
The page does the following:
* A button to add all of the new feature flags to the database "Add All New Feature Flags". When clicked the `/addAllNew` feature flag endpoint is hit
* Displays all of the jurisdictions in a table and has a button to edit the feature flags associated with it. 
* Displays all of the feature flags in a table and has a button to edit the jurisdictions associated with it
Note: No designs were used to create this page. Consider it to be an mvp so the look and …
=> feat: add new feature flag UI

sites/public/src/pages/preview/listings/[id].tsx, sites/public/styles/overrides.scss
This PR addresses #4800 
For environments with the Seeds listing design enabled, this will show a preview of the listing using the Seeds version.
This can be reviewed here:
https://deploy-preview-5076--bloom-lakeview.netlify.app/preview/listings/e0c9e35a-a672-4b7f-802c-faf91d0f098b
and the non-Seeds version:
https://deploy-preview-5076--bloom-exygy-dev.netlify.app/preview/listings/16815545-3a1a-4639-b2e9-94206a16ba6a
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review …
=> feat: preview listing will now show the Seeds version

api/prisma/seed-helpers/listing-data/hollywood-hills-heights.ts, api/prisma/seed-helpers/listing-data/little-village-apartments.ts
This PR addresses #(insert-number-here)
Missing application method for Hollywood Hills Heights and Little Village Apartments listings in the seed data made the listings un-editable on the partners site.
Reseed the db
Log into the partner site
Open Hollywood Hills Heights and Little Village Apartments
Open the edit view
Successfully save a change
=> fix: add missing app methods to seed data

shared-helpers/src/utilities/photos.ts, sites/public/__tests__/components/listing/listing_sections/Apply.test.tsx, sites/public/src/components/listing/ListingView.tsx, sites/public/src/components/listing/ListingViewSeedsHelpers.tsx, sites/public/src/components/listing/listing_sections/Apply.tsx, sites/public/src/components/shared/FormSummaryDetails.tsx
This PR addresses #5080 
This PR addresses the following points in the issue:
1. The fallback image is now utilized. There was a typo creating this bug.
3. The styling is fixed by removing the unnecessary tailwind which allows the overrides to apply correctly. NOTE that this slightly changes the visuals of the core experience but since anything seeds related should be using sans serif and I assume we'd want the h3 headers to align in styling rather than create a custom one off styling for the application, I made the update
You is a example of old styling, Household Details is an example of new styling
4. Mandated accounts should not force a user to sign in if the application is not a common app. This is achieved by pulling a doorway PR back to core (with slight tweaks) …
=> feat: bash fixes 1

shared-helpers/src/utilities/photos.ts
This PR addresses #5075
If a listing gets published with no image, there was old fallback code to look at assets directly attached to a listing. The problem was that JSON value could be `{}` instead of `[]`. I'm not sure why even after spending some time poking around, so I simply add this Array type check. If we don't like that approach, an alternative might be to stop look at listings assets (is that even still a requirement?).
Save a new published listing with no image, then verify you can view it on public and see a fallback image placeholder.
- Either (1) explicitly ask a clarifying …
=> fix: use listing assets only when array, refactor of photo helper

api/prisma/seed-helpers/listing-data/blue-sky-apartments.ts, api/prisma/seed-helpers/listing-data/hollywood-hills-heights.ts, api/prisma/seed-helpers/listing-data/lakeview-villa.ts, api/prisma/seed-helpers/listing-data/little-village-apartments.ts, api/prisma/seed-helpers/listing-data/sunshine-flats.ts, api/prisma/seed-helpers/listing-data/valley-heights-senior-community.ts, api/prisma/seed-helpers/listing-factory.ts, api/prisma/seed-staging.ts
To improve our seed data, two changes:
- remove setting applicationDueDate explicitly to null for seeded listings
- add logic to allow associating seeded partner users to listings and associate one partner with all listings on the main jurisdiction
Reseed your local
Run the partner site and backend
Sign in as partner@example.com
Check all bloomington listings are associated with the user
Look into the listings and confirm they all have applicationDueDate set by default
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small …
=> chore: improve seed data

sites/public/src/components/browse/FilterDrawer.tsx
This PR addresses a logic bug from PRs #5102 & #5107
The Units Available filter was updated to Vacant Units when unit groups feature flag is enabled, but the way the label was updated caused a backend error, which is now apparent in testing the backend updates.
Once this is merged into Detroit, we can do a final QA pass.
=> fix: use the right backend availability key

sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx, sites/partners/src/components/shared/TextEditor.tsx
Issue #5174 
[This PR](https://github.com/bloom-housing/bloom/pull/5175) introduced a regression, where now when you hover over the label for the rich text editor, the first item in the menu bar also gets the visual hover state.
https://github.com/user-attachments/assets/7bb8eb1f-903f-49a4-a12f-035d862202c5
Resolves the hover issue, while still maintaining the initial goal of having a label associated with the editor. If you use a screen reader, you can see the textbox still announces the label name.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the …
=> fix: improve rich text a11y pt 2

sites/partners/__tests__/components/applications/sections/FormDemographics.test.tsx
This PR addresses #5083 
This is a follow up to this PR: https://github.com/bloom-housing/bloom/pull/5199 since I forgot to include Partner's test coverage.
Ensure the tests pass.
=> fix: add partners testing

sites/public/src/components/listing/listing_sections/AdditionalFees.tsx
This PR addresses #5047
Previously, if deposit min and/or max wasn't present, the entire Deposit section under Additional Fees wasn't shown. Now, it will be shown even if deposit helper text alone is available.
Save a listing with deposit helper text but no deposit min/max, verify the Deposit section is still shown. Then remove the helper text and verify the section is hidden.
=> feat: always show deposit helper text if present

sites/public/cypress.config.ts
Our cypress config was simply checking if `SHOW_NEW_SEEDS_DESIGNS` was set, not the value. This was causing failures when we set it to FALSE. Fix is needed to improve HBA & Doorway seed data and testing.
In your local public/.env file, set `SHOW_NEW_SEEDS_DESIGNS` to FALSE
Run application
Run public Cypress tests
application-submit test should pass
In your local public/.env file, set `SHOW_NEW_SEEDS_DESIGNS` to TRUE
Run application
Run public Cypress tests
application-submit test should pass
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if …
=> chore: set seeds for circleci

shared-helpers/src/locales/general.json, sites/public/__tests__/lib/helpers.test.tsx, sites/public/src/components/browse/ListingCard.tsx, sites/public/src/lib/helpers.tsx
This PR addresses #5196 
Brings back status for unit groups listings.
Basically we need to test those AC's and check on `localhost:3000/listings` if it displays properly:
- If Under Construction, should show status as "Under Construction" + coming soon date (stay as-is)
- If Lottery - status will show "Lottery” + due date if applicable
- If FCFS (vacant units entered) and open waitlist - status will show ‘FCFS” + due date if applicable
- If FCFS (vacant units entered) and closed waitlist - status will show ‘FCFS” + due date if applicable
- If only open waitlist units (no vacant units entered) - status will show “Open waitlist” + due date if applicable
- If only closed waitlist (no vacant units entered) - status will show “Closed waitlist” (if there is a due date entered, it should be …
=> fix: Resurface review order status for unit groups

api/prisma/seed-staging.ts, shared-helpers/src/utilities/Address.tsx, sites/public/__tests__/components/browse/ListingCard.test.tsx, sites/public/src/components/listing/listing_sections/MainDetails.tsx, sites/public/src/components/listing/listing_sections/Neighborhood.tsx
Allows for a listing to not have the address filled out and still render. Currently the browse and detail pages in Detroit dev when we bring over the replatforming breaks without an address ([deploy preview](https://deploy-preview-1685--detroit-public-dev.netlify.app/listings)). Some of the test data in old Detroit dev does not have an address.
Detail page: Check out a preview of this Nada Hill listing with no address: https://deploy-preview-5307--bloom-public-seeds.netlify.app/preview/listings/5d6629cf-a37d-4cfb-8600-3ca4c2b64500
Browse page: The browse page needs to be tested locally - set the public env jurisdiction variable to Nada Hill and create a listing with no address.
- Review the code itself from a style …
=> fix: allow empty address

sites/partners/next.config.js, sites/public/next.config.js
This attempts to resolve our intermittent failing Netlify builds due to out of memory issues.
[Documentation
](https://nextjs.org/docs/app/guides/memory-usage#disable-static-analysis)
Because we already run linting in CI and locally pre-commit, which is where we are getting OOM, we don't need to also run it during a build.
=> fix: oom builds

shared-helpers/src/types/backend-swagger.ts, sites/public/src/components/listing/ListingView.tsx
This PR addresses bug found during Doorway bash, but related to #5117 
When testing this change in Doorway it was noticed that the new "what to expect additional" field was added to the partners site but because it does not use the new seeds public changes the additional text is not shown anywhere.
This change adds it to the older listing details page.
Prerequisite for both scenarios is the `SHOW_NEW_SEEDS_DESIGNS` flag for the public site must be turned to `FALSE`
1. create or edit a listing in partners. Fill out the "Tell the applicant any additional information" field with data and publish the listing
2. Go to the public site and you should see the "read more" button within the "What to Expect" section for that listing.
3. On clicking the "read more" you should see the data filled out. …
=> fix: add what to expect additional for non-seeds page

sites/partners/__tests__/pages/listings/lottery.test.tsx, sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses #5422
Please include a summary of the change and which issue(s) is addressed.
1. Sign in as an admin
2. Creat a listing enabling lottery.
How is the application review order determined?
- Lottery
- Will the lottery be run in the partner portal?
- Select time
3. Close the listing
4. Lottery tab will then appear
5. On the lottery tab, click Run lottery
6. Click on release lottery to partners
7. Log in as a JA or JA (NO PII) 
8. Look for the closed listing 
9.  Click on the Lottery tab
10.  Should NO see the publish button
- Pull the …
=> feat: Remove publish lottery button on JA roles 
